// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package charts.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Charts module
	public static java.util.List<charts.proxies.DataPoint> dS_ChartData(IContext context, charts.proxies.DataPoint _chartData)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ChartData", _chartData == null ? null : _chartData.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Charts.DS_ChartData").withParams(params).execute(context);
		java.util.List<charts.proxies.DataPoint> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(charts.proxies.DataPoint.initialize(context, obj));
		}
		return result;
	}
	public static charts.proxies.CJsChart dS_ChartJS_CreateLineChart(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Charts.DS_ChartJS_CreateLineChart").withParams(params).execute(context);
		return result == null ? null : charts.proxies.CJsChart.initialize(context, result);
	}
	public static charts.proxies.CJsChart dS_ChartJS_GetData(IContext context, charts.proxies.CJsChart _chartJs)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ChartJs", _chartJs == null ? null : _chartJs.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Charts.DS_ChartJS_GetData").withParams(params).execute(context);
		return result == null ? null : charts.proxies.CJsChart.initialize(context, result);
	}
}