// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package goodies.proxies;

public class DialogboxAnswer
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dialogboxAnswerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Goodies.DialogboxAnswer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		YesOrNo("YesOrNo");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DialogboxAnswer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Goodies.DialogboxAnswer"));
	}

	protected DialogboxAnswer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dialogboxAnswerMendixObject)
	{
		if (dialogboxAnswerMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Goodies.DialogboxAnswer", dialogboxAnswerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Goodies.DialogboxAnswer");

		this.dialogboxAnswerMendixObject = dialogboxAnswerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DialogboxAnswer.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static goodies.proxies.DialogboxAnswer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return goodies.proxies.DialogboxAnswer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static goodies.proxies.DialogboxAnswer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new goodies.proxies.DialogboxAnswer(context, mendixObject);
	}

	public static goodies.proxies.DialogboxAnswer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return goodies.proxies.DialogboxAnswer.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of YesOrNo
	 * @param yesorno
	 */
	public final goodies.proxies.Enum_YesOrNo getYesOrNo()
	{
		return getYesOrNo(getContext());
	}

	/**
	 * @param context
	 * @return value of YesOrNo
	 */
	public final goodies.proxies.Enum_YesOrNo getYesOrNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.YesOrNo.toString());
		if (obj == null)
			return null;

		return goodies.proxies.Enum_YesOrNo.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of YesOrNo
	 * @param yesorno
	 */
	public final void setYesOrNo(goodies.proxies.Enum_YesOrNo yesorno)
	{
		setYesOrNo(getContext(), yesorno);
	}

	/**
	 * Set value of YesOrNo
	 * @param context
	 * @param yesorno
	 */
	public final void setYesOrNo(com.mendix.systemwideinterfaces.core.IContext context, goodies.proxies.Enum_YesOrNo yesorno)
	{
		if (yesorno != null)
			getMendixObject().setValue(context, MemberNames.YesOrNo.toString(), yesorno.toString());
		else
			getMendixObject().setValue(context, MemberNames.YesOrNo.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dialogboxAnswerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final goodies.proxies.DialogboxAnswer that = (goodies.proxies.DialogboxAnswer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Goodies.DialogboxAnswer";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
