// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package goodies.proxies;

public class EntityB
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject entityBMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Goodies.EntityB";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		EntityB_EntityA("Goodies.EntityB_EntityA");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EntityB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Goodies.EntityB"));
	}

	protected EntityB(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject entityBMendixObject)
	{
		if (entityBMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Goodies.EntityB", entityBMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Goodies.EntityB");

		this.entityBMendixObject = entityBMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EntityB.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static goodies.proxies.EntityB initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return goodies.proxies.EntityB.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static goodies.proxies.EntityB initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new goodies.proxies.EntityB(context, mendixObject);
	}

	public static goodies.proxies.EntityB load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return goodies.proxies.EntityB.initialize(context, mendixObject);
	}

	public static java.util.List<goodies.proxies.EntityB> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<goodies.proxies.EntityB> result = new java.util.ArrayList<goodies.proxies.EntityB>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Goodies.EntityB" + xpathConstraint))
			result.add(goodies.proxies.EntityB.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of EntityB_EntityA
	 */
	public final goodies.proxies.EntityA getEntityB_EntityA() throws com.mendix.core.CoreException
	{
		return getEntityB_EntityA(getContext());
	}

	/**
	 * @param context
	 * @return value of EntityB_EntityA
	 */
	public final goodies.proxies.EntityA getEntityB_EntityA(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		goodies.proxies.EntityA result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EntityB_EntityA.toString());
		if (identifier != null)
			result = goodies.proxies.EntityA.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EntityB_EntityA
	 * @param entityb_entitya
	 */
	public final void setEntityB_EntityA(goodies.proxies.EntityA entityb_entitya)
	{
		setEntityB_EntityA(getContext(), entityb_entitya);
	}

	/**
	 * Set value of EntityB_EntityA
	 * @param context
	 * @param entityb_entitya
	 */
	public final void setEntityB_EntityA(com.mendix.systemwideinterfaces.core.IContext context, goodies.proxies.EntityA entityb_entitya)
	{
		if (entityb_entitya == null)
			getMendixObject().setValue(context, MemberNames.EntityB_EntityA.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EntityB_EntityA.toString(), entityb_entitya.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return entityBMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final goodies.proxies.EntityB that = (goodies.proxies.EntityB) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Goodies.EntityB";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
