// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package test.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the test module
	public static test.proxies.FibonacciPageHelper dS_FibonacciGenerator(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("test.DS_FibonacciGenerator").withParams(params).execute(context);
		return result == null ? null : test.proxies.FibonacciPageHelper.initialize(context, result);
	}
	public static void fibonacci(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("test.Fibonacci").withParams(params).execute(context);
	}
	public static java.lang.String fibonacci_Generator(IContext context, java.lang.Long _toTheNth)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ToTheNth", _toTheNth);
		return (java.lang.String) Core.microflowCall("test.Fibonacci_Generator").withParams(params).execute(context);
	}
	public static void fibonacci_Passingvalues(IContext context, test.proxies.FibonacciPageHelper _fibonacciPageHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("FibonacciPageHelper", _fibonacciPageHelper == null ? null : _fibonacciPageHelper.getMendixObject());
		Core.microflowCall("test.Fibonacci_Passingvalues").withParams(params).execute(context);
	}
	public static java.lang.String fibonacci_Serie10th(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.String) Core.microflowCall("test.Fibonacci_Serie10th").withParams(params).execute(context);
	}
}