// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package countriesv5.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the CountriesV5 module
	public static void countries_ISO3166_1_Overview_Open(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("CountriesV5.Countries_ISO3166_1_Overview_Open").withParams(params).execute(context);
	}
	public static countriesv5.proxies.CountryModuleSettings countriesModuleSettings_Retrieve(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("CountriesV5.CountriesModuleSettings_Retrieve").withParams(params).execute(context);
		return result == null ? null : countriesv5.proxies.CountryModuleSettings.initialize(context, result);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_A(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_A").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_B_Bon(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_B_Bon").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_Bos_Bur(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_Bos_Bur").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_C(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_C").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_D(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_D").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_E_F(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_E_F").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_G(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_G").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_H(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_H").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_I(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_I").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_J_K(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_J_K").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_L(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_L").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_M_Mar(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_M_Mar").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_Mau_Mya(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_Mau_Mya").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_NO(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_NO").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_P(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_P").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_QR(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_QR").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_SaintB_SaintP(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_SaintB_SaintP").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_Sao_Slo(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_Sao_Slo").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_Slo_Syr(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_Slo_Syr").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_T(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_T").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_Create_and_Update_Table_UVWXYZ(IContext context, system.proxies.Language _languageUS, system.proxies.Language _languageNL, boolean _dutchNENTable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LanguageUS", _languageUS == null ? null : _languageUS.getMendixObject());
		params.put("LanguageNL", _languageNL == null ? null : _languageNL.getMendixObject());
		params.put("DutchNENTable", _dutchNENTable);
		Core.microflowCall("CountriesV5.Country_ISO3166_1_Create_and_Update_Table_UVWXYZ").withParams(params).execute(context);
	}
	public static void country_ISO3166_1_DeleteTable(IContext context, java.util.List<countriesv5.proxies.Country_ISO3166_1> _country_ISO3166_1)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_country_ISO3166_1 = null;
		if (_country_ISO3166_1 != null)
		{
			listparam_country_ISO3166_1 = new java.util.ArrayList<>();
			for (countriesv5.proxies.Country_ISO3166_1 obj : _country_ISO3166_1)
				listparam_country_ISO3166_1.add(obj.getMendixObject());
		}
		params.put("Country_ISO3166_1", listparam_country_ISO3166_1);

		Core.microflowCall("CountriesV5.Country_ISO3166_1_DeleteTable").withParams(params).execute(context);
	}
	public static void country_UpdateAndOpen(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("CountriesV5.Country_UpdateAndOpen").withParams(params).execute(context);
	}
	public static java.lang.String countryToString(IContext context, countriesv5.proxies.Countries _country)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Country", _country == null ? null : _country.name());
		return (java.lang.String) Core.microflowCall("CountriesV5.CountryToString").withParams(params).execute(context);
	}
	public static void demonym_DeleteAll(IContext context, java.util.List<countriesv5.proxies.Demonym> _demonym)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_demonym = null;
		if (_demonym != null)
		{
			listparam_demonym = new java.util.ArrayList<>();
			for (countriesv5.proxies.Demonym obj : _demonym)
				listparam_demonym.add(obj.getMendixObject());
		}
		params.put("demonym", listparam_demonym);

		Core.microflowCall("CountriesV5.Demonym_DeleteAll").withParams(params).execute(context);
	}
	public static void demonym_Overview_Open(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("CountriesV5.Demonym_Overview_Open").withParams(params).execute(context);
	}
	public static java.lang.String demonym_Translation(IContext context, countriesv5.proxies.Demonym _nationality)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Nationality", _nationality == null ? null : _nationality.getMendixObject());
		return (java.lang.String) Core.microflowCall("CountriesV5.Demonym_Translation").withParams(params).execute(context);
	}
	public static void demonymTranslation_Overview_Open(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("CountriesV5.DemonymTranslation_Overview_Open").withParams(params).execute(context);
	}
	public static void dutch_NEN1888_Open(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("CountriesV5.Dutch_NEN1888_Open").withParams(params).execute(context);
	}
	public static void nEN1888_DeleteAll(IContext context, java.util.List<countriesv5.proxies.Nationality_Dutch_NEN1888> _nationality_Dutch_NEN1888List)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_nationality_Dutch_NEN1888List = null;
		if (_nationality_Dutch_NEN1888List != null)
		{
			listparam_nationality_Dutch_NEN1888List = new java.util.ArrayList<>();
			for (countriesv5.proxies.Nationality_Dutch_NEN1888 obj : _nationality_Dutch_NEN1888List)
				listparam_nationality_Dutch_NEN1888List.add(obj.getMendixObject());
		}
		params.put("nationality_Dutch_NEN1888List", listparam_nationality_Dutch_NEN1888List);

		Core.microflowCall("CountriesV5.NEN1888_DeleteAll").withParams(params).execute(context);
	}
	public static void oCh_NEN1888Boolean(IContext context, countriesv5.proxies.CountryModuleSettings _countryModuleSettings)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("countryModuleSettings", _countryModuleSettings == null ? null : _countryModuleSettings.getMendixObject());
		Core.microflowCall("CountriesV5.OCh_NEN1888Boolean").withParams(params).execute(context);
	}
}