// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datahubio_countrycodes.proxies;

public class CountryCode
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject countryCodeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataHubIo_CountryCodes.CountryCode";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CLDR_display_name("CLDR_display_name"),
		Capital("Capital"),
		Continent("Continent"),
		DS("DS"),
		Developed___Developing_Countries("Developed___Developing_Countries"),
		Dial("Dial"),
		EDGAR("EDGAR"),
		FIFA("FIFA"),
		FIPS("FIPS"),
		GAUL("GAUL"),
		Geoname_ID("Geoname_ID"),
		Global_Code("Global_Code"),
		Global_Name("Global_Name"),
		IOC("IOC"),
		ISO3166_1_Alpha_2("ISO3166_1_Alpha_2"),
		ISO3166_1_Alpha_3("ISO3166_1_Alpha_3"),
		ISO3166_1_numeric("ISO3166_1_numeric"),
		ISO4217_currency_alphabetic_code("ISO4217_currency_alphabetic_code"),
		ISO4217_currency_country_name("ISO4217_currency_country_name"),
		ISO4217_currency_minor_unit("ISO4217_currency_minor_unit"),
		ISO4217_currency_name("ISO4217_currency_name"),
		ISO4217_currency_numeric_code("ISO4217_currency_numeric_code"),
		ITU("ITU"),
		Land_Locked_Developing_Countries__LLDC_("Land_Locked_Developing_Countries__LLDC_"),
		Languages("Languages"),
		Least_Developed_Countries__LDC_("Least_Developed_Countries__LDC_"),
		M49("M49"),
		MARC("MARC"),
		Region_Code("Region_Code"),
		Region_Name("Region_Name"),
		Sub_region_Code("Sub_region_Code"),
		Sub_region_Name("Sub_region_Name"),
		TLD("TLD"),
		UNTERM_Arabic_Formal("UNTERM_Arabic_Formal"),
		UNTERM_Arabic_Short("UNTERM_Arabic_Short"),
		UNTERM_Chinese_Formal("UNTERM_Chinese_Formal"),
		UNTERM_Chinese_Short("UNTERM_Chinese_Short"),
		UNTERM_English_Formal("UNTERM_English_Formal"),
		UNTERM_English_Short("UNTERM_English_Short"),
		UNTERM_French_Formal("UNTERM_French_Formal"),
		UNTERM_French_Short("UNTERM_French_Short"),
		UNTERM_Russian_Formal("UNTERM_Russian_Formal"),
		UNTERM_Russian_Short("UNTERM_Russian_Short"),
		UNTERM_Spanish_Formal("UNTERM_Spanish_Formal"),
		UNTERM_Spanish_Short("UNTERM_Spanish_Short"),
		WMO("WMO"),
		Is_independent("Is_independent"),
		Official_name_ar("Official_name_ar"),
		Official_name_cn("Official_name_cn"),
		Official_name_en("Official_name_en"),
		Official_name_es("Official_name_es"),
		Official_name_fr("Official_name_fr"),
		Official_name_ru("Official_name_ru"),
		CountryFlag_CountryCode("DataHubIo_CountryCodes.CountryFlag_CountryCode");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CountryCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DataHubIo_CountryCodes.CountryCode"));
	}

	protected CountryCode(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject countryCodeMendixObject)
	{
		if (countryCodeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DataHubIo_CountryCodes.CountryCode", countryCodeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DataHubIo_CountryCodes.CountryCode");

		this.countryCodeMendixObject = countryCodeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CountryCode.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static datahubio_countrycodes.proxies.CountryCode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return datahubio_countrycodes.proxies.CountryCode.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static datahubio_countrycodes.proxies.CountryCode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new datahubio_countrycodes.proxies.CountryCode(context, mendixObject);
	}

	public static datahubio_countrycodes.proxies.CountryCode load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return datahubio_countrycodes.proxies.CountryCode.initialize(context, mendixObject);
	}

	public static java.util.List<datahubio_countrycodes.proxies.CountryCode> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<datahubio_countrycodes.proxies.CountryCode> result = new java.util.ArrayList<datahubio_countrycodes.proxies.CountryCode>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DataHubIo_CountryCodes.CountryCode" + xpathConstraint))
			result.add(datahubio_countrycodes.proxies.CountryCode.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CLDR_display_name
	 */
	public final java.lang.String getCLDR_display_name()
	{
		return getCLDR_display_name(getContext());
	}

	/**
	 * @param context
	 * @return value of CLDR_display_name
	 */
	public final java.lang.String getCLDR_display_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CLDR_display_name.toString());
	}

	/**
	 * Set value of CLDR_display_name
	 * @param cldr_display_name
	 */
	public final void setCLDR_display_name(java.lang.String cldr_display_name)
	{
		setCLDR_display_name(getContext(), cldr_display_name);
	}

	/**
	 * Set value of CLDR_display_name
	 * @param context
	 * @param cldr_display_name
	 */
	public final void setCLDR_display_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cldr_display_name)
	{
		getMendixObject().setValue(context, MemberNames.CLDR_display_name.toString(), cldr_display_name);
	}

	/**
	 * @return value of Capital
	 */
	public final java.lang.String getCapital()
	{
		return getCapital(getContext());
	}

	/**
	 * @param context
	 * @return value of Capital
	 */
	public final java.lang.String getCapital(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Capital.toString());
	}

	/**
	 * Set value of Capital
	 * @param capital
	 */
	public final void setCapital(java.lang.String capital)
	{
		setCapital(getContext(), capital);
	}

	/**
	 * Set value of Capital
	 * @param context
	 * @param capital
	 */
	public final void setCapital(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String capital)
	{
		getMendixObject().setValue(context, MemberNames.Capital.toString(), capital);
	}

	/**
	 * @return value of Continent
	 */
	public final java.lang.String getContinent()
	{
		return getContinent(getContext());
	}

	/**
	 * @param context
	 * @return value of Continent
	 */
	public final java.lang.String getContinent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Continent.toString());
	}

	/**
	 * Set value of Continent
	 * @param continent
	 */
	public final void setContinent(java.lang.String continent)
	{
		setContinent(getContext(), continent);
	}

	/**
	 * Set value of Continent
	 * @param context
	 * @param continent
	 */
	public final void setContinent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String continent)
	{
		getMendixObject().setValue(context, MemberNames.Continent.toString(), continent);
	}

	/**
	 * @return value of DS
	 */
	public final java.lang.String getDS()
	{
		return getDS(getContext());
	}

	/**
	 * @param context
	 * @return value of DS
	 */
	public final java.lang.String getDS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DS.toString());
	}

	/**
	 * Set value of DS
	 * @param ds
	 */
	public final void setDS(java.lang.String ds)
	{
		setDS(getContext(), ds);
	}

	/**
	 * Set value of DS
	 * @param context
	 * @param ds
	 */
	public final void setDS(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ds)
	{
		getMendixObject().setValue(context, MemberNames.DS.toString(), ds);
	}

	/**
	 * @return value of Developed___Developing_Countries
	 */
	public final java.lang.String getDeveloped___Developing_Countries()
	{
		return getDeveloped___Developing_Countries(getContext());
	}

	/**
	 * @param context
	 * @return value of Developed___Developing_Countries
	 */
	public final java.lang.String getDeveloped___Developing_Countries(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Developed___Developing_Countries.toString());
	}

	/**
	 * Set value of Developed___Developing_Countries
	 * @param developed___developing_countries
	 */
	public final void setDeveloped___Developing_Countries(java.lang.String developed___developing_countries)
	{
		setDeveloped___Developing_Countries(getContext(), developed___developing_countries);
	}

	/**
	 * Set value of Developed___Developing_Countries
	 * @param context
	 * @param developed___developing_countries
	 */
	public final void setDeveloped___Developing_Countries(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String developed___developing_countries)
	{
		getMendixObject().setValue(context, MemberNames.Developed___Developing_Countries.toString(), developed___developing_countries);
	}

	/**
	 * @return value of Dial
	 */
	public final java.lang.String getDial()
	{
		return getDial(getContext());
	}

	/**
	 * @param context
	 * @return value of Dial
	 */
	public final java.lang.String getDial(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Dial.toString());
	}

	/**
	 * Set value of Dial
	 * @param dial
	 */
	public final void setDial(java.lang.String dial)
	{
		setDial(getContext(), dial);
	}

	/**
	 * Set value of Dial
	 * @param context
	 * @param dial
	 */
	public final void setDial(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dial)
	{
		getMendixObject().setValue(context, MemberNames.Dial.toString(), dial);
	}

	/**
	 * @return value of EDGAR
	 */
	public final java.lang.String getEDGAR()
	{
		return getEDGAR(getContext());
	}

	/**
	 * @param context
	 * @return value of EDGAR
	 */
	public final java.lang.String getEDGAR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EDGAR.toString());
	}

	/**
	 * Set value of EDGAR
	 * @param edgar
	 */
	public final void setEDGAR(java.lang.String edgar)
	{
		setEDGAR(getContext(), edgar);
	}

	/**
	 * Set value of EDGAR
	 * @param context
	 * @param edgar
	 */
	public final void setEDGAR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String edgar)
	{
		getMendixObject().setValue(context, MemberNames.EDGAR.toString(), edgar);
	}

	/**
	 * @return value of FIFA
	 */
	public final java.lang.String getFIFA()
	{
		return getFIFA(getContext());
	}

	/**
	 * @param context
	 * @return value of FIFA
	 */
	public final java.lang.String getFIFA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FIFA.toString());
	}

	/**
	 * Set value of FIFA
	 * @param fifa
	 */
	public final void setFIFA(java.lang.String fifa)
	{
		setFIFA(getContext(), fifa);
	}

	/**
	 * Set value of FIFA
	 * @param context
	 * @param fifa
	 */
	public final void setFIFA(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fifa)
	{
		getMendixObject().setValue(context, MemberNames.FIFA.toString(), fifa);
	}

	/**
	 * @return value of FIPS
	 */
	public final java.lang.String getFIPS()
	{
		return getFIPS(getContext());
	}

	/**
	 * @param context
	 * @return value of FIPS
	 */
	public final java.lang.String getFIPS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FIPS.toString());
	}

	/**
	 * Set value of FIPS
	 * @param fips
	 */
	public final void setFIPS(java.lang.String fips)
	{
		setFIPS(getContext(), fips);
	}

	/**
	 * Set value of FIPS
	 * @param context
	 * @param fips
	 */
	public final void setFIPS(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fips)
	{
		getMendixObject().setValue(context, MemberNames.FIPS.toString(), fips);
	}

	/**
	 * @return value of GAUL
	 */
	public final java.lang.String getGAUL()
	{
		return getGAUL(getContext());
	}

	/**
	 * @param context
	 * @return value of GAUL
	 */
	public final java.lang.String getGAUL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GAUL.toString());
	}

	/**
	 * Set value of GAUL
	 * @param gaul
	 */
	public final void setGAUL(java.lang.String gaul)
	{
		setGAUL(getContext(), gaul);
	}

	/**
	 * Set value of GAUL
	 * @param context
	 * @param gaul
	 */
	public final void setGAUL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gaul)
	{
		getMendixObject().setValue(context, MemberNames.GAUL.toString(), gaul);
	}

	/**
	 * @return value of Geoname_ID
	 */
	public final java.math.BigDecimal getGeoname_ID()
	{
		return getGeoname_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of Geoname_ID
	 */
	public final java.math.BigDecimal getGeoname_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Geoname_ID.toString());
	}

	/**
	 * Set value of Geoname_ID
	 * @param geoname_id
	 */
	public final void setGeoname_ID(java.math.BigDecimal geoname_id)
	{
		setGeoname_ID(getContext(), geoname_id);
	}

	/**
	 * Set value of Geoname_ID
	 * @param context
	 * @param geoname_id
	 */
	public final void setGeoname_ID(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal geoname_id)
	{
		getMendixObject().setValue(context, MemberNames.Geoname_ID.toString(), geoname_id);
	}

	/**
	 * @return value of Global_Code
	 */
	public final java.lang.String getGlobal_Code()
	{
		return getGlobal_Code(getContext());
	}

	/**
	 * @param context
	 * @return value of Global_Code
	 */
	public final java.lang.String getGlobal_Code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Global_Code.toString());
	}

	/**
	 * Set value of Global_Code
	 * @param global_code
	 */
	public final void setGlobal_Code(java.lang.String global_code)
	{
		setGlobal_Code(getContext(), global_code);
	}

	/**
	 * Set value of Global_Code
	 * @param context
	 * @param global_code
	 */
	public final void setGlobal_Code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String global_code)
	{
		getMendixObject().setValue(context, MemberNames.Global_Code.toString(), global_code);
	}

	/**
	 * @return value of Global_Name
	 */
	public final java.lang.String getGlobal_Name()
	{
		return getGlobal_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Global_Name
	 */
	public final java.lang.String getGlobal_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Global_Name.toString());
	}

	/**
	 * Set value of Global_Name
	 * @param global_name
	 */
	public final void setGlobal_Name(java.lang.String global_name)
	{
		setGlobal_Name(getContext(), global_name);
	}

	/**
	 * Set value of Global_Name
	 * @param context
	 * @param global_name
	 */
	public final void setGlobal_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String global_name)
	{
		getMendixObject().setValue(context, MemberNames.Global_Name.toString(), global_name);
	}

	/**
	 * @return value of IOC
	 */
	public final java.lang.String getIOC()
	{
		return getIOC(getContext());
	}

	/**
	 * @param context
	 * @return value of IOC
	 */
	public final java.lang.String getIOC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IOC.toString());
	}

	/**
	 * Set value of IOC
	 * @param ioc
	 */
	public final void setIOC(java.lang.String ioc)
	{
		setIOC(getContext(), ioc);
	}

	/**
	 * Set value of IOC
	 * @param context
	 * @param ioc
	 */
	public final void setIOC(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ioc)
	{
		getMendixObject().setValue(context, MemberNames.IOC.toString(), ioc);
	}

	/**
	 * @return value of ISO3166_1_Alpha_2
	 */
	public final java.lang.String getISO3166_1_Alpha_2()
	{
		return getISO3166_1_Alpha_2(getContext());
	}

	/**
	 * @param context
	 * @return value of ISO3166_1_Alpha_2
	 */
	public final java.lang.String getISO3166_1_Alpha_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ISO3166_1_Alpha_2.toString());
	}

	/**
	 * Set value of ISO3166_1_Alpha_2
	 * @param iso3166_1_alpha_2
	 */
	public final void setISO3166_1_Alpha_2(java.lang.String iso3166_1_alpha_2)
	{
		setISO3166_1_Alpha_2(getContext(), iso3166_1_alpha_2);
	}

	/**
	 * Set value of ISO3166_1_Alpha_2
	 * @param context
	 * @param iso3166_1_alpha_2
	 */
	public final void setISO3166_1_Alpha_2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iso3166_1_alpha_2)
	{
		getMendixObject().setValue(context, MemberNames.ISO3166_1_Alpha_2.toString(), iso3166_1_alpha_2);
	}

	/**
	 * @return value of ISO3166_1_Alpha_3
	 */
	public final java.lang.String getISO3166_1_Alpha_3()
	{
		return getISO3166_1_Alpha_3(getContext());
	}

	/**
	 * @param context
	 * @return value of ISO3166_1_Alpha_3
	 */
	public final java.lang.String getISO3166_1_Alpha_3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ISO3166_1_Alpha_3.toString());
	}

	/**
	 * Set value of ISO3166_1_Alpha_3
	 * @param iso3166_1_alpha_3
	 */
	public final void setISO3166_1_Alpha_3(java.lang.String iso3166_1_alpha_3)
	{
		setISO3166_1_Alpha_3(getContext(), iso3166_1_alpha_3);
	}

	/**
	 * Set value of ISO3166_1_Alpha_3
	 * @param context
	 * @param iso3166_1_alpha_3
	 */
	public final void setISO3166_1_Alpha_3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iso3166_1_alpha_3)
	{
		getMendixObject().setValue(context, MemberNames.ISO3166_1_Alpha_3.toString(), iso3166_1_alpha_3);
	}

	/**
	 * @return value of ISO3166_1_numeric
	 */
	public final java.lang.String getISO3166_1_numeric()
	{
		return getISO3166_1_numeric(getContext());
	}

	/**
	 * @param context
	 * @return value of ISO3166_1_numeric
	 */
	public final java.lang.String getISO3166_1_numeric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ISO3166_1_numeric.toString());
	}

	/**
	 * Set value of ISO3166_1_numeric
	 * @param iso3166_1_numeric
	 */
	public final void setISO3166_1_numeric(java.lang.String iso3166_1_numeric)
	{
		setISO3166_1_numeric(getContext(), iso3166_1_numeric);
	}

	/**
	 * Set value of ISO3166_1_numeric
	 * @param context
	 * @param iso3166_1_numeric
	 */
	public final void setISO3166_1_numeric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iso3166_1_numeric)
	{
		getMendixObject().setValue(context, MemberNames.ISO3166_1_numeric.toString(), iso3166_1_numeric);
	}

	/**
	 * @return value of ISO4217_currency_alphabetic_code
	 */
	public final java.lang.String getISO4217_currency_alphabetic_code()
	{
		return getISO4217_currency_alphabetic_code(getContext());
	}

	/**
	 * @param context
	 * @return value of ISO4217_currency_alphabetic_code
	 */
	public final java.lang.String getISO4217_currency_alphabetic_code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ISO4217_currency_alphabetic_code.toString());
	}

	/**
	 * Set value of ISO4217_currency_alphabetic_code
	 * @param iso4217_currency_alphabetic_code
	 */
	public final void setISO4217_currency_alphabetic_code(java.lang.String iso4217_currency_alphabetic_code)
	{
		setISO4217_currency_alphabetic_code(getContext(), iso4217_currency_alphabetic_code);
	}

	/**
	 * Set value of ISO4217_currency_alphabetic_code
	 * @param context
	 * @param iso4217_currency_alphabetic_code
	 */
	public final void setISO4217_currency_alphabetic_code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iso4217_currency_alphabetic_code)
	{
		getMendixObject().setValue(context, MemberNames.ISO4217_currency_alphabetic_code.toString(), iso4217_currency_alphabetic_code);
	}

	/**
	 * @return value of ISO4217_currency_country_name
	 */
	public final java.lang.String getISO4217_currency_country_name()
	{
		return getISO4217_currency_country_name(getContext());
	}

	/**
	 * @param context
	 * @return value of ISO4217_currency_country_name
	 */
	public final java.lang.String getISO4217_currency_country_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ISO4217_currency_country_name.toString());
	}

	/**
	 * Set value of ISO4217_currency_country_name
	 * @param iso4217_currency_country_name
	 */
	public final void setISO4217_currency_country_name(java.lang.String iso4217_currency_country_name)
	{
		setISO4217_currency_country_name(getContext(), iso4217_currency_country_name);
	}

	/**
	 * Set value of ISO4217_currency_country_name
	 * @param context
	 * @param iso4217_currency_country_name
	 */
	public final void setISO4217_currency_country_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iso4217_currency_country_name)
	{
		getMendixObject().setValue(context, MemberNames.ISO4217_currency_country_name.toString(), iso4217_currency_country_name);
	}

	/**
	 * @return value of ISO4217_currency_minor_unit
	 */
	public final java.lang.String getISO4217_currency_minor_unit()
	{
		return getISO4217_currency_minor_unit(getContext());
	}

	/**
	 * @param context
	 * @return value of ISO4217_currency_minor_unit
	 */
	public final java.lang.String getISO4217_currency_minor_unit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ISO4217_currency_minor_unit.toString());
	}

	/**
	 * Set value of ISO4217_currency_minor_unit
	 * @param iso4217_currency_minor_unit
	 */
	public final void setISO4217_currency_minor_unit(java.lang.String iso4217_currency_minor_unit)
	{
		setISO4217_currency_minor_unit(getContext(), iso4217_currency_minor_unit);
	}

	/**
	 * Set value of ISO4217_currency_minor_unit
	 * @param context
	 * @param iso4217_currency_minor_unit
	 */
	public final void setISO4217_currency_minor_unit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iso4217_currency_minor_unit)
	{
		getMendixObject().setValue(context, MemberNames.ISO4217_currency_minor_unit.toString(), iso4217_currency_minor_unit);
	}

	/**
	 * @return value of ISO4217_currency_name
	 */
	public final java.lang.String getISO4217_currency_name()
	{
		return getISO4217_currency_name(getContext());
	}

	/**
	 * @param context
	 * @return value of ISO4217_currency_name
	 */
	public final java.lang.String getISO4217_currency_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ISO4217_currency_name.toString());
	}

	/**
	 * Set value of ISO4217_currency_name
	 * @param iso4217_currency_name
	 */
	public final void setISO4217_currency_name(java.lang.String iso4217_currency_name)
	{
		setISO4217_currency_name(getContext(), iso4217_currency_name);
	}

	/**
	 * Set value of ISO4217_currency_name
	 * @param context
	 * @param iso4217_currency_name
	 */
	public final void setISO4217_currency_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iso4217_currency_name)
	{
		getMendixObject().setValue(context, MemberNames.ISO4217_currency_name.toString(), iso4217_currency_name);
	}

	/**
	 * @return value of ISO4217_currency_numeric_code
	 */
	public final java.lang.String getISO4217_currency_numeric_code()
	{
		return getISO4217_currency_numeric_code(getContext());
	}

	/**
	 * @param context
	 * @return value of ISO4217_currency_numeric_code
	 */
	public final java.lang.String getISO4217_currency_numeric_code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ISO4217_currency_numeric_code.toString());
	}

	/**
	 * Set value of ISO4217_currency_numeric_code
	 * @param iso4217_currency_numeric_code
	 */
	public final void setISO4217_currency_numeric_code(java.lang.String iso4217_currency_numeric_code)
	{
		setISO4217_currency_numeric_code(getContext(), iso4217_currency_numeric_code);
	}

	/**
	 * Set value of ISO4217_currency_numeric_code
	 * @param context
	 * @param iso4217_currency_numeric_code
	 */
	public final void setISO4217_currency_numeric_code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iso4217_currency_numeric_code)
	{
		getMendixObject().setValue(context, MemberNames.ISO4217_currency_numeric_code.toString(), iso4217_currency_numeric_code);
	}

	/**
	 * @return value of ITU
	 */
	public final java.lang.String getITU()
	{
		return getITU(getContext());
	}

	/**
	 * @param context
	 * @return value of ITU
	 */
	public final java.lang.String getITU(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ITU.toString());
	}

	/**
	 * Set value of ITU
	 * @param itu
	 */
	public final void setITU(java.lang.String itu)
	{
		setITU(getContext(), itu);
	}

	/**
	 * Set value of ITU
	 * @param context
	 * @param itu
	 */
	public final void setITU(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String itu)
	{
		getMendixObject().setValue(context, MemberNames.ITU.toString(), itu);
	}

	/**
	 * @return value of Land_Locked_Developing_Countries__LLDC_
	 */
	public final java.lang.Boolean getLand_Locked_Developing_Countries__LLDC_()
	{
		return getLand_Locked_Developing_Countries__LLDC_(getContext());
	}

	/**
	 * @param context
	 * @return value of Land_Locked_Developing_Countries__LLDC_
	 */
	public final java.lang.Boolean getLand_Locked_Developing_Countries__LLDC_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Land_Locked_Developing_Countries__LLDC_.toString());
	}

	/**
	 * Set value of Land_Locked_Developing_Countries__LLDC_
	 * @param land_locked_developing_countries__lldc_
	 */
	public final void setLand_Locked_Developing_Countries__LLDC_(java.lang.Boolean land_locked_developing_countries__lldc_)
	{
		setLand_Locked_Developing_Countries__LLDC_(getContext(), land_locked_developing_countries__lldc_);
	}

	/**
	 * Set value of Land_Locked_Developing_Countries__LLDC_
	 * @param context
	 * @param land_locked_developing_countries__lldc_
	 */
	public final void setLand_Locked_Developing_Countries__LLDC_(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean land_locked_developing_countries__lldc_)
	{
		getMendixObject().setValue(context, MemberNames.Land_Locked_Developing_Countries__LLDC_.toString(), land_locked_developing_countries__lldc_);
	}

	/**
	 * @return value of Languages
	 */
	public final java.lang.String getLanguages()
	{
		return getLanguages(getContext());
	}

	/**
	 * @param context
	 * @return value of Languages
	 */
	public final java.lang.String getLanguages(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Languages.toString());
	}

	/**
	 * Set value of Languages
	 * @param languages
	 */
	public final void setLanguages(java.lang.String languages)
	{
		setLanguages(getContext(), languages);
	}

	/**
	 * Set value of Languages
	 * @param context
	 * @param languages
	 */
	public final void setLanguages(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String languages)
	{
		getMendixObject().setValue(context, MemberNames.Languages.toString(), languages);
	}

	/**
	 * @return value of Least_Developed_Countries__LDC_
	 */
	public final java.lang.Boolean getLeast_Developed_Countries__LDC_()
	{
		return getLeast_Developed_Countries__LDC_(getContext());
	}

	/**
	 * @param context
	 * @return value of Least_Developed_Countries__LDC_
	 */
	public final java.lang.Boolean getLeast_Developed_Countries__LDC_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Least_Developed_Countries__LDC_.toString());
	}

	/**
	 * Set value of Least_Developed_Countries__LDC_
	 * @param least_developed_countries__ldc_
	 */
	public final void setLeast_Developed_Countries__LDC_(java.lang.Boolean least_developed_countries__ldc_)
	{
		setLeast_Developed_Countries__LDC_(getContext(), least_developed_countries__ldc_);
	}

	/**
	 * Set value of Least_Developed_Countries__LDC_
	 * @param context
	 * @param least_developed_countries__ldc_
	 */
	public final void setLeast_Developed_Countries__LDC_(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean least_developed_countries__ldc_)
	{
		getMendixObject().setValue(context, MemberNames.Least_Developed_Countries__LDC_.toString(), least_developed_countries__ldc_);
	}

	/**
	 * @return value of M49
	 */
	public final java.math.BigDecimal getM49()
	{
		return getM49(getContext());
	}

	/**
	 * @param context
	 * @return value of M49
	 */
	public final java.math.BigDecimal getM49(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.M49.toString());
	}

	/**
	 * Set value of M49
	 * @param m49
	 */
	public final void setM49(java.math.BigDecimal m49)
	{
		setM49(getContext(), m49);
	}

	/**
	 * Set value of M49
	 * @param context
	 * @param m49
	 */
	public final void setM49(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal m49)
	{
		getMendixObject().setValue(context, MemberNames.M49.toString(), m49);
	}

	/**
	 * @return value of MARC
	 */
	public final java.lang.String getMARC()
	{
		return getMARC(getContext());
	}

	/**
	 * @param context
	 * @return value of MARC
	 */
	public final java.lang.String getMARC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MARC.toString());
	}

	/**
	 * Set value of MARC
	 * @param marc
	 */
	public final void setMARC(java.lang.String marc)
	{
		setMARC(getContext(), marc);
	}

	/**
	 * Set value of MARC
	 * @param context
	 * @param marc
	 */
	public final void setMARC(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String marc)
	{
		getMendixObject().setValue(context, MemberNames.MARC.toString(), marc);
	}

	/**
	 * @return value of Region_Code
	 */
	public final java.lang.String getRegion_Code()
	{
		return getRegion_Code(getContext());
	}

	/**
	 * @param context
	 * @return value of Region_Code
	 */
	public final java.lang.String getRegion_Code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Region_Code.toString());
	}

	/**
	 * Set value of Region_Code
	 * @param region_code
	 */
	public final void setRegion_Code(java.lang.String region_code)
	{
		setRegion_Code(getContext(), region_code);
	}

	/**
	 * Set value of Region_Code
	 * @param context
	 * @param region_code
	 */
	public final void setRegion_Code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String region_code)
	{
		getMendixObject().setValue(context, MemberNames.Region_Code.toString(), region_code);
	}

	/**
	 * @return value of Region_Name
	 */
	public final java.lang.String getRegion_Name()
	{
		return getRegion_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Region_Name
	 */
	public final java.lang.String getRegion_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Region_Name.toString());
	}

	/**
	 * Set value of Region_Name
	 * @param region_name
	 */
	public final void setRegion_Name(java.lang.String region_name)
	{
		setRegion_Name(getContext(), region_name);
	}

	/**
	 * Set value of Region_Name
	 * @param context
	 * @param region_name
	 */
	public final void setRegion_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String region_name)
	{
		getMendixObject().setValue(context, MemberNames.Region_Name.toString(), region_name);
	}

	/**
	 * @return value of Sub_region_Code
	 */
	public final java.lang.String getSub_region_Code()
	{
		return getSub_region_Code(getContext());
	}

	/**
	 * @param context
	 * @return value of Sub_region_Code
	 */
	public final java.lang.String getSub_region_Code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sub_region_Code.toString());
	}

	/**
	 * Set value of Sub_region_Code
	 * @param sub_region_code
	 */
	public final void setSub_region_Code(java.lang.String sub_region_code)
	{
		setSub_region_Code(getContext(), sub_region_code);
	}

	/**
	 * Set value of Sub_region_Code
	 * @param context
	 * @param sub_region_code
	 */
	public final void setSub_region_Code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sub_region_code)
	{
		getMendixObject().setValue(context, MemberNames.Sub_region_Code.toString(), sub_region_code);
	}

	/**
	 * @return value of Sub_region_Name
	 */
	public final java.lang.String getSub_region_Name()
	{
		return getSub_region_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Sub_region_Name
	 */
	public final java.lang.String getSub_region_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sub_region_Name.toString());
	}

	/**
	 * Set value of Sub_region_Name
	 * @param sub_region_name
	 */
	public final void setSub_region_Name(java.lang.String sub_region_name)
	{
		setSub_region_Name(getContext(), sub_region_name);
	}

	/**
	 * Set value of Sub_region_Name
	 * @param context
	 * @param sub_region_name
	 */
	public final void setSub_region_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sub_region_name)
	{
		getMendixObject().setValue(context, MemberNames.Sub_region_Name.toString(), sub_region_name);
	}

	/**
	 * @return value of TLD
	 */
	public final java.lang.String getTLD()
	{
		return getTLD(getContext());
	}

	/**
	 * @param context
	 * @return value of TLD
	 */
	public final java.lang.String getTLD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TLD.toString());
	}

	/**
	 * Set value of TLD
	 * @param tld
	 */
	public final void setTLD(java.lang.String tld)
	{
		setTLD(getContext(), tld);
	}

	/**
	 * Set value of TLD
	 * @param context
	 * @param tld
	 */
	public final void setTLD(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tld)
	{
		getMendixObject().setValue(context, MemberNames.TLD.toString(), tld);
	}

	/**
	 * @return value of UNTERM_Arabic_Formal
	 */
	public final java.lang.String getUNTERM_Arabic_Formal()
	{
		return getUNTERM_Arabic_Formal(getContext());
	}

	/**
	 * @param context
	 * @return value of UNTERM_Arabic_Formal
	 */
	public final java.lang.String getUNTERM_Arabic_Formal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UNTERM_Arabic_Formal.toString());
	}

	/**
	 * Set value of UNTERM_Arabic_Formal
	 * @param unterm_arabic_formal
	 */
	public final void setUNTERM_Arabic_Formal(java.lang.String unterm_arabic_formal)
	{
		setUNTERM_Arabic_Formal(getContext(), unterm_arabic_formal);
	}

	/**
	 * Set value of UNTERM_Arabic_Formal
	 * @param context
	 * @param unterm_arabic_formal
	 */
	public final void setUNTERM_Arabic_Formal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unterm_arabic_formal)
	{
		getMendixObject().setValue(context, MemberNames.UNTERM_Arabic_Formal.toString(), unterm_arabic_formal);
	}

	/**
	 * @return value of UNTERM_Arabic_Short
	 */
	public final java.lang.String getUNTERM_Arabic_Short()
	{
		return getUNTERM_Arabic_Short(getContext());
	}

	/**
	 * @param context
	 * @return value of UNTERM_Arabic_Short
	 */
	public final java.lang.String getUNTERM_Arabic_Short(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UNTERM_Arabic_Short.toString());
	}

	/**
	 * Set value of UNTERM_Arabic_Short
	 * @param unterm_arabic_short
	 */
	public final void setUNTERM_Arabic_Short(java.lang.String unterm_arabic_short)
	{
		setUNTERM_Arabic_Short(getContext(), unterm_arabic_short);
	}

	/**
	 * Set value of UNTERM_Arabic_Short
	 * @param context
	 * @param unterm_arabic_short
	 */
	public final void setUNTERM_Arabic_Short(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unterm_arabic_short)
	{
		getMendixObject().setValue(context, MemberNames.UNTERM_Arabic_Short.toString(), unterm_arabic_short);
	}

	/**
	 * @return value of UNTERM_Chinese_Formal
	 */
	public final java.lang.String getUNTERM_Chinese_Formal()
	{
		return getUNTERM_Chinese_Formal(getContext());
	}

	/**
	 * @param context
	 * @return value of UNTERM_Chinese_Formal
	 */
	public final java.lang.String getUNTERM_Chinese_Formal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UNTERM_Chinese_Formal.toString());
	}

	/**
	 * Set value of UNTERM_Chinese_Formal
	 * @param unterm_chinese_formal
	 */
	public final void setUNTERM_Chinese_Formal(java.lang.String unterm_chinese_formal)
	{
		setUNTERM_Chinese_Formal(getContext(), unterm_chinese_formal);
	}

	/**
	 * Set value of UNTERM_Chinese_Formal
	 * @param context
	 * @param unterm_chinese_formal
	 */
	public final void setUNTERM_Chinese_Formal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unterm_chinese_formal)
	{
		getMendixObject().setValue(context, MemberNames.UNTERM_Chinese_Formal.toString(), unterm_chinese_formal);
	}

	/**
	 * @return value of UNTERM_Chinese_Short
	 */
	public final java.lang.String getUNTERM_Chinese_Short()
	{
		return getUNTERM_Chinese_Short(getContext());
	}

	/**
	 * @param context
	 * @return value of UNTERM_Chinese_Short
	 */
	public final java.lang.String getUNTERM_Chinese_Short(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UNTERM_Chinese_Short.toString());
	}

	/**
	 * Set value of UNTERM_Chinese_Short
	 * @param unterm_chinese_short
	 */
	public final void setUNTERM_Chinese_Short(java.lang.String unterm_chinese_short)
	{
		setUNTERM_Chinese_Short(getContext(), unterm_chinese_short);
	}

	/**
	 * Set value of UNTERM_Chinese_Short
	 * @param context
	 * @param unterm_chinese_short
	 */
	public final void setUNTERM_Chinese_Short(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unterm_chinese_short)
	{
		getMendixObject().setValue(context, MemberNames.UNTERM_Chinese_Short.toString(), unterm_chinese_short);
	}

	/**
	 * @return value of UNTERM_English_Formal
	 */
	public final java.lang.String getUNTERM_English_Formal()
	{
		return getUNTERM_English_Formal(getContext());
	}

	/**
	 * @param context
	 * @return value of UNTERM_English_Formal
	 */
	public final java.lang.String getUNTERM_English_Formal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UNTERM_English_Formal.toString());
	}

	/**
	 * Set value of UNTERM_English_Formal
	 * @param unterm_english_formal
	 */
	public final void setUNTERM_English_Formal(java.lang.String unterm_english_formal)
	{
		setUNTERM_English_Formal(getContext(), unterm_english_formal);
	}

	/**
	 * Set value of UNTERM_English_Formal
	 * @param context
	 * @param unterm_english_formal
	 */
	public final void setUNTERM_English_Formal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unterm_english_formal)
	{
		getMendixObject().setValue(context, MemberNames.UNTERM_English_Formal.toString(), unterm_english_formal);
	}

	/**
	 * @return value of UNTERM_English_Short
	 */
	public final java.lang.String getUNTERM_English_Short()
	{
		return getUNTERM_English_Short(getContext());
	}

	/**
	 * @param context
	 * @return value of UNTERM_English_Short
	 */
	public final java.lang.String getUNTERM_English_Short(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UNTERM_English_Short.toString());
	}

	/**
	 * Set value of UNTERM_English_Short
	 * @param unterm_english_short
	 */
	public final void setUNTERM_English_Short(java.lang.String unterm_english_short)
	{
		setUNTERM_English_Short(getContext(), unterm_english_short);
	}

	/**
	 * Set value of UNTERM_English_Short
	 * @param context
	 * @param unterm_english_short
	 */
	public final void setUNTERM_English_Short(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unterm_english_short)
	{
		getMendixObject().setValue(context, MemberNames.UNTERM_English_Short.toString(), unterm_english_short);
	}

	/**
	 * @return value of UNTERM_French_Formal
	 */
	public final java.lang.String getUNTERM_French_Formal()
	{
		return getUNTERM_French_Formal(getContext());
	}

	/**
	 * @param context
	 * @return value of UNTERM_French_Formal
	 */
	public final java.lang.String getUNTERM_French_Formal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UNTERM_French_Formal.toString());
	}

	/**
	 * Set value of UNTERM_French_Formal
	 * @param unterm_french_formal
	 */
	public final void setUNTERM_French_Formal(java.lang.String unterm_french_formal)
	{
		setUNTERM_French_Formal(getContext(), unterm_french_formal);
	}

	/**
	 * Set value of UNTERM_French_Formal
	 * @param context
	 * @param unterm_french_formal
	 */
	public final void setUNTERM_French_Formal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unterm_french_formal)
	{
		getMendixObject().setValue(context, MemberNames.UNTERM_French_Formal.toString(), unterm_french_formal);
	}

	/**
	 * @return value of UNTERM_French_Short
	 */
	public final java.lang.String getUNTERM_French_Short()
	{
		return getUNTERM_French_Short(getContext());
	}

	/**
	 * @param context
	 * @return value of UNTERM_French_Short
	 */
	public final java.lang.String getUNTERM_French_Short(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UNTERM_French_Short.toString());
	}

	/**
	 * Set value of UNTERM_French_Short
	 * @param unterm_french_short
	 */
	public final void setUNTERM_French_Short(java.lang.String unterm_french_short)
	{
		setUNTERM_French_Short(getContext(), unterm_french_short);
	}

	/**
	 * Set value of UNTERM_French_Short
	 * @param context
	 * @param unterm_french_short
	 */
	public final void setUNTERM_French_Short(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unterm_french_short)
	{
		getMendixObject().setValue(context, MemberNames.UNTERM_French_Short.toString(), unterm_french_short);
	}

	/**
	 * @return value of UNTERM_Russian_Formal
	 */
	public final java.lang.String getUNTERM_Russian_Formal()
	{
		return getUNTERM_Russian_Formal(getContext());
	}

	/**
	 * @param context
	 * @return value of UNTERM_Russian_Formal
	 */
	public final java.lang.String getUNTERM_Russian_Formal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UNTERM_Russian_Formal.toString());
	}

	/**
	 * Set value of UNTERM_Russian_Formal
	 * @param unterm_russian_formal
	 */
	public final void setUNTERM_Russian_Formal(java.lang.String unterm_russian_formal)
	{
		setUNTERM_Russian_Formal(getContext(), unterm_russian_formal);
	}

	/**
	 * Set value of UNTERM_Russian_Formal
	 * @param context
	 * @param unterm_russian_formal
	 */
	public final void setUNTERM_Russian_Formal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unterm_russian_formal)
	{
		getMendixObject().setValue(context, MemberNames.UNTERM_Russian_Formal.toString(), unterm_russian_formal);
	}

	/**
	 * @return value of UNTERM_Russian_Short
	 */
	public final java.lang.String getUNTERM_Russian_Short()
	{
		return getUNTERM_Russian_Short(getContext());
	}

	/**
	 * @param context
	 * @return value of UNTERM_Russian_Short
	 */
	public final java.lang.String getUNTERM_Russian_Short(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UNTERM_Russian_Short.toString());
	}

	/**
	 * Set value of UNTERM_Russian_Short
	 * @param unterm_russian_short
	 */
	public final void setUNTERM_Russian_Short(java.lang.String unterm_russian_short)
	{
		setUNTERM_Russian_Short(getContext(), unterm_russian_short);
	}

	/**
	 * Set value of UNTERM_Russian_Short
	 * @param context
	 * @param unterm_russian_short
	 */
	public final void setUNTERM_Russian_Short(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unterm_russian_short)
	{
		getMendixObject().setValue(context, MemberNames.UNTERM_Russian_Short.toString(), unterm_russian_short);
	}

	/**
	 * @return value of UNTERM_Spanish_Formal
	 */
	public final java.lang.String getUNTERM_Spanish_Formal()
	{
		return getUNTERM_Spanish_Formal(getContext());
	}

	/**
	 * @param context
	 * @return value of UNTERM_Spanish_Formal
	 */
	public final java.lang.String getUNTERM_Spanish_Formal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UNTERM_Spanish_Formal.toString());
	}

	/**
	 * Set value of UNTERM_Spanish_Formal
	 * @param unterm_spanish_formal
	 */
	public final void setUNTERM_Spanish_Formal(java.lang.String unterm_spanish_formal)
	{
		setUNTERM_Spanish_Formal(getContext(), unterm_spanish_formal);
	}

	/**
	 * Set value of UNTERM_Spanish_Formal
	 * @param context
	 * @param unterm_spanish_formal
	 */
	public final void setUNTERM_Spanish_Formal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unterm_spanish_formal)
	{
		getMendixObject().setValue(context, MemberNames.UNTERM_Spanish_Formal.toString(), unterm_spanish_formal);
	}

	/**
	 * @return value of UNTERM_Spanish_Short
	 */
	public final java.lang.String getUNTERM_Spanish_Short()
	{
		return getUNTERM_Spanish_Short(getContext());
	}

	/**
	 * @param context
	 * @return value of UNTERM_Spanish_Short
	 */
	public final java.lang.String getUNTERM_Spanish_Short(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UNTERM_Spanish_Short.toString());
	}

	/**
	 * Set value of UNTERM_Spanish_Short
	 * @param unterm_spanish_short
	 */
	public final void setUNTERM_Spanish_Short(java.lang.String unterm_spanish_short)
	{
		setUNTERM_Spanish_Short(getContext(), unterm_spanish_short);
	}

	/**
	 * Set value of UNTERM_Spanish_Short
	 * @param context
	 * @param unterm_spanish_short
	 */
	public final void setUNTERM_Spanish_Short(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unterm_spanish_short)
	{
		getMendixObject().setValue(context, MemberNames.UNTERM_Spanish_Short.toString(), unterm_spanish_short);
	}

	/**
	 * @return value of WMO
	 */
	public final java.lang.String getWMO()
	{
		return getWMO(getContext());
	}

	/**
	 * @param context
	 * @return value of WMO
	 */
	public final java.lang.String getWMO(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WMO.toString());
	}

	/**
	 * Set value of WMO
	 * @param wmo
	 */
	public final void setWMO(java.lang.String wmo)
	{
		setWMO(getContext(), wmo);
	}

	/**
	 * Set value of WMO
	 * @param context
	 * @param wmo
	 */
	public final void setWMO(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wmo)
	{
		getMendixObject().setValue(context, MemberNames.WMO.toString(), wmo);
	}

	/**
	 * @return value of Is_independent
	 */
	public final java.lang.Boolean getIs_independent()
	{
		return getIs_independent(getContext());
	}

	/**
	 * @param context
	 * @return value of Is_independent
	 */
	public final java.lang.Boolean getIs_independent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Is_independent.toString());
	}

	/**
	 * Set value of Is_independent
	 * @param is_independent
	 */
	public final void setIs_independent(java.lang.Boolean is_independent)
	{
		setIs_independent(getContext(), is_independent);
	}

	/**
	 * Set value of Is_independent
	 * @param context
	 * @param is_independent
	 */
	public final void setIs_independent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean is_independent)
	{
		getMendixObject().setValue(context, MemberNames.Is_independent.toString(), is_independent);
	}

	/**
	 * @return value of Official_name_ar
	 */
	public final java.lang.String getOfficial_name_ar()
	{
		return getOfficial_name_ar(getContext());
	}

	/**
	 * @param context
	 * @return value of Official_name_ar
	 */
	public final java.lang.String getOfficial_name_ar(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Official_name_ar.toString());
	}

	/**
	 * Set value of Official_name_ar
	 * @param official_name_ar
	 */
	public final void setOfficial_name_ar(java.lang.String official_name_ar)
	{
		setOfficial_name_ar(getContext(), official_name_ar);
	}

	/**
	 * Set value of Official_name_ar
	 * @param context
	 * @param official_name_ar
	 */
	public final void setOfficial_name_ar(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String official_name_ar)
	{
		getMendixObject().setValue(context, MemberNames.Official_name_ar.toString(), official_name_ar);
	}

	/**
	 * @return value of Official_name_cn
	 */
	public final java.lang.String getOfficial_name_cn()
	{
		return getOfficial_name_cn(getContext());
	}

	/**
	 * @param context
	 * @return value of Official_name_cn
	 */
	public final java.lang.String getOfficial_name_cn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Official_name_cn.toString());
	}

	/**
	 * Set value of Official_name_cn
	 * @param official_name_cn
	 */
	public final void setOfficial_name_cn(java.lang.String official_name_cn)
	{
		setOfficial_name_cn(getContext(), official_name_cn);
	}

	/**
	 * Set value of Official_name_cn
	 * @param context
	 * @param official_name_cn
	 */
	public final void setOfficial_name_cn(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String official_name_cn)
	{
		getMendixObject().setValue(context, MemberNames.Official_name_cn.toString(), official_name_cn);
	}

	/**
	 * @return value of Official_name_en
	 */
	public final java.lang.String getOfficial_name_en()
	{
		return getOfficial_name_en(getContext());
	}

	/**
	 * @param context
	 * @return value of Official_name_en
	 */
	public final java.lang.String getOfficial_name_en(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Official_name_en.toString());
	}

	/**
	 * Set value of Official_name_en
	 * @param official_name_en
	 */
	public final void setOfficial_name_en(java.lang.String official_name_en)
	{
		setOfficial_name_en(getContext(), official_name_en);
	}

	/**
	 * Set value of Official_name_en
	 * @param context
	 * @param official_name_en
	 */
	public final void setOfficial_name_en(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String official_name_en)
	{
		getMendixObject().setValue(context, MemberNames.Official_name_en.toString(), official_name_en);
	}

	/**
	 * @return value of Official_name_es
	 */
	public final java.lang.String getOfficial_name_es()
	{
		return getOfficial_name_es(getContext());
	}

	/**
	 * @param context
	 * @return value of Official_name_es
	 */
	public final java.lang.String getOfficial_name_es(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Official_name_es.toString());
	}

	/**
	 * Set value of Official_name_es
	 * @param official_name_es
	 */
	public final void setOfficial_name_es(java.lang.String official_name_es)
	{
		setOfficial_name_es(getContext(), official_name_es);
	}

	/**
	 * Set value of Official_name_es
	 * @param context
	 * @param official_name_es
	 */
	public final void setOfficial_name_es(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String official_name_es)
	{
		getMendixObject().setValue(context, MemberNames.Official_name_es.toString(), official_name_es);
	}

	/**
	 * @return value of Official_name_fr
	 */
	public final java.lang.String getOfficial_name_fr()
	{
		return getOfficial_name_fr(getContext());
	}

	/**
	 * @param context
	 * @return value of Official_name_fr
	 */
	public final java.lang.String getOfficial_name_fr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Official_name_fr.toString());
	}

	/**
	 * Set value of Official_name_fr
	 * @param official_name_fr
	 */
	public final void setOfficial_name_fr(java.lang.String official_name_fr)
	{
		setOfficial_name_fr(getContext(), official_name_fr);
	}

	/**
	 * Set value of Official_name_fr
	 * @param context
	 * @param official_name_fr
	 */
	public final void setOfficial_name_fr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String official_name_fr)
	{
		getMendixObject().setValue(context, MemberNames.Official_name_fr.toString(), official_name_fr);
	}

	/**
	 * @return value of Official_name_ru
	 */
	public final java.lang.String getOfficial_name_ru()
	{
		return getOfficial_name_ru(getContext());
	}

	/**
	 * @param context
	 * @return value of Official_name_ru
	 */
	public final java.lang.String getOfficial_name_ru(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Official_name_ru.toString());
	}

	/**
	 * Set value of Official_name_ru
	 * @param official_name_ru
	 */
	public final void setOfficial_name_ru(java.lang.String official_name_ru)
	{
		setOfficial_name_ru(getContext(), official_name_ru);
	}

	/**
	 * Set value of Official_name_ru
	 * @param context
	 * @param official_name_ru
	 */
	public final void setOfficial_name_ru(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String official_name_ru)
	{
		getMendixObject().setValue(context, MemberNames.Official_name_ru.toString(), official_name_ru);
	}

	/**
	 * @return value of CountryFlag_CountryCode
	 */
	public final datahubio_countrycodes.proxies.CountryFlag getCountryFlag_CountryCode() throws com.mendix.core.CoreException
	{
		return getCountryFlag_CountryCode(getContext());
	}

	/**
	 * @param context
	 * @return value of CountryFlag_CountryCode
	 */
	public final datahubio_countrycodes.proxies.CountryFlag getCountryFlag_CountryCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		datahubio_countrycodes.proxies.CountryFlag result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CountryFlag_CountryCode.toString());
		if (identifier != null)
			result = datahubio_countrycodes.proxies.CountryFlag.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CountryFlag_CountryCode
	 * @param countryflag_countrycode
	 */
	public final void setCountryFlag_CountryCode(datahubio_countrycodes.proxies.CountryFlag countryflag_countrycode)
	{
		setCountryFlag_CountryCode(getContext(), countryflag_countrycode);
	}

	/**
	 * Set value of CountryFlag_CountryCode
	 * @param context
	 * @param countryflag_countrycode
	 */
	public final void setCountryFlag_CountryCode(com.mendix.systemwideinterfaces.core.IContext context, datahubio_countrycodes.proxies.CountryFlag countryflag_countrycode)
	{
		if (countryflag_countrycode == null)
			getMendixObject().setValue(context, MemberNames.CountryFlag_CountryCode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CountryFlag_CountryCode.toString(), countryflag_countrycode.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return countryCodeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final datahubio_countrycodes.proxies.CountryCode that = (datahubio_countrycodes.proxies.CountryCode) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DataHubIo_CountryCodes.CountryCode";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
