// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package barcode.proxies;

/**
 * entity which will contain the barcode image
 */
public class Barcode extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Barcode.Barcode";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BarcodeType("BarcodeType"),
		EAN("EAN"),
		showBarcodeText("showBarcodeText"),
		orientation("orientation"),
		heightMultiplier("heightMultiplier"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Barcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Barcode.Barcode"));
	}

	protected Barcode(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject barcodeMendixObject)
	{
		super(context, barcodeMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Barcode.Barcode", barcodeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Barcode.Barcode");
	}

	/**
	 * @deprecated Use 'Barcode.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static barcode.proxies.Barcode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return barcode.proxies.Barcode.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static barcode.proxies.Barcode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("BarcodePlayground.MyBarcode", mendixObject.getType()))
			return barcodeplayground.proxies.MyBarcode.initialize(context, mendixObject);

		return new barcode.proxies.Barcode(context, mendixObject);
	}

	public static barcode.proxies.Barcode load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return barcode.proxies.Barcode.initialize(context, mendixObject);
	}

	public static java.util.List<? extends barcode.proxies.Barcode> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<barcode.proxies.Barcode> result = new java.util.ArrayList<barcode.proxies.Barcode>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Barcode.Barcode" + xpathConstraint))
			result.add(barcode.proxies.Barcode.initialize(context, obj));
		return result;
	}

	/**
	 * Set value of BarcodeType
	 * @param barcodetype
	 */
	public final barcode.proxies.BarcodeType getBarcodeType()
	{
		return getBarcodeType(getContext());
	}

	/**
	 * @param context
	 * @return value of BarcodeType
	 */
	public final barcode.proxies.BarcodeType getBarcodeType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.BarcodeType.toString());
		if (obj == null)
			return null;

		return barcode.proxies.BarcodeType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of BarcodeType
	 * @param barcodetype
	 */
	public final void setBarcodeType(barcode.proxies.BarcodeType barcodetype)
	{
		setBarcodeType(getContext(), barcodetype);
	}

	/**
	 * Set value of BarcodeType
	 * @param context
	 * @param barcodetype
	 */
	public final void setBarcodeType(com.mendix.systemwideinterfaces.core.IContext context, barcode.proxies.BarcodeType barcodetype)
	{
		if (barcodetype != null)
			getMendixObject().setValue(context, MemberNames.BarcodeType.toString(), barcodetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.BarcodeType.toString(), null);
	}

	/**
	 * @return value of EAN
	 */
	public final java.lang.String getEAN()
	{
		return getEAN(getContext());
	}

	/**
	 * @param context
	 * @return value of EAN
	 */
	public final java.lang.String getEAN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EAN.toString());
	}

	/**
	 * Set value of EAN
	 * @param ean
	 */
	public final void setEAN(java.lang.String ean)
	{
		setEAN(getContext(), ean);
	}

	/**
	 * Set value of EAN
	 * @param context
	 * @param ean
	 */
	public final void setEAN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ean)
	{
		getMendixObject().setValue(context, MemberNames.EAN.toString(), ean);
	}

	/**
	 * @return value of showBarcodeText
	 */
	public final java.lang.Boolean getshowBarcodeText()
	{
		return getshowBarcodeText(getContext());
	}

	/**
	 * @param context
	 * @return value of showBarcodeText
	 */
	public final java.lang.Boolean getshowBarcodeText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.showBarcodeText.toString());
	}

	/**
	 * Set value of showBarcodeText
	 * @param showbarcodetext
	 */
	public final void setshowBarcodeText(java.lang.Boolean showbarcodetext)
	{
		setshowBarcodeText(getContext(), showbarcodetext);
	}

	/**
	 * Set value of showBarcodeText
	 * @param context
	 * @param showbarcodetext
	 */
	public final void setshowBarcodeText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showbarcodetext)
	{
		getMendixObject().setValue(context, MemberNames.showBarcodeText.toString(), showbarcodetext);
	}

	/**
	 * @return value of orientation
	 */
	public final java.lang.Integer getorientation()
	{
		return getorientation(getContext());
	}

	/**
	 * @param context
	 * @return value of orientation
	 */
	public final java.lang.Integer getorientation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.orientation.toString());
	}

	/**
	 * Set value of orientation
	 * @param orientation
	 */
	public final void setorientation(java.lang.Integer orientation)
	{
		setorientation(getContext(), orientation);
	}

	/**
	 * Set value of orientation
	 * @param context
	 * @param orientation
	 */
	public final void setorientation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer orientation)
	{
		getMendixObject().setValue(context, MemberNames.orientation.toString(), orientation);
	}

	/**
	 * @return value of heightMultiplier
	 */
	public final java.math.BigDecimal getheightMultiplier()
	{
		return getheightMultiplier(getContext());
	}

	/**
	 * @param context
	 * @return value of heightMultiplier
	 */
	public final java.math.BigDecimal getheightMultiplier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.heightMultiplier.toString());
	}

	/**
	 * Set value of heightMultiplier
	 * @param heightmultiplier
	 */
	public final void setheightMultiplier(java.math.BigDecimal heightmultiplier)
	{
		setheightMultiplier(getContext(), heightmultiplier);
	}

	/**
	 * Set value of heightMultiplier
	 * @param context
	 * @param heightmultiplier
	 */
	public final void setheightMultiplier(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal heightmultiplier)
	{
		getMendixObject().setValue(context, MemberNames.heightMultiplier.toString(), heightmultiplier);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final barcode.proxies.Barcode that = (barcode.proxies.Barcode) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Barcode.Barcode";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
