// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sprintrapis2.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the SprintrApis2 module
	public static void aCT_App_DownloadToLocalHTMLfile(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("SprintrApis2.ACT_App_DownloadToLocalHTMLfile").withParams(params).execute(context);
	}
	public static void oCh_App_UpdateLinks(IContext context, sprintrapis2.proxies.App _app)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("App", _app == null ? null : _app.getMendixObject());
		Core.microflowCall("SprintrApis2.OCh_App_UpdateLinks").withParams(params).execute(context);
	}
	public static void sub_App_GetMyApps(IContext context, sprintrapis2.proxies.MendixUser _mendixUser)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MendixUser", _mendixUser == null ? null : _mendixUser.getMendixObject());
		Core.microflowCall("SprintrApis2.Sub_App_GetMyApps").withParams(params).execute(context);
	}
	public static void sub_App_GetSprints(IContext context, sprintrapis2.proxies.MendixUser _mendixUser, sprintrapis2.proxies.App _mendixApp)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MendixUser", _mendixUser == null ? null : _mendixUser.getMendixObject());
		params.put("MendixApp", _mendixApp == null ? null : _mendixApp.getMendixObject());
		Core.microflowCall("SprintrApis2.Sub_App_GetSprints").withParams(params).execute(context);
	}
	public static void sUB_MendixApp_RemoveDuplicates(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("SprintrApis2.SUB_MendixApp_RemoveDuplicates").withParams(params).execute(context);
	}
	public static sprintrapis2.proxies.MendixUser sUB_Mendixuser_GetOrCreate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("SprintrApis2.SUB_Mendixuser_GetOrCreate").withParams(params).execute(context);
		return result == null ? null : sprintrapis2.proxies.MendixUser.initialize(context, result);
	}
}