// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package personswithsingleuseraccount.proxies;

/**
 * How to address someone. For instance when sending an email or letter.
 * Miss, Ms.
 * Misses, Mrs. or Ms.
 * Mister, Mr.
 */
public class AddressTitle
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject addressTitleMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PersonsWithSingleUserAccount.AddressTitle";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Abbreviation("Abbreviation"),
		Person_AddressTitle("PersonsWithSingleUserAccount.Person_AddressTitle");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AddressTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PersonsWithSingleUserAccount.AddressTitle"));
	}

	protected AddressTitle(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject addressTitleMendixObject)
	{
		if (addressTitleMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PersonsWithSingleUserAccount.AddressTitle", addressTitleMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PersonsWithSingleUserAccount.AddressTitle");

		this.addressTitleMendixObject = addressTitleMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AddressTitle.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static personswithsingleuseraccount.proxies.AddressTitle initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return personswithsingleuseraccount.proxies.AddressTitle.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static personswithsingleuseraccount.proxies.AddressTitle initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new personswithsingleuseraccount.proxies.AddressTitle(context, mendixObject);
	}

	public static personswithsingleuseraccount.proxies.AddressTitle load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return personswithsingleuseraccount.proxies.AddressTitle.initialize(context, mendixObject);
	}

	public static java.util.List<personswithsingleuseraccount.proxies.AddressTitle> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<personswithsingleuseraccount.proxies.AddressTitle> result = new java.util.ArrayList<personswithsingleuseraccount.proxies.AddressTitle>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PersonsWithSingleUserAccount.AddressTitle" + xpathConstraint))
			result.add(personswithsingleuseraccount.proxies.AddressTitle.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Abbreviation
	 */
	public final java.lang.String getAbbreviation()
	{
		return getAbbreviation(getContext());
	}

	/**
	 * @param context
	 * @return value of Abbreviation
	 */
	public final java.lang.String getAbbreviation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Abbreviation.toString());
	}

	/**
	 * Set value of Abbreviation
	 * @param abbreviation
	 */
	public final void setAbbreviation(java.lang.String abbreviation)
	{
		setAbbreviation(getContext(), abbreviation);
	}

	/**
	 * Set value of Abbreviation
	 * @param context
	 * @param abbreviation
	 */
	public final void setAbbreviation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String abbreviation)
	{
		getMendixObject().setValue(context, MemberNames.Abbreviation.toString(), abbreviation);
	}

	/**
	 * @return value of Person_AddressTitle
	 */
	public final personswithsingleuseraccount.proxies.Person getPerson_AddressTitle() throws com.mendix.core.CoreException
	{
		return getPerson_AddressTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_AddressTitle
	 */
	public final personswithsingleuseraccount.proxies.Person getPerson_AddressTitle(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		personswithsingleuseraccount.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_AddressTitle.toString());
		if (identifier != null)
			result = personswithsingleuseraccount.proxies.Person.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Person_AddressTitle
	 * @param person_addresstitle
	 */
	public final void setPerson_AddressTitle(personswithsingleuseraccount.proxies.Person person_addresstitle)
	{
		setPerson_AddressTitle(getContext(), person_addresstitle);
	}

	/**
	 * Set value of Person_AddressTitle
	 * @param context
	 * @param person_addresstitle
	 */
	public final void setPerson_AddressTitle(com.mendix.systemwideinterfaces.core.IContext context, personswithsingleuseraccount.proxies.Person person_addresstitle)
	{
		if (person_addresstitle == null)
			getMendixObject().setValue(context, MemberNames.Person_AddressTitle.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Person_AddressTitle.toString(), person_addresstitle.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return addressTitleMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final personswithsingleuseraccount.proxies.AddressTitle that = (personswithsingleuseraccount.proxies.AddressTitle) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PersonsWithSingleUserAccount.AddressTitle";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
