// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package personswithsingleuseraccount.proxies;

/**
 * One person. Having only one UserAccount.
 */
public class Person
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject personMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PersonsWithSingleUserAccount.Person";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FirstName("FirstName"),
		MiddleName("MiddleName"),
		LastName("LastName"),
		FullName("FullName"),
		ChangeFullName("ChangeFullName"),
		Birthdate("Birthdate"),
		Gender("Gender"),
		Title("Title"),
		PhoneNumber("PhoneNumber"),
		EmailAddress("EmailAddress"),
		Person_AddressTitle("PersonsWithSingleUserAccount.Person_AddressTitle"),
		Person_MotherPerson("PersonsWithSingleUserAccount.Person_MotherPerson"),
		Person_FatherPerson("PersonsWithSingleUserAccount.Person_FatherPerson"),
		Person_SocialMedia("PersonsWithSingleUserAccount.Person_SocialMedia"),
		Person_ProfileImage("PersonsWithSingleUserAccount.Person_ProfileImage"),
		Person_User("PersonsWithSingleUserAccount.Person_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Person(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PersonsWithSingleUserAccount.Person"));
	}

	protected Person(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject personMendixObject)
	{
		if (personMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PersonsWithSingleUserAccount.Person", personMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PersonsWithSingleUserAccount.Person");

		this.personMendixObject = personMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Person.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static personswithsingleuseraccount.proxies.Person initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return personswithsingleuseraccount.proxies.Person.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static personswithsingleuseraccount.proxies.Person initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new personswithsingleuseraccount.proxies.Person(context, mendixObject);
	}

	public static personswithsingleuseraccount.proxies.Person load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return personswithsingleuseraccount.proxies.Person.initialize(context, mendixObject);
	}

	public static java.util.List<personswithsingleuseraccount.proxies.Person> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<personswithsingleuseraccount.proxies.Person> result = new java.util.ArrayList<personswithsingleuseraccount.proxies.Person>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PersonsWithSingleUserAccount.Person" + xpathConstraint))
			result.add(personswithsingleuseraccount.proxies.Person.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of MiddleName
	 */
	public final java.lang.String getMiddleName()
	{
		return getMiddleName(getContext());
	}

	/**
	 * @param context
	 * @return value of MiddleName
	 */
	public final java.lang.String getMiddleName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MiddleName.toString());
	}

	/**
	 * Set value of MiddleName
	 * @param middlename
	 */
	public final void setMiddleName(java.lang.String middlename)
	{
		setMiddleName(getContext(), middlename);
	}

	/**
	 * Set value of MiddleName
	 * @param context
	 * @param middlename
	 */
	public final void setMiddleName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String middlename)
	{
		getMendixObject().setValue(context, MemberNames.MiddleName.toString(), middlename);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of FullName
	 */
	public final java.lang.String getFullName()
	{
		return getFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FullName
	 */
	public final java.lang.String getFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FullName.toString());
	}

	/**
	 * Set value of FullName
	 * @param fullname
	 */
	public final void setFullName(java.lang.String fullname)
	{
		setFullName(getContext(), fullname);
	}

	/**
	 * Set value of FullName
	 * @param context
	 * @param fullname
	 */
	public final void setFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fullname)
	{
		getMendixObject().setValue(context, MemberNames.FullName.toString(), fullname);
	}

	/**
	 * @return value of ChangeFullName
	 */
	public final java.lang.Boolean getChangeFullName()
	{
		return getChangeFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of ChangeFullName
	 */
	public final java.lang.Boolean getChangeFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ChangeFullName.toString());
	}

	/**
	 * Set value of ChangeFullName
	 * @param changefullname
	 */
	public final void setChangeFullName(java.lang.Boolean changefullname)
	{
		setChangeFullName(getContext(), changefullname);
	}

	/**
	 * Set value of ChangeFullName
	 * @param context
	 * @param changefullname
	 */
	public final void setChangeFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean changefullname)
	{
		getMendixObject().setValue(context, MemberNames.ChangeFullName.toString(), changefullname);
	}

	/**
	 * @return value of Birthdate
	 */
	public final java.util.Date getBirthdate()
	{
		return getBirthdate(getContext());
	}

	/**
	 * @param context
	 * @return value of Birthdate
	 */
	public final java.util.Date getBirthdate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Birthdate.toString());
	}

	/**
	 * Set value of Birthdate
	 * @param birthdate
	 */
	public final void setBirthdate(java.util.Date birthdate)
	{
		setBirthdate(getContext(), birthdate);
	}

	/**
	 * Set value of Birthdate
	 * @param context
	 * @param birthdate
	 */
	public final void setBirthdate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date birthdate)
	{
		getMendixObject().setValue(context, MemberNames.Birthdate.toString(), birthdate);
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final personswithsingleuseraccount.proxies.Enum_PersonGender getGender()
	{
		return getGender(getContext());
	}

	/**
	 * @param context
	 * @return value of Gender
	 */
	public final personswithsingleuseraccount.proxies.Enum_PersonGender getGender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Gender.toString());
		if (obj == null)
			return null;

		return personswithsingleuseraccount.proxies.Enum_PersonGender.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final void setGender(personswithsingleuseraccount.proxies.Enum_PersonGender gender)
	{
		setGender(getContext(), gender);
	}

	/**
	 * Set value of Gender
	 * @param context
	 * @param gender
	 */
	public final void setGender(com.mendix.systemwideinterfaces.core.IContext context, personswithsingleuseraccount.proxies.Enum_PersonGender gender)
	{
		if (gender != null)
			getMendixObject().setValue(context, MemberNames.Gender.toString(), gender.toString());
		else
			getMendixObject().setValue(context, MemberNames.Gender.toString(), null);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber()
	{
		return getPhoneNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PhoneNumber.toString());
	}

	/**
	 * Set value of PhoneNumber
	 * @param phonenumber
	 */
	public final void setPhoneNumber(java.lang.String phonenumber)
	{
		setPhoneNumber(getContext(), phonenumber);
	}

	/**
	 * Set value of PhoneNumber
	 * @param context
	 * @param phonenumber
	 */
	public final void setPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phonenumber)
	{
		getMendixObject().setValue(context, MemberNames.PhoneNumber.toString(), phonenumber);
	}

	/**
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress()
	{
		return getEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailAddress.toString());
	}

	/**
	 * Set value of EmailAddress
	 * @param emailaddress
	 */
	public final void setEmailAddress(java.lang.String emailaddress)
	{
		setEmailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of EmailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.EmailAddress.toString(), emailaddress);
	}

	/**
	 * @return value of Person_AddressTitle
	 */
	public final personswithsingleuseraccount.proxies.AddressTitle getPerson_AddressTitle() throws com.mendix.core.CoreException
	{
		return getPerson_AddressTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_AddressTitle
	 */
	public final personswithsingleuseraccount.proxies.AddressTitle getPerson_AddressTitle(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		personswithsingleuseraccount.proxies.AddressTitle result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_AddressTitle.toString());
		if (identifier != null)
			result = personswithsingleuseraccount.proxies.AddressTitle.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Person_AddressTitle
	 * @param person_addresstitle
	 */
	public final void setPerson_AddressTitle(personswithsingleuseraccount.proxies.AddressTitle person_addresstitle)
	{
		setPerson_AddressTitle(getContext(), person_addresstitle);
	}

	/**
	 * Set value of Person_AddressTitle
	 * @param context
	 * @param person_addresstitle
	 */
	public final void setPerson_AddressTitle(com.mendix.systemwideinterfaces.core.IContext context, personswithsingleuseraccount.proxies.AddressTitle person_addresstitle)
	{
		if (person_addresstitle == null)
			getMendixObject().setValue(context, MemberNames.Person_AddressTitle.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Person_AddressTitle.toString(), person_addresstitle.getMendixObject().getId());
	}

	/**
	 * @return value of Person_MotherPerson
	 */
	public final personswithsingleuseraccount.proxies.Person getPerson_MotherPerson() throws com.mendix.core.CoreException
	{
		return getPerson_MotherPerson(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_MotherPerson
	 */
	public final personswithsingleuseraccount.proxies.Person getPerson_MotherPerson(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		personswithsingleuseraccount.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_MotherPerson.toString());
		if (identifier != null)
			result = personswithsingleuseraccount.proxies.Person.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Person_MotherPerson
	 * @param person_motherperson
	 */
	public final void setPerson_MotherPerson(personswithsingleuseraccount.proxies.Person person_motherperson)
	{
		setPerson_MotherPerson(getContext(), person_motherperson);
	}

	/**
	 * Set value of Person_MotherPerson
	 * @param context
	 * @param person_motherperson
	 */
	public final void setPerson_MotherPerson(com.mendix.systemwideinterfaces.core.IContext context, personswithsingleuseraccount.proxies.Person person_motherperson)
	{
		if (person_motherperson == null)
			getMendixObject().setValue(context, MemberNames.Person_MotherPerson.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Person_MotherPerson.toString(), person_motherperson.getMendixObject().getId());
	}

	/**
	 * @return value of Person_FatherPerson
	 */
	public final personswithsingleuseraccount.proxies.Person getPerson_FatherPerson() throws com.mendix.core.CoreException
	{
		return getPerson_FatherPerson(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_FatherPerson
	 */
	public final personswithsingleuseraccount.proxies.Person getPerson_FatherPerson(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		personswithsingleuseraccount.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_FatherPerson.toString());
		if (identifier != null)
			result = personswithsingleuseraccount.proxies.Person.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Person_FatherPerson
	 * @param person_fatherperson
	 */
	public final void setPerson_FatherPerson(personswithsingleuseraccount.proxies.Person person_fatherperson)
	{
		setPerson_FatherPerson(getContext(), person_fatherperson);
	}

	/**
	 * Set value of Person_FatherPerson
	 * @param context
	 * @param person_fatherperson
	 */
	public final void setPerson_FatherPerson(com.mendix.systemwideinterfaces.core.IContext context, personswithsingleuseraccount.proxies.Person person_fatherperson)
	{
		if (person_fatherperson == null)
			getMendixObject().setValue(context, MemberNames.Person_FatherPerson.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Person_FatherPerson.toString(), person_fatherperson.getMendixObject().getId());
	}

	/**
	 * @return value of Person_SocialMedia
	 */
	public final personswithsingleuseraccount.proxies.SocialMedia getPerson_SocialMedia() throws com.mendix.core.CoreException
	{
		return getPerson_SocialMedia(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_SocialMedia
	 */
	public final personswithsingleuseraccount.proxies.SocialMedia getPerson_SocialMedia(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		personswithsingleuseraccount.proxies.SocialMedia result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_SocialMedia.toString());
		if (identifier != null)
			result = personswithsingleuseraccount.proxies.SocialMedia.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Person_SocialMedia
	 * @param person_socialmedia
	 */
	public final void setPerson_SocialMedia(personswithsingleuseraccount.proxies.SocialMedia person_socialmedia)
	{
		setPerson_SocialMedia(getContext(), person_socialmedia);
	}

	/**
	 * Set value of Person_SocialMedia
	 * @param context
	 * @param person_socialmedia
	 */
	public final void setPerson_SocialMedia(com.mendix.systemwideinterfaces.core.IContext context, personswithsingleuseraccount.proxies.SocialMedia person_socialmedia)
	{
		if (person_socialmedia == null)
			getMendixObject().setValue(context, MemberNames.Person_SocialMedia.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Person_SocialMedia.toString(), person_socialmedia.getMendixObject().getId());
	}

	/**
	 * @return value of Person_ProfileImage
	 */
	public final personswithsingleuseraccount.proxies.ProfileImage getPerson_ProfileImage() throws com.mendix.core.CoreException
	{
		return getPerson_ProfileImage(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_ProfileImage
	 */
	public final personswithsingleuseraccount.proxies.ProfileImage getPerson_ProfileImage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		personswithsingleuseraccount.proxies.ProfileImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_ProfileImage.toString());
		if (identifier != null)
			result = personswithsingleuseraccount.proxies.ProfileImage.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Person_ProfileImage
	 * @param person_profileimage
	 */
	public final void setPerson_ProfileImage(personswithsingleuseraccount.proxies.ProfileImage person_profileimage)
	{
		setPerson_ProfileImage(getContext(), person_profileimage);
	}

	/**
	 * Set value of Person_ProfileImage
	 * @param context
	 * @param person_profileimage
	 */
	public final void setPerson_ProfileImage(com.mendix.systemwideinterfaces.core.IContext context, personswithsingleuseraccount.proxies.ProfileImage person_profileimage)
	{
		if (person_profileimage == null)
			getMendixObject().setValue(context, MemberNames.Person_ProfileImage.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Person_ProfileImage.toString(), person_profileimage.getMendixObject().getId());
	}

	/**
	 * @return value of Person_User
	 */
	public final system.proxies.User getPerson_User() throws com.mendix.core.CoreException
	{
		return getPerson_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_User
	 */
	public final system.proxies.User getPerson_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_User.toString());
		if (identifier != null)
			result = system.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Person_User
	 * @param person_user
	 */
	public final void setPerson_User(system.proxies.User person_user)
	{
		setPerson_User(getContext(), person_user);
	}

	/**
	 * Set value of Person_User
	 * @param context
	 * @param person_user
	 */
	public final void setPerson_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User person_user)
	{
		if (person_user == null)
			getMendixObject().setValue(context, MemberNames.Person_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Person_User.toString(), person_user.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return personMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final personswithsingleuseraccount.proxies.Person that = (personswithsingleuseraccount.proxies.Person) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PersonsWithSingleUserAccount.Person";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
