// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package personswithsingleuseraccount.proxies;

/**
 * An person's image usable as a person's thumbnail in applications
 */
public class ProfileImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PersonsWithSingleUserAccount.ProfileImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Person_ProfileImage("PersonsWithSingleUserAccount.Person_ProfileImage");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProfileImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PersonsWithSingleUserAccount.ProfileImage"));
	}

	protected ProfileImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject profileImageMendixObject)
	{
		super(context, profileImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("PersonsWithSingleUserAccount.ProfileImage", profileImageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PersonsWithSingleUserAccount.ProfileImage");
	}

	/**
	 * @deprecated Use 'ProfileImage.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static personswithsingleuseraccount.proxies.ProfileImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return personswithsingleuseraccount.proxies.ProfileImage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static personswithsingleuseraccount.proxies.ProfileImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new personswithsingleuseraccount.proxies.ProfileImage(context, mendixObject);
	}

	public static personswithsingleuseraccount.proxies.ProfileImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return personswithsingleuseraccount.proxies.ProfileImage.initialize(context, mendixObject);
	}

	public static java.util.List<personswithsingleuseraccount.proxies.ProfileImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<personswithsingleuseraccount.proxies.ProfileImage> result = new java.util.ArrayList<personswithsingleuseraccount.proxies.ProfileImage>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PersonsWithSingleUserAccount.ProfileImage" + xpathConstraint))
			result.add(personswithsingleuseraccount.proxies.ProfileImage.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Person_ProfileImage
	 */
	public final personswithsingleuseraccount.proxies.Person getPerson_ProfileImage() throws com.mendix.core.CoreException
	{
		return getPerson_ProfileImage(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_ProfileImage
	 */
	public final personswithsingleuseraccount.proxies.Person getPerson_ProfileImage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		personswithsingleuseraccount.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_ProfileImage.toString());
		if (identifier != null)
			result = personswithsingleuseraccount.proxies.Person.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Person_ProfileImage
	 * @param person_profileimage
	 */
	public final void setPerson_ProfileImage(personswithsingleuseraccount.proxies.Person person_profileimage)
	{
		setPerson_ProfileImage(getContext(), person_profileimage);
	}

	/**
	 * Set value of Person_ProfileImage
	 * @param context
	 * @param person_profileimage
	 */
	public final void setPerson_ProfileImage(com.mendix.systemwideinterfaces.core.IContext context, personswithsingleuseraccount.proxies.Person person_profileimage)
	{
		if (person_profileimage == null)
			getMendixObject().setValue(context, MemberNames.Person_ProfileImage.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Person_ProfileImage.toString(), person_profileimage.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final personswithsingleuseraccount.proxies.ProfileImage that = (personswithsingleuseraccount.proxies.ProfileImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PersonsWithSingleUserAccount.ProfileImage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
