// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package personswithsingleuseraccount.proxies;

/**
 * Some of the social media accounts of this person.
 */
public class SocialMedia
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject socialMediaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PersonsWithSingleUserAccount.SocialMedia";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TwitterAccount("TwitterAccount"),
		FacebookAccount("FacebookAccount"),
		PinterestAccount("PinterestAccount"),
		InstagramAccount("InstagramAccount"),
		SnapchatAccount("SnapchatAccount"),
		Person_SocialMedia("PersonsWithSingleUserAccount.Person_SocialMedia");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SocialMedia(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PersonsWithSingleUserAccount.SocialMedia"));
	}

	protected SocialMedia(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject socialMediaMendixObject)
	{
		if (socialMediaMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PersonsWithSingleUserAccount.SocialMedia", socialMediaMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PersonsWithSingleUserAccount.SocialMedia");

		this.socialMediaMendixObject = socialMediaMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SocialMedia.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static personswithsingleuseraccount.proxies.SocialMedia initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return personswithsingleuseraccount.proxies.SocialMedia.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static personswithsingleuseraccount.proxies.SocialMedia initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new personswithsingleuseraccount.proxies.SocialMedia(context, mendixObject);
	}

	public static personswithsingleuseraccount.proxies.SocialMedia load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return personswithsingleuseraccount.proxies.SocialMedia.initialize(context, mendixObject);
	}

	public static java.util.List<personswithsingleuseraccount.proxies.SocialMedia> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<personswithsingleuseraccount.proxies.SocialMedia> result = new java.util.ArrayList<personswithsingleuseraccount.proxies.SocialMedia>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PersonsWithSingleUserAccount.SocialMedia" + xpathConstraint))
			result.add(personswithsingleuseraccount.proxies.SocialMedia.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TwitterAccount
	 */
	public final java.lang.String getTwitterAccount()
	{
		return getTwitterAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of TwitterAccount
	 */
	public final java.lang.String getTwitterAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TwitterAccount.toString());
	}

	/**
	 * Set value of TwitterAccount
	 * @param twitteraccount
	 */
	public final void setTwitterAccount(java.lang.String twitteraccount)
	{
		setTwitterAccount(getContext(), twitteraccount);
	}

	/**
	 * Set value of TwitterAccount
	 * @param context
	 * @param twitteraccount
	 */
	public final void setTwitterAccount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String twitteraccount)
	{
		getMendixObject().setValue(context, MemberNames.TwitterAccount.toString(), twitteraccount);
	}

	/**
	 * @return value of FacebookAccount
	 */
	public final java.lang.String getFacebookAccount()
	{
		return getFacebookAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of FacebookAccount
	 */
	public final java.lang.String getFacebookAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FacebookAccount.toString());
	}

	/**
	 * Set value of FacebookAccount
	 * @param facebookaccount
	 */
	public final void setFacebookAccount(java.lang.String facebookaccount)
	{
		setFacebookAccount(getContext(), facebookaccount);
	}

	/**
	 * Set value of FacebookAccount
	 * @param context
	 * @param facebookaccount
	 */
	public final void setFacebookAccount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String facebookaccount)
	{
		getMendixObject().setValue(context, MemberNames.FacebookAccount.toString(), facebookaccount);
	}

	/**
	 * @return value of PinterestAccount
	 */
	public final java.lang.String getPinterestAccount()
	{
		return getPinterestAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of PinterestAccount
	 */
	public final java.lang.String getPinterestAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PinterestAccount.toString());
	}

	/**
	 * Set value of PinterestAccount
	 * @param pinterestaccount
	 */
	public final void setPinterestAccount(java.lang.String pinterestaccount)
	{
		setPinterestAccount(getContext(), pinterestaccount);
	}

	/**
	 * Set value of PinterestAccount
	 * @param context
	 * @param pinterestaccount
	 */
	public final void setPinterestAccount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pinterestaccount)
	{
		getMendixObject().setValue(context, MemberNames.PinterestAccount.toString(), pinterestaccount);
	}

	/**
	 * @return value of InstagramAccount
	 */
	public final java.lang.String getInstagramAccount()
	{
		return getInstagramAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of InstagramAccount
	 */
	public final java.lang.String getInstagramAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstagramAccount.toString());
	}

	/**
	 * Set value of InstagramAccount
	 * @param instagramaccount
	 */
	public final void setInstagramAccount(java.lang.String instagramaccount)
	{
		setInstagramAccount(getContext(), instagramaccount);
	}

	/**
	 * Set value of InstagramAccount
	 * @param context
	 * @param instagramaccount
	 */
	public final void setInstagramAccount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instagramaccount)
	{
		getMendixObject().setValue(context, MemberNames.InstagramAccount.toString(), instagramaccount);
	}

	/**
	 * @return value of SnapchatAccount
	 */
	public final java.lang.String getSnapchatAccount()
	{
		return getSnapchatAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of SnapchatAccount
	 */
	public final java.lang.String getSnapchatAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SnapchatAccount.toString());
	}

	/**
	 * Set value of SnapchatAccount
	 * @param snapchataccount
	 */
	public final void setSnapchatAccount(java.lang.String snapchataccount)
	{
		setSnapchatAccount(getContext(), snapchataccount);
	}

	/**
	 * Set value of SnapchatAccount
	 * @param context
	 * @param snapchataccount
	 */
	public final void setSnapchatAccount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String snapchataccount)
	{
		getMendixObject().setValue(context, MemberNames.SnapchatAccount.toString(), snapchataccount);
	}

	/**
	 * @return value of Person_SocialMedia
	 */
	public final personswithsingleuseraccount.proxies.Person getPerson_SocialMedia() throws com.mendix.core.CoreException
	{
		return getPerson_SocialMedia(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_SocialMedia
	 */
	public final personswithsingleuseraccount.proxies.Person getPerson_SocialMedia(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		personswithsingleuseraccount.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_SocialMedia.toString());
		if (identifier != null)
			result = personswithsingleuseraccount.proxies.Person.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Person_SocialMedia
	 * @param person_socialmedia
	 */
	public final void setPerson_SocialMedia(personswithsingleuseraccount.proxies.Person person_socialmedia)
	{
		setPerson_SocialMedia(getContext(), person_socialmedia);
	}

	/**
	 * Set value of Person_SocialMedia
	 * @param context
	 * @param person_socialmedia
	 */
	public final void setPerson_SocialMedia(com.mendix.systemwideinterfaces.core.IContext context, personswithsingleuseraccount.proxies.Person person_socialmedia)
	{
		if (person_socialmedia == null)
			getMendixObject().setValue(context, MemberNames.Person_SocialMedia.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Person_SocialMedia.toString(), person_socialmedia.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return socialMediaMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final personswithsingleuseraccount.proxies.SocialMedia that = (personswithsingleuseraccount.proxies.SocialMedia) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PersonsWithSingleUserAccount.SocialMedia";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
