// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package personswithsingleuseraccount.proxies;

/**
 * Identificationnumber for the taxes
 */
public class TaxId
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject taxIdMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PersonsWithSingleUserAccount.TaxId";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BSN("BSN"),
		SocialSecurityNumber("SocialSecurityNumber"),
		Steuernummer("Steuernummer"),
		SteuerId("SteuerId"),
		UmzatsSteuerId("UmzatsSteuerId"),
		TaxId_Person("PersonsWithSingleUserAccount.TaxId_Person");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TaxId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PersonsWithSingleUserAccount.TaxId"));
	}

	protected TaxId(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject taxIdMendixObject)
	{
		if (taxIdMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PersonsWithSingleUserAccount.TaxId", taxIdMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PersonsWithSingleUserAccount.TaxId");

		this.taxIdMendixObject = taxIdMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TaxId.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static personswithsingleuseraccount.proxies.TaxId initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return personswithsingleuseraccount.proxies.TaxId.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static personswithsingleuseraccount.proxies.TaxId initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new personswithsingleuseraccount.proxies.TaxId(context, mendixObject);
	}

	public static personswithsingleuseraccount.proxies.TaxId load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return personswithsingleuseraccount.proxies.TaxId.initialize(context, mendixObject);
	}

	public static java.util.List<personswithsingleuseraccount.proxies.TaxId> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<personswithsingleuseraccount.proxies.TaxId> result = new java.util.ArrayList<personswithsingleuseraccount.proxies.TaxId>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PersonsWithSingleUserAccount.TaxId" + xpathConstraint))
			result.add(personswithsingleuseraccount.proxies.TaxId.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of BSN
	 */
	public final java.lang.String getBSN()
	{
		return getBSN(getContext());
	}

	/**
	 * @param context
	 * @return value of BSN
	 */
	public final java.lang.String getBSN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BSN.toString());
	}

	/**
	 * Set value of BSN
	 * @param bsn
	 */
	public final void setBSN(java.lang.String bsn)
	{
		setBSN(getContext(), bsn);
	}

	/**
	 * Set value of BSN
	 * @param context
	 * @param bsn
	 */
	public final void setBSN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bsn)
	{
		getMendixObject().setValue(context, MemberNames.BSN.toString(), bsn);
	}

	/**
	 * @return value of SocialSecurityNumber
	 */
	public final java.lang.String getSocialSecurityNumber()
	{
		return getSocialSecurityNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of SocialSecurityNumber
	 */
	public final java.lang.String getSocialSecurityNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SocialSecurityNumber.toString());
	}

	/**
	 * Set value of SocialSecurityNumber
	 * @param socialsecuritynumber
	 */
	public final void setSocialSecurityNumber(java.lang.String socialsecuritynumber)
	{
		setSocialSecurityNumber(getContext(), socialsecuritynumber);
	}

	/**
	 * Set value of SocialSecurityNumber
	 * @param context
	 * @param socialsecuritynumber
	 */
	public final void setSocialSecurityNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String socialsecuritynumber)
	{
		getMendixObject().setValue(context, MemberNames.SocialSecurityNumber.toString(), socialsecuritynumber);
	}

	/**
	 * @return value of Steuernummer
	 */
	public final java.lang.String getSteuernummer()
	{
		return getSteuernummer(getContext());
	}

	/**
	 * @param context
	 * @return value of Steuernummer
	 */
	public final java.lang.String getSteuernummer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Steuernummer.toString());
	}

	/**
	 * Set value of Steuernummer
	 * @param steuernummer
	 */
	public final void setSteuernummer(java.lang.String steuernummer)
	{
		setSteuernummer(getContext(), steuernummer);
	}

	/**
	 * Set value of Steuernummer
	 * @param context
	 * @param steuernummer
	 */
	public final void setSteuernummer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String steuernummer)
	{
		getMendixObject().setValue(context, MemberNames.Steuernummer.toString(), steuernummer);
	}

	/**
	 * @return value of SteuerId
	 */
	public final java.lang.String getSteuerId()
	{
		return getSteuerId(getContext());
	}

	/**
	 * @param context
	 * @return value of SteuerId
	 */
	public final java.lang.String getSteuerId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SteuerId.toString());
	}

	/**
	 * Set value of SteuerId
	 * @param steuerid
	 */
	public final void setSteuerId(java.lang.String steuerid)
	{
		setSteuerId(getContext(), steuerid);
	}

	/**
	 * Set value of SteuerId
	 * @param context
	 * @param steuerid
	 */
	public final void setSteuerId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String steuerid)
	{
		getMendixObject().setValue(context, MemberNames.SteuerId.toString(), steuerid);
	}

	/**
	 * @return value of UmzatsSteuerId
	 */
	public final java.lang.String getUmzatsSteuerId()
	{
		return getUmzatsSteuerId(getContext());
	}

	/**
	 * @param context
	 * @return value of UmzatsSteuerId
	 */
	public final java.lang.String getUmzatsSteuerId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UmzatsSteuerId.toString());
	}

	/**
	 * Set value of UmzatsSteuerId
	 * @param umzatssteuerid
	 */
	public final void setUmzatsSteuerId(java.lang.String umzatssteuerid)
	{
		setUmzatsSteuerId(getContext(), umzatssteuerid);
	}

	/**
	 * Set value of UmzatsSteuerId
	 * @param context
	 * @param umzatssteuerid
	 */
	public final void setUmzatsSteuerId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String umzatssteuerid)
	{
		getMendixObject().setValue(context, MemberNames.UmzatsSteuerId.toString(), umzatssteuerid);
	}

	/**
	 * @return value of TaxId_Person
	 */
	public final personswithsingleuseraccount.proxies.Person getTaxId_Person() throws com.mendix.core.CoreException
	{
		return getTaxId_Person(getContext());
	}

	/**
	 * @param context
	 * @return value of TaxId_Person
	 */
	public final personswithsingleuseraccount.proxies.Person getTaxId_Person(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		personswithsingleuseraccount.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaxId_Person.toString());
		if (identifier != null)
			result = personswithsingleuseraccount.proxies.Person.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TaxId_Person
	 * @param taxid_person
	 */
	public final void setTaxId_Person(personswithsingleuseraccount.proxies.Person taxid_person)
	{
		setTaxId_Person(getContext(), taxid_person);
	}

	/**
	 * Set value of TaxId_Person
	 * @param context
	 * @param taxid_person
	 */
	public final void setTaxId_Person(com.mendix.systemwideinterfaces.core.IContext context, personswithsingleuseraccount.proxies.Person taxid_person)
	{
		if (taxid_person == null)
			getMendixObject().setValue(context, MemberNames.TaxId_Person.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TaxId_Person.toString(), taxid_person.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return taxIdMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final personswithsingleuseraccount.proxies.TaxId that = (personswithsingleuseraccount.proxies.TaxId) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PersonsWithSingleUserAccount.TaxId";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
