// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package environmentvariables.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the EnvironmentVariables module

	/**
	* Either D, T, A or P, or S or Z and limited to those six values.
	* D, T, A and P are commonly used.
	* Z, for performance environments (since P is already taken for production)
	* S, for soak environments
	* 
	* Default is D because this is usefull during development.
	*/
	public static java.lang.String getEnvironmentLetter()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EnvironmentVariables.EnvironmentLetter");
	}

	public static java.lang.String getLognode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EnvironmentVariables.Lognode");
	}
}