// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasewriteerrors.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the DatabaseWriteErrors module
	public static void sUB_Ride_PostChangeRoute_AddParcel(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DatabaseWriteErrors.SUB_Ride_PostChangeRoute_AddParcel").withParams(params).execute(context);
	}
	public static void writeMe_AddSeveralObjects(IContext context, databasewriteerrors.proxies.Enum_Error _enum_Error)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Enum_Error", _enum_Error == null ? null : _enum_Error.name());
		Core.microflowCall("DatabaseWriteErrors.WriteMe_AddSeveralObjects").withParams(params).execute(context);
	}
}