// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package deeplink.proxies;

public class DeepLink
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject deepLinkMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DeepLink.DeepLink";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Microflow("Microflow"),
		ObjectType("ObjectType"),
		ObjectAttribute("ObjectAttribute"),
		AllowGuests("AllowGuests"),
		UseStringArgument("UseStringArgument"),
		IncludeGetParameters("IncludeGetParameters"),
		SeparateGetParameters("SeparateGetParameters"),
		UseAsHome("UseAsHome"),
		IndexPage("IndexPage"),
		HitCount("HitCount"),
		ArgumentExample("ArgumentExample"),
		UseObjectArgument("UseObjectArgument"),
		DeepLink_Microflow("DeepLink.DeepLink_Microflow"),
		DeepLink_Entity("DeepLink.DeepLink_Entity"),
		DeepLink_Attribute("DeepLink.DeepLink_Attribute"),
		DeepLink_Language("DeepLink.DeepLink_Language");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DeepLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DeepLink.DeepLink"));
	}

	protected DeepLink(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject deepLinkMendixObject)
	{
		if (deepLinkMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DeepLink.DeepLink", deepLinkMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DeepLink.DeepLink");

		this.deepLinkMendixObject = deepLinkMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DeepLink.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static deeplink.proxies.DeepLink initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return deeplink.proxies.DeepLink.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static deeplink.proxies.DeepLink initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new deeplink.proxies.DeepLink(context, mendixObject);
	}

	public static deeplink.proxies.DeepLink load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return deeplink.proxies.DeepLink.initialize(context, mendixObject);
	}

	public static java.util.List<deeplink.proxies.DeepLink> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<deeplink.proxies.DeepLink> result = new java.util.ArrayList<deeplink.proxies.DeepLink>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DeepLink.DeepLink" + xpathConstraint))
			result.add(deeplink.proxies.DeepLink.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Microflow
	 */
	public final java.lang.String getMicroflow()
	{
		return getMicroflow(getContext());
	}

	/**
	 * @param context
	 * @return value of Microflow
	 */
	public final java.lang.String getMicroflow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Microflow.toString());
	}

	/**
	 * Set value of Microflow
	 * @param microflow
	 */
	public final void setMicroflow(java.lang.String microflow)
	{
		setMicroflow(getContext(), microflow);
	}

	/**
	 * Set value of Microflow
	 * @param context
	 * @param microflow
	 */
	public final void setMicroflow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String microflow)
	{
		getMendixObject().setValue(context, MemberNames.Microflow.toString(), microflow);
	}

	/**
	 * @return value of ObjectType
	 */
	public final java.lang.String getObjectType()
	{
		return getObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of ObjectType
	 */
	public final java.lang.String getObjectType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ObjectType.toString());
	}

	/**
	 * Set value of ObjectType
	 * @param objecttype
	 */
	public final void setObjectType(java.lang.String objecttype)
	{
		setObjectType(getContext(), objecttype);
	}

	/**
	 * Set value of ObjectType
	 * @param context
	 * @param objecttype
	 */
	public final void setObjectType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String objecttype)
	{
		getMendixObject().setValue(context, MemberNames.ObjectType.toString(), objecttype);
	}

	/**
	 * @return value of ObjectAttribute
	 */
	public final java.lang.String getObjectAttribute()
	{
		return getObjectAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of ObjectAttribute
	 */
	public final java.lang.String getObjectAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ObjectAttribute.toString());
	}

	/**
	 * Set value of ObjectAttribute
	 * @param objectattribute
	 */
	public final void setObjectAttribute(java.lang.String objectattribute)
	{
		setObjectAttribute(getContext(), objectattribute);
	}

	/**
	 * Set value of ObjectAttribute
	 * @param context
	 * @param objectattribute
	 */
	public final void setObjectAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String objectattribute)
	{
		getMendixObject().setValue(context, MemberNames.ObjectAttribute.toString(), objectattribute);
	}

	/**
	 * @return value of AllowGuests
	 */
	public final java.lang.Boolean getAllowGuests()
	{
		return getAllowGuests(getContext());
	}

	/**
	 * @param context
	 * @return value of AllowGuests
	 */
	public final java.lang.Boolean getAllowGuests(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AllowGuests.toString());
	}

	/**
	 * Set value of AllowGuests
	 * @param allowguests
	 */
	public final void setAllowGuests(java.lang.Boolean allowguests)
	{
		setAllowGuests(getContext(), allowguests);
	}

	/**
	 * Set value of AllowGuests
	 * @param context
	 * @param allowguests
	 */
	public final void setAllowGuests(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean allowguests)
	{
		getMendixObject().setValue(context, MemberNames.AllowGuests.toString(), allowguests);
	}

	/**
	 * @return value of UseStringArgument
	 */
	public final java.lang.Boolean getUseStringArgument()
	{
		return getUseStringArgument(getContext());
	}

	/**
	 * @param context
	 * @return value of UseStringArgument
	 */
	public final java.lang.Boolean getUseStringArgument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseStringArgument.toString());
	}

	/**
	 * Set value of UseStringArgument
	 * @param usestringargument
	 */
	public final void setUseStringArgument(java.lang.Boolean usestringargument)
	{
		setUseStringArgument(getContext(), usestringargument);
	}

	/**
	 * Set value of UseStringArgument
	 * @param context
	 * @param usestringargument
	 */
	public final void setUseStringArgument(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean usestringargument)
	{
		getMendixObject().setValue(context, MemberNames.UseStringArgument.toString(), usestringargument);
	}

	/**
	 * @return value of IncludeGetParameters
	 */
	public final java.lang.Boolean getIncludeGetParameters()
	{
		return getIncludeGetParameters(getContext());
	}

	/**
	 * @param context
	 * @return value of IncludeGetParameters
	 */
	public final java.lang.Boolean getIncludeGetParameters(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IncludeGetParameters.toString());
	}

	/**
	 * Set value of IncludeGetParameters
	 * @param includegetparameters
	 */
	public final void setIncludeGetParameters(java.lang.Boolean includegetparameters)
	{
		setIncludeGetParameters(getContext(), includegetparameters);
	}

	/**
	 * Set value of IncludeGetParameters
	 * @param context
	 * @param includegetparameters
	 */
	public final void setIncludeGetParameters(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean includegetparameters)
	{
		getMendixObject().setValue(context, MemberNames.IncludeGetParameters.toString(), includegetparameters);
	}

	/**
	 * @return value of SeparateGetParameters
	 */
	public final java.lang.Boolean getSeparateGetParameters()
	{
		return getSeparateGetParameters(getContext());
	}

	/**
	 * @param context
	 * @return value of SeparateGetParameters
	 */
	public final java.lang.Boolean getSeparateGetParameters(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SeparateGetParameters.toString());
	}

	/**
	 * Set value of SeparateGetParameters
	 * @param separategetparameters
	 */
	public final void setSeparateGetParameters(java.lang.Boolean separategetparameters)
	{
		setSeparateGetParameters(getContext(), separategetparameters);
	}

	/**
	 * Set value of SeparateGetParameters
	 * @param context
	 * @param separategetparameters
	 */
	public final void setSeparateGetParameters(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean separategetparameters)
	{
		getMendixObject().setValue(context, MemberNames.SeparateGetParameters.toString(), separategetparameters);
	}

	/**
	 * @return value of UseAsHome
	 */
	public final java.lang.Boolean getUseAsHome()
	{
		return getUseAsHome(getContext());
	}

	/**
	 * @param context
	 * @return value of UseAsHome
	 */
	public final java.lang.Boolean getUseAsHome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseAsHome.toString());
	}

	/**
	 * Set value of UseAsHome
	 * @param useashome
	 */
	public final void setUseAsHome(java.lang.Boolean useashome)
	{
		setUseAsHome(getContext(), useashome);
	}

	/**
	 * Set value of UseAsHome
	 * @param context
	 * @param useashome
	 */
	public final void setUseAsHome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean useashome)
	{
		getMendixObject().setValue(context, MemberNames.UseAsHome.toString(), useashome);
	}

	/**
	 * @return value of IndexPage
	 */
	public final java.lang.String getIndexPage()
	{
		return getIndexPage(getContext());
	}

	/**
	 * @param context
	 * @return value of IndexPage
	 */
	public final java.lang.String getIndexPage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IndexPage.toString());
	}

	/**
	 * Set value of IndexPage
	 * @param indexpage
	 */
	public final void setIndexPage(java.lang.String indexpage)
	{
		setIndexPage(getContext(), indexpage);
	}

	/**
	 * Set value of IndexPage
	 * @param context
	 * @param indexpage
	 */
	public final void setIndexPage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String indexpage)
	{
		getMendixObject().setValue(context, MemberNames.IndexPage.toString(), indexpage);
	}

	/**
	 * @return value of HitCount
	 */
	public final java.lang.Integer getHitCount()
	{
		return getHitCount(getContext());
	}

	/**
	 * @param context
	 * @return value of HitCount
	 */
	public final java.lang.Integer getHitCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.HitCount.toString());
	}

	/**
	 * Set value of HitCount
	 * @param hitcount
	 */
	public final void setHitCount(java.lang.Integer hitcount)
	{
		setHitCount(getContext(), hitcount);
	}

	/**
	 * Set value of HitCount
	 * @param context
	 * @param hitcount
	 */
	public final void setHitCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer hitcount)
	{
		getMendixObject().setValue(context, MemberNames.HitCount.toString(), hitcount);
	}

	/**
	 * @return value of ArgumentExample
	 */
	public final java.lang.String getArgumentExample()
	{
		return getArgumentExample(getContext());
	}

	/**
	 * @param context
	 * @return value of ArgumentExample
	 */
	public final java.lang.String getArgumentExample(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ArgumentExample.toString());
	}

	/**
	 * Set value of ArgumentExample
	 * @param argumentexample
	 */
	public final void setArgumentExample(java.lang.String argumentexample)
	{
		setArgumentExample(getContext(), argumentexample);
	}

	/**
	 * Set value of ArgumentExample
	 * @param context
	 * @param argumentexample
	 */
	public final void setArgumentExample(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String argumentexample)
	{
		getMendixObject().setValue(context, MemberNames.ArgumentExample.toString(), argumentexample);
	}

	/**
	 * @return value of UseObjectArgument
	 */
	public final java.lang.Boolean getUseObjectArgument()
	{
		return getUseObjectArgument(getContext());
	}

	/**
	 * @param context
	 * @return value of UseObjectArgument
	 */
	public final java.lang.Boolean getUseObjectArgument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseObjectArgument.toString());
	}

	/**
	 * Set value of UseObjectArgument
	 * @param useobjectargument
	 */
	public final void setUseObjectArgument(java.lang.Boolean useobjectargument)
	{
		setUseObjectArgument(getContext(), useobjectargument);
	}

	/**
	 * Set value of UseObjectArgument
	 * @param context
	 * @param useobjectargument
	 */
	public final void setUseObjectArgument(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean useobjectargument)
	{
		getMendixObject().setValue(context, MemberNames.UseObjectArgument.toString(), useobjectargument);
	}

	/**
	 * @return value of DeepLink_Microflow
	 */
	public final deeplink.proxies.Microflow getDeepLink_Microflow() throws com.mendix.core.CoreException
	{
		return getDeepLink_Microflow(getContext());
	}

	/**
	 * @param context
	 * @return value of DeepLink_Microflow
	 */
	public final deeplink.proxies.Microflow getDeepLink_Microflow(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		deeplink.proxies.Microflow result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DeepLink_Microflow.toString());
		if (identifier != null)
			result = deeplink.proxies.Microflow.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DeepLink_Microflow
	 * @param deeplink_microflow
	 */
	public final void setDeepLink_Microflow(deeplink.proxies.Microflow deeplink_microflow)
	{
		setDeepLink_Microflow(getContext(), deeplink_microflow);
	}

	/**
	 * Set value of DeepLink_Microflow
	 * @param context
	 * @param deeplink_microflow
	 */
	public final void setDeepLink_Microflow(com.mendix.systemwideinterfaces.core.IContext context, deeplink.proxies.Microflow deeplink_microflow)
	{
		if (deeplink_microflow == null)
			getMendixObject().setValue(context, MemberNames.DeepLink_Microflow.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DeepLink_Microflow.toString(), deeplink_microflow.getMendixObject().getId());
	}

	/**
	 * @return value of DeepLink_Entity
	 */
	public final deeplink.proxies.Entity getDeepLink_Entity() throws com.mendix.core.CoreException
	{
		return getDeepLink_Entity(getContext());
	}

	/**
	 * @param context
	 * @return value of DeepLink_Entity
	 */
	public final deeplink.proxies.Entity getDeepLink_Entity(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		deeplink.proxies.Entity result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DeepLink_Entity.toString());
		if (identifier != null)
			result = deeplink.proxies.Entity.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DeepLink_Entity
	 * @param deeplink_entity
	 */
	public final void setDeepLink_Entity(deeplink.proxies.Entity deeplink_entity)
	{
		setDeepLink_Entity(getContext(), deeplink_entity);
	}

	/**
	 * Set value of DeepLink_Entity
	 * @param context
	 * @param deeplink_entity
	 */
	public final void setDeepLink_Entity(com.mendix.systemwideinterfaces.core.IContext context, deeplink.proxies.Entity deeplink_entity)
	{
		if (deeplink_entity == null)
			getMendixObject().setValue(context, MemberNames.DeepLink_Entity.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DeepLink_Entity.toString(), deeplink_entity.getMendixObject().getId());
	}

	/**
	 * @return value of DeepLink_Attribute
	 */
	public final deeplink.proxies.Attribute getDeepLink_Attribute() throws com.mendix.core.CoreException
	{
		return getDeepLink_Attribute(getContext());
	}

	/**
	 * @param context
	 * @return value of DeepLink_Attribute
	 */
	public final deeplink.proxies.Attribute getDeepLink_Attribute(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		deeplink.proxies.Attribute result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DeepLink_Attribute.toString());
		if (identifier != null)
			result = deeplink.proxies.Attribute.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DeepLink_Attribute
	 * @param deeplink_attribute
	 */
	public final void setDeepLink_Attribute(deeplink.proxies.Attribute deeplink_attribute)
	{
		setDeepLink_Attribute(getContext(), deeplink_attribute);
	}

	/**
	 * Set value of DeepLink_Attribute
	 * @param context
	 * @param deeplink_attribute
	 */
	public final void setDeepLink_Attribute(com.mendix.systemwideinterfaces.core.IContext context, deeplink.proxies.Attribute deeplink_attribute)
	{
		if (deeplink_attribute == null)
			getMendixObject().setValue(context, MemberNames.DeepLink_Attribute.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DeepLink_Attribute.toString(), deeplink_attribute.getMendixObject().getId());
	}

	/**
	 * @return value of DeepLink_Language
	 */
	public final system.proxies.Language getDeepLink_Language() throws com.mendix.core.CoreException
	{
		return getDeepLink_Language(getContext());
	}

	/**
	 * @param context
	 * @return value of DeepLink_Language
	 */
	public final system.proxies.Language getDeepLink_Language(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Language result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DeepLink_Language.toString());
		if (identifier != null)
			result = system.proxies.Language.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DeepLink_Language
	 * @param deeplink_language
	 */
	public final void setDeepLink_Language(system.proxies.Language deeplink_language)
	{
		setDeepLink_Language(getContext(), deeplink_language);
	}

	/**
	 * Set value of DeepLink_Language
	 * @param context
	 * @param deeplink_language
	 */
	public final void setDeepLink_Language(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Language deeplink_language)
	{
		if (deeplink_language == null)
			getMendixObject().setValue(context, MemberNames.DeepLink_Language.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DeepLink_Language.toString(), deeplink_language.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return deepLinkMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final deeplink.proxies.DeepLink that = (deeplink.proxies.DeepLink) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DeepLink.DeepLink";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
