// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cssflexgrid.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the CssFlexGrid module
	public static java.util.List<cssflexgrid.proxies.Record> dSL_Record_Generate100Records(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("CssFlexGrid.DSL_Record_Generate100Records").withParams(params).execute(context);
		java.util.List<cssflexgrid.proxies.Record> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(cssflexgrid.proxies.Record.initialize(context, obj));
		}
		return result;
	}
}