// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datahubio_countrycodes.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DataHubIo_CountryCodes module
	public static void aCT_CountryCodes_Update(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DataHubIo_CountryCodes.ACT_CountryCodes_Update").withParams(params).execute(context);
	}
	public static datahubio_countrycodes.proxies.CountryFlag countryFlag_Ensure_CWF(IContext context, datahubio_countrycodes.proxies.CountryCode _countryCode)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CountryCode", _countryCode == null ? null : _countryCode.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DataHubIo_CountryCodes.CountryFlag_Ensure_CWF").withParams(params).execute(context);
		return result == null ? null : datahubio_countrycodes.proxies.CountryFlag.initialize(context, result);
	}
	public static datahubio_countrycodes.proxies.CountryFlag countryFlag_Ensure_Flagpedia(IContext context, datahubio_countrycodes.proxies.CountryCode _countryCode)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CountryCode", _countryCode == null ? null : _countryCode.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DataHubIo_CountryCodes.CountryFlag_Ensure_Flagpedia").withParams(params).execute(context);
		return result == null ? null : datahubio_countrycodes.proxies.CountryFlag.initialize(context, result);
	}
	public static datahubio_countrycodes.proxies.CountryFlag countryFlag_Ensure_FoTW(IContext context, datahubio_countrycodes.proxies.CountryCode _countryCode)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CountryCode", _countryCode == null ? null : _countryCode.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DataHubIo_CountryCodes.CountryFlag_Ensure_FoTW").withParams(params).execute(context);
		return result == null ? null : datahubio_countrycodes.proxies.CountryFlag.initialize(context, result);
	}
	public static datahubio_countrycodes.proxies.CountryFlag countryFlag_Ensure_FoTW_2(IContext context, datahubio_countrycodes.proxies.CountryCode _countryCode)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CountryCode", _countryCode == null ? null : _countryCode.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DataHubIo_CountryCodes.CountryFlag_Ensure_FoTW_2").withParams(params).execute(context);
		return result == null ? null : datahubio_countrycodes.proxies.CountryFlag.initialize(context, result);
	}
	public static datahubio_countrycodes.proxies.CountryCode getCountryCode(IContext context, java.lang.String _iSO3166_1_Alpha_2, java.lang.String _iSO3166_1_Alpha_3)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ISO3166_1_Alpha_2", _iSO3166_1_Alpha_2);
		params.put("ISO3166_1_Alpha_3", _iSO3166_1_Alpha_3);
		IMendixObject result = (IMendixObject)Core.microflowCall("DataHubIo_CountryCodes.GetCountryCode").withParams(params).execute(context);
		return result == null ? null : datahubio_countrycodes.proxies.CountryCode.initialize(context, result);
	}
	public static boolean string2Boolean(IContext context, java.lang.String _string)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("String", _string);
		return (java.lang.Boolean) Core.microflowCall("DataHubIo_CountryCodes.String2Boolean").withParams(params).execute(context);
	}
}