// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package deeplink.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the DeepLink module

	/**
	* The index page that a user will be redirected to when the deeplink request handler finishes. This pages should start the client system, which will trigger the user's home microflow, which will execute the pending link that the handler prepared. You can (for example) modify this to have deeplinks use a different styling from the rest of the system by loading a different index page.
	* Default: index.html
	*/
	public static java.lang.String getIndexPage()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DeepLink.IndexPage");
	}

	/**
	* If login is required, this constant defines where to use can enter his credentials. If empty, the default login page of the deeplink module (resources/login.html) is used. 
	* 
	* If not empty, it is assumed that after login, the user will be redirected to the deeplink again. For this reason the provided url is appended with the original deeplink.
	* 
	* For example:
	* 'https://mxid.mendix.com/login?a=MyApp&f=true&cont='
	* or
	* '../sso/login?f=true&cont='
	* 
	* Default: empty
	*/
	public static java.lang.String getLoginLocation()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DeepLink.LoginLocation");
	}

	/**
	* E.g RequesthandlerName 'link' will result in https://yourdomain.com/link/
	* 
	*/
	public static java.lang.String getRequestHandlerName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DeepLink.RequestHandlerName");
	}
}