// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package parallelexecute.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the ParallelExecute module
	public static void aCr_ParallelActionsOptions(IContext context, parallelexecute.proxies.ParallelExecuteOptions _parallelActionOptions)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ParallelActionOptions", _parallelActionOptions == null ? null : _parallelActionOptions.getMendixObject());
		Core.microflowCall("ParallelExecute.ACr_ParallelActionsOptions").withParams(params).execute(context);
	}
}