// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package appstoreappdemos.proxies;

public class GridCellStyler
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject gridCellStylerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AppstoreAppDemos.GridCellStyler";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		String("String"),
		Integer("Integer"),
		Bollejan("Bollejan"),
		Decimal("Decimal"),
		DateTime("DateTime"),
		Enumeration("Enumeration"),
		Binary("Binary");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GridCellStyler(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AppstoreAppDemos.GridCellStyler"));
	}

	protected GridCellStyler(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject gridCellStylerMendixObject)
	{
		if (gridCellStylerMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AppstoreAppDemos.GridCellStyler", gridCellStylerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AppstoreAppDemos.GridCellStyler");

		this.gridCellStylerMendixObject = gridCellStylerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GridCellStyler.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static appstoreappdemos.proxies.GridCellStyler initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return appstoreappdemos.proxies.GridCellStyler.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static appstoreappdemos.proxies.GridCellStyler initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new appstoreappdemos.proxies.GridCellStyler(context, mendixObject);
	}

	public static appstoreappdemos.proxies.GridCellStyler load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return appstoreappdemos.proxies.GridCellStyler.initialize(context, mendixObject);
	}

	public static java.util.List<appstoreappdemos.proxies.GridCellStyler> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<appstoreappdemos.proxies.GridCellStyler> result = new java.util.ArrayList<appstoreappdemos.proxies.GridCellStyler>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//AppstoreAppDemos.GridCellStyler" + xpathConstraint))
			result.add(appstoreappdemos.proxies.GridCellStyler.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of String
	 */
	public final java.lang.String getString()
	{
		return getString(getContext());
	}

	/**
	 * @param context
	 * @return value of String
	 */
	public final java.lang.String getString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.String.toString());
	}

	/**
	 * Set value of String
	 * @param string
	 */
	public final void setString(java.lang.String string)
	{
		setString(getContext(), string);
	}

	/**
	 * Set value of String
	 * @param context
	 * @param string
	 */
	public final void setString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String string)
	{
		getMendixObject().setValue(context, MemberNames.String.toString(), string);
	}

	/**
	 * @return value of Integer
	 */
	public final java.lang.Integer getInteger()
	{
		return getInteger(getContext());
	}

	/**
	 * @param context
	 * @return value of Integer
	 */
	public final java.lang.Integer getInteger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Integer.toString());
	}

	/**
	 * Set value of Integer
	 * @param integer
	 */
	public final void setInteger(java.lang.Integer integer)
	{
		setInteger(getContext(), integer);
	}

	/**
	 * Set value of Integer
	 * @param context
	 * @param integer
	 */
	public final void setInteger(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer integer)
	{
		getMendixObject().setValue(context, MemberNames.Integer.toString(), integer);
	}

	/**
	 * @return value of Bollejan
	 */
	public final java.lang.Boolean getBollejan()
	{
		return getBollejan(getContext());
	}

	/**
	 * @param context
	 * @return value of Bollejan
	 */
	public final java.lang.Boolean getBollejan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Bollejan.toString());
	}

	/**
	 * Set value of Bollejan
	 * @param bollejan
	 */
	public final void setBollejan(java.lang.Boolean bollejan)
	{
		setBollejan(getContext(), bollejan);
	}

	/**
	 * Set value of Bollejan
	 * @param context
	 * @param bollejan
	 */
	public final void setBollejan(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean bollejan)
	{
		getMendixObject().setValue(context, MemberNames.Bollejan.toString(), bollejan);
	}

	/**
	 * @return value of Decimal
	 */
	public final java.math.BigDecimal getDecimal()
	{
		return getDecimal(getContext());
	}

	/**
	 * @param context
	 * @return value of Decimal
	 */
	public final java.math.BigDecimal getDecimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Decimal.toString());
	}

	/**
	 * Set value of Decimal
	 * @param decimal
	 */
	public final void setDecimal(java.math.BigDecimal decimal)
	{
		setDecimal(getContext(), decimal);
	}

	/**
	 * Set value of Decimal
	 * @param context
	 * @param decimal
	 */
	public final void setDecimal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal decimal)
	{
		getMendixObject().setValue(context, MemberNames.Decimal.toString(), decimal);
	}

	/**
	 * @return value of DateTime
	 */
	public final java.util.Date getDateTime()
	{
		return getDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTime
	 */
	public final java.util.Date getDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTime.toString());
	}

	/**
	 * Set value of DateTime
	 * @param datetime
	 */
	public final void setDateTime(java.util.Date datetime)
	{
		setDateTime(getContext(), datetime);
	}

	/**
	 * Set value of DateTime
	 * @param context
	 * @param datetime
	 */
	public final void setDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetime)
	{
		getMendixObject().setValue(context, MemberNames.DateTime.toString(), datetime);
	}

	/**
	 * Set value of Enumeration
	 * @param enumeration
	 */
	public final appstoreappdemos.proxies.Enum_Any getEnumeration()
	{
		return getEnumeration(getContext());
	}

	/**
	 * @param context
	 * @return value of Enumeration
	 */
	public final appstoreappdemos.proxies.Enum_Any getEnumeration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Enumeration.toString());
		if (obj == null)
			return null;

		return appstoreappdemos.proxies.Enum_Any.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Enumeration
	 * @param enumeration
	 */
	public final void setEnumeration(appstoreappdemos.proxies.Enum_Any enumeration)
	{
		setEnumeration(getContext(), enumeration);
	}

	/**
	 * Set value of Enumeration
	 * @param context
	 * @param enumeration
	 */
	public final void setEnumeration(com.mendix.systemwideinterfaces.core.IContext context, appstoreappdemos.proxies.Enum_Any enumeration)
	{
		if (enumeration != null)
			getMendixObject().setValue(context, MemberNames.Enumeration.toString(), enumeration.toString());
		else
			getMendixObject().setValue(context, MemberNames.Enumeration.toString(), null);
	}

	/**
	  * The contents of the binary field will be written to the output stream.
	  * The output stream will be closed at the end.
	  *
	  * @param context
	  * @param outputStream
	  */
	public final void getBinary(com.mendix.systemwideinterfaces.core.IContext context, java.io.OutputStream outputStream)
	{
		com.mendix.core.objectmanagement.member.MendixBinary binary = (com.mendix.core.objectmanagement.member.MendixBinary) getMendixObject().getMember(context, MemberNames.Binary.toString());
		binary.retrieveValue(context, outputStream);
	}

	/**
	  * Stores the bytes from the given InputStream.
	  *
	  * Please note that the input stream will be immediately sent to the data store,
	  * whether you commit the Mendix object or not.
	  *
	  * @param context
	  * @param inputStream
	  * @param length the number of bytes in the stream
	  */
	public final void setBinary(com.mendix.systemwideinterfaces.core.IContext context, java.io.InputStream inputStream, long length)
	{
		if (getMendixObject().getState() == com.mendix.systemwideinterfaces.core.IMendixObject.ObjectState.INSTANTIATED)
			try { commit(); } catch (com.mendix.core.CoreException ex) { }
		com.mendix.core.objectmanagement.member.MendixBinary binary = (com.mendix.core.objectmanagement.member.MendixBinary) getMendixObject().getMember(context, MemberNames.Binary.toString());
		binary.storeValue(context, inputStream, length);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return gridCellStylerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final appstoreappdemos.proxies.GridCellStyler that = (appstoreappdemos.proxies.GridCellStyler) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AppstoreAppDemos.GridCellStyler";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
