// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package appstoreappdemos.proxies;

/**
 * Testing barcode
 */
public class MyBarcode extends barcode.proxies.Barcode
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AppstoreAppDemos.MyBarcode";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BarcodeType("BarcodeType"),
		EAN("EAN"),
		showBarcodeText("showBarcodeText"),
		orientation("orientation"),
		heightMultiplier("heightMultiplier"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		MyThing_MyBarcode("AppstoreAppDemos.MyThing_MyBarcode");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MyBarcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AppstoreAppDemos.MyBarcode"));
	}

	protected MyBarcode(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject myBarcodeMendixObject)
	{
		super(context, myBarcodeMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("AppstoreAppDemos.MyBarcode", myBarcodeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AppstoreAppDemos.MyBarcode");
	}

	/**
	 * @deprecated Use 'MyBarcode.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static appstoreappdemos.proxies.MyBarcode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return appstoreappdemos.proxies.MyBarcode.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static appstoreappdemos.proxies.MyBarcode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new appstoreappdemos.proxies.MyBarcode(context, mendixObject);
	}

	public static appstoreappdemos.proxies.MyBarcode load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return appstoreappdemos.proxies.MyBarcode.initialize(context, mendixObject);
	}

	public static java.util.List<appstoreappdemos.proxies.MyBarcode> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<appstoreappdemos.proxies.MyBarcode> result = new java.util.ArrayList<appstoreappdemos.proxies.MyBarcode>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//AppstoreAppDemos.MyBarcode" + xpathConstraint))
			result.add(appstoreappdemos.proxies.MyBarcode.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of MyThing_MyBarcode
	 */
	public final appstoreappdemos.proxies.MyThing getMyThing_MyBarcode() throws com.mendix.core.CoreException
	{
		return getMyThing_MyBarcode(getContext());
	}

	/**
	 * @param context
	 * @return value of MyThing_MyBarcode
	 */
	public final appstoreappdemos.proxies.MyThing getMyThing_MyBarcode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		appstoreappdemos.proxies.MyThing result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MyThing_MyBarcode.toString());
		if (identifier != null)
			result = appstoreappdemos.proxies.MyThing.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MyThing_MyBarcode
	 * @param mything_mybarcode
	 */
	public final void setMyThing_MyBarcode(appstoreappdemos.proxies.MyThing mything_mybarcode)
	{
		setMyThing_MyBarcode(getContext(), mything_mybarcode);
	}

	/**
	 * Set value of MyThing_MyBarcode
	 * @param context
	 * @param mything_mybarcode
	 */
	public final void setMyThing_MyBarcode(com.mendix.systemwideinterfaces.core.IContext context, appstoreappdemos.proxies.MyThing mything_mybarcode)
	{
		if (mything_mybarcode == null)
			getMendixObject().setValue(context, MemberNames.MyThing_MyBarcode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MyThing_MyBarcode.toString(), mything_mybarcode.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final appstoreappdemos.proxies.MyBarcode that = (appstoreappdemos.proxies.MyBarcode) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AppstoreAppDemos.MyBarcode";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
