// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package appstoreappdemos.proxies;

/**
 * Compared in integers
 */
public class Temperature
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject temperatureMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AppstoreAppDemos.Temperature";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Celsius("Celsius"),
		Fahrenheit("Fahrenheit"),
		Kelvin("Kelvin"),
		Rankine("Rankine"),
		Reamure("Reamure");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Temperature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AppstoreAppDemos.Temperature"));
	}

	protected Temperature(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject temperatureMendixObject)
	{
		if (temperatureMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AppstoreAppDemos.Temperature", temperatureMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AppstoreAppDemos.Temperature");

		this.temperatureMendixObject = temperatureMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Temperature.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static appstoreappdemos.proxies.Temperature initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return appstoreappdemos.proxies.Temperature.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static appstoreappdemos.proxies.Temperature initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new appstoreappdemos.proxies.Temperature(context, mendixObject);
	}

	public static appstoreappdemos.proxies.Temperature load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return appstoreappdemos.proxies.Temperature.initialize(context, mendixObject);
	}

	public static java.util.List<appstoreappdemos.proxies.Temperature> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<appstoreappdemos.proxies.Temperature> result = new java.util.ArrayList<appstoreappdemos.proxies.Temperature>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//AppstoreAppDemos.Temperature" + xpathConstraint))
			result.add(appstoreappdemos.proxies.Temperature.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Celsius
	 */
	public final java.lang.Integer getCelsius()
	{
		return getCelsius(getContext());
	}

	/**
	 * @param context
	 * @return value of Celsius
	 */
	public final java.lang.Integer getCelsius(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Celsius.toString());
	}

	/**
	 * Set value of Celsius
	 * @param celsius
	 */
	public final void setCelsius(java.lang.Integer celsius)
	{
		setCelsius(getContext(), celsius);
	}

	/**
	 * Set value of Celsius
	 * @param context
	 * @param celsius
	 */
	public final void setCelsius(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer celsius)
	{
		getMendixObject().setValue(context, MemberNames.Celsius.toString(), celsius);
	}

	/**
	 * @return value of Fahrenheit
	 */
	public final java.lang.Integer getFahrenheit()
	{
		return getFahrenheit(getContext());
	}

	/**
	 * @param context
	 * @return value of Fahrenheit
	 */
	public final java.lang.Integer getFahrenheit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Fahrenheit.toString());
	}

	/**
	 * Set value of Fahrenheit
	 * @param fahrenheit
	 */
	public final void setFahrenheit(java.lang.Integer fahrenheit)
	{
		setFahrenheit(getContext(), fahrenheit);
	}

	/**
	 * Set value of Fahrenheit
	 * @param context
	 * @param fahrenheit
	 */
	public final void setFahrenheit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer fahrenheit)
	{
		getMendixObject().setValue(context, MemberNames.Fahrenheit.toString(), fahrenheit);
	}

	/**
	 * @return value of Kelvin
	 */
	public final java.lang.Integer getKelvin()
	{
		return getKelvin(getContext());
	}

	/**
	 * @param context
	 * @return value of Kelvin
	 */
	public final java.lang.Integer getKelvin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Kelvin.toString());
	}

	/**
	 * Set value of Kelvin
	 * @param kelvin
	 */
	public final void setKelvin(java.lang.Integer kelvin)
	{
		setKelvin(getContext(), kelvin);
	}

	/**
	 * Set value of Kelvin
	 * @param context
	 * @param kelvin
	 */
	public final void setKelvin(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer kelvin)
	{
		getMendixObject().setValue(context, MemberNames.Kelvin.toString(), kelvin);
	}

	/**
	 * @return value of Rankine
	 */
	public final java.lang.Integer getRankine()
	{
		return getRankine(getContext());
	}

	/**
	 * @param context
	 * @return value of Rankine
	 */
	public final java.lang.Integer getRankine(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Rankine.toString());
	}

	/**
	 * Set value of Rankine
	 * @param rankine
	 */
	public final void setRankine(java.lang.Integer rankine)
	{
		setRankine(getContext(), rankine);
	}

	/**
	 * Set value of Rankine
	 * @param context
	 * @param rankine
	 */
	public final void setRankine(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer rankine)
	{
		getMendixObject().setValue(context, MemberNames.Rankine.toString(), rankine);
	}

	/**
	 * @return value of Reamure
	 */
	public final java.lang.Integer getReamure()
	{
		return getReamure(getContext());
	}

	/**
	 * @param context
	 * @return value of Reamure
	 */
	public final java.lang.Integer getReamure(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Reamure.toString());
	}

	/**
	 * Set value of Reamure
	 * @param reamure
	 */
	public final void setReamure(java.lang.Integer reamure)
	{
		setReamure(getContext(), reamure);
	}

	/**
	 * Set value of Reamure
	 * @param context
	 * @param reamure
	 */
	public final void setReamure(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer reamure)
	{
		getMendixObject().setValue(context, MemberNames.Reamure.toString(), reamure);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return temperatureMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final appstoreappdemos.proxies.Temperature that = (appstoreappdemos.proxies.Temperature) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AppstoreAppDemos.Temperature";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
