// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package appstoreappdemos.proxies;

/**
 * A webcam that is showing images of some sort, preferably streaming.
 */
public class Webcam
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject webcamMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AppstoreAppDemos.Webcam";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Source("Source"),
		UrlOrId("UrlOrId"),
		ImageUrl("ImageUrl"),
		Quality("Quality"),
		UpSince("UpSince"),
		Picturetype("Picturetype"),
		Base64Image("Base64Image"),
		Webcam_Image("AppstoreAppDemos.Webcam_Image"),
		Label_Webcam("AppstoreAppDemos.Label_Webcam");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Webcam(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AppstoreAppDemos.Webcam"));
	}

	protected Webcam(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject webcamMendixObject)
	{
		if (webcamMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AppstoreAppDemos.Webcam", webcamMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AppstoreAppDemos.Webcam");

		this.webcamMendixObject = webcamMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Webcam.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static appstoreappdemos.proxies.Webcam initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return appstoreappdemos.proxies.Webcam.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static appstoreappdemos.proxies.Webcam initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new appstoreappdemos.proxies.Webcam(context, mendixObject);
	}

	public static appstoreappdemos.proxies.Webcam load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return appstoreappdemos.proxies.Webcam.initialize(context, mendixObject);
	}

	public static java.util.List<appstoreappdemos.proxies.Webcam> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<appstoreappdemos.proxies.Webcam> result = new java.util.ArrayList<appstoreappdemos.proxies.Webcam>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//AppstoreAppDemos.Webcam" + xpathConstraint))
			result.add(appstoreappdemos.proxies.Webcam.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * Set value of Source
	 * @param source
	 */
	public final appstoreappdemos.proxies.Enum_VideoSource getSource()
	{
		return getSource(getContext());
	}

	/**
	 * @param context
	 * @return value of Source
	 */
	public final appstoreappdemos.proxies.Enum_VideoSource getSource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Source.toString());
		if (obj == null)
			return null;

		return appstoreappdemos.proxies.Enum_VideoSource.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Source
	 * @param source
	 */
	public final void setSource(appstoreappdemos.proxies.Enum_VideoSource source)
	{
		setSource(getContext(), source);
	}

	/**
	 * Set value of Source
	 * @param context
	 * @param source
	 */
	public final void setSource(com.mendix.systemwideinterfaces.core.IContext context, appstoreappdemos.proxies.Enum_VideoSource source)
	{
		if (source != null)
			getMendixObject().setValue(context, MemberNames.Source.toString(), source.toString());
		else
			getMendixObject().setValue(context, MemberNames.Source.toString(), null);
	}

	/**
	 * @return value of UrlOrId
	 */
	public final java.lang.String getUrlOrId()
	{
		return getUrlOrId(getContext());
	}

	/**
	 * @param context
	 * @return value of UrlOrId
	 */
	public final java.lang.String getUrlOrId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UrlOrId.toString());
	}

	/**
	 * Set value of UrlOrId
	 * @param urlorid
	 */
	public final void setUrlOrId(java.lang.String urlorid)
	{
		setUrlOrId(getContext(), urlorid);
	}

	/**
	 * Set value of UrlOrId
	 * @param context
	 * @param urlorid
	 */
	public final void setUrlOrId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String urlorid)
	{
		getMendixObject().setValue(context, MemberNames.UrlOrId.toString(), urlorid);
	}

	/**
	 * @return value of ImageUrl
	 */
	public final java.lang.String getImageUrl()
	{
		return getImageUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageUrl
	 */
	public final java.lang.String getImageUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImageUrl.toString());
	}

	/**
	 * Set value of ImageUrl
	 * @param imageurl
	 */
	public final void setImageUrl(java.lang.String imageurl)
	{
		setImageUrl(getContext(), imageurl);
	}

	/**
	 * Set value of ImageUrl
	 * @param context
	 * @param imageurl
	 */
	public final void setImageUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imageurl)
	{
		getMendixObject().setValue(context, MemberNames.ImageUrl.toString(), imageurl);
	}

	/**
	 * @return value of Quality
	 */
	public final java.lang.Integer getQuality()
	{
		return getQuality(getContext());
	}

	/**
	 * @param context
	 * @return value of Quality
	 */
	public final java.lang.Integer getQuality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Quality.toString());
	}

	/**
	 * Set value of Quality
	 * @param quality
	 */
	public final void setQuality(java.lang.Integer quality)
	{
		setQuality(getContext(), quality);
	}

	/**
	 * Set value of Quality
	 * @param context
	 * @param quality
	 */
	public final void setQuality(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quality)
	{
		getMendixObject().setValue(context, MemberNames.Quality.toString(), quality);
	}

	/**
	 * @return value of UpSince
	 */
	public final java.util.Date getUpSince()
	{
		return getUpSince(getContext());
	}

	/**
	 * @param context
	 * @return value of UpSince
	 */
	public final java.util.Date getUpSince(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.UpSince.toString());
	}

	/**
	 * Set value of UpSince
	 * @param upsince
	 */
	public final void setUpSince(java.util.Date upsince)
	{
		setUpSince(getContext(), upsince);
	}

	/**
	 * Set value of UpSince
	 * @param context
	 * @param upsince
	 */
	public final void setUpSince(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date upsince)
	{
		getMendixObject().setValue(context, MemberNames.UpSince.toString(), upsince);
	}

	/**
	 * Set value of Picturetype
	 * @param picturetype
	 */
	public final appstoreappdemos.proxies.Enum_PictureType getPicturetype()
	{
		return getPicturetype(getContext());
	}

	/**
	 * @param context
	 * @return value of Picturetype
	 */
	public final appstoreappdemos.proxies.Enum_PictureType getPicturetype(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Picturetype.toString());
		if (obj == null)
			return null;

		return appstoreappdemos.proxies.Enum_PictureType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Picturetype
	 * @param picturetype
	 */
	public final void setPicturetype(appstoreappdemos.proxies.Enum_PictureType picturetype)
	{
		setPicturetype(getContext(), picturetype);
	}

	/**
	 * Set value of Picturetype
	 * @param context
	 * @param picturetype
	 */
	public final void setPicturetype(com.mendix.systemwideinterfaces.core.IContext context, appstoreappdemos.proxies.Enum_PictureType picturetype)
	{
		if (picturetype != null)
			getMendixObject().setValue(context, MemberNames.Picturetype.toString(), picturetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.Picturetype.toString(), null);
	}

	/**
	 * @return value of Base64Image
	 */
	public final java.lang.String getBase64Image()
	{
		return getBase64Image(getContext());
	}

	/**
	 * @param context
	 * @return value of Base64Image
	 */
	public final java.lang.String getBase64Image(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Base64Image.toString());
	}

	/**
	 * Set value of Base64Image
	 * @param base64image
	 */
	public final void setBase64Image(java.lang.String base64image)
	{
		setBase64Image(getContext(), base64image);
	}

	/**
	 * Set value of Base64Image
	 * @param context
	 * @param base64image
	 */
	public final void setBase64Image(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String base64image)
	{
		getMendixObject().setValue(context, MemberNames.Base64Image.toString(), base64image);
	}

	/**
	 * @return value of Webcam_Image
	 */
	public final appstoreappdemos.proxies.Image getWebcam_Image() throws com.mendix.core.CoreException
	{
		return getWebcam_Image(getContext());
	}

	/**
	 * @param context
	 * @return value of Webcam_Image
	 */
	public final appstoreappdemos.proxies.Image getWebcam_Image(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		appstoreappdemos.proxies.Image result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Webcam_Image.toString());
		if (identifier != null)
			result = appstoreappdemos.proxies.Image.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Webcam_Image
	 * @param webcam_image
	 */
	public final void setWebcam_Image(appstoreappdemos.proxies.Image webcam_image)
	{
		setWebcam_Image(getContext(), webcam_image);
	}

	/**
	 * Set value of Webcam_Image
	 * @param context
	 * @param webcam_image
	 */
	public final void setWebcam_Image(com.mendix.systemwideinterfaces.core.IContext context, appstoreappdemos.proxies.Image webcam_image)
	{
		if (webcam_image == null)
			getMendixObject().setValue(context, MemberNames.Webcam_Image.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Webcam_Image.toString(), webcam_image.getMendixObject().getId());
	}

	/**
	 * @return value of Label_Webcam
	 */
	public final java.util.List<appstoreappdemos.proxies.Label> getLabel_Webcam() throws com.mendix.core.CoreException
	{
		return getLabel_Webcam(getContext());
	}

	/**
	 * @param context
	 * @return value of Label_Webcam
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<appstoreappdemos.proxies.Label> getLabel_Webcam(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<appstoreappdemos.proxies.Label> result = new java.util.ArrayList<appstoreappdemos.proxies.Label>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Label_Webcam.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(appstoreappdemos.proxies.Label.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Label_Webcam
	 * @param label_webcam
	 */
	public final void setLabel_Webcam(java.util.List<appstoreappdemos.proxies.Label> label_webcam)
	{
		setLabel_Webcam(getContext(), label_webcam);
	}

	/**
	 * Set value of Label_Webcam
	 * @param context
	 * @param label_webcam
	 */
	public final void setLabel_Webcam(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<appstoreappdemos.proxies.Label> label_webcam)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (appstoreappdemos.proxies.Label proxyObject : label_webcam)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Label_Webcam.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return webcamMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final appstoreappdemos.proxies.Webcam that = (appstoreappdemos.proxies.Webcam) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AppstoreAppDemos.Webcam";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
