// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} webcamurl
 * @returns {Promise.<boolean>}
 */
export async function JaA_IfOtherStreamThenSetStream(webcamurl) {
	// BEGIN USER CODE
	// Find the DOM-element containing the Videoplayback 
	console.log('Ran JaA_IfOtherStreamThenSetStream from MicroflowTimer');
	var videoIframe = document.querySelector(".mx-name-audioVideoPlaybackEmbedVariable iframe");
	if (typeof videoIframe == 'object' && videoIframe !== null) {
		// If the DOM-element has a different src compared to the webcamurl, then set it's src to the webcamurl
		if (videoIframe.src != webcamurl) {
			(videoIframe.src = webcamurl); 
		}
	}
	// END USER CODE
}
