// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<boolean>}
 */
export async function JaA_StartShowingDeviceWebcam() {
	// BEGIN USER CODE
	var video = document.querySelector("#UsersDeviceCamera");
	if (navigator.mediaDevices.getUserMedia) {
        navigator.mediaDevices.getUserMedia({ video : true })
            .then(function (stream) {
            video.srcObject = stream;
            })
            .catch(function (error) {
            console.log("Something went wrong!");
            });
	}
	// END USER CODE
}
