// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Moves a sprite
 * @returns {Promise.<void>}
 */
export async function JS_movesprite_running() {
	// BEGIN USER CODE
	let image = new Image();
	image.src = "/resources/running.png";
	let counter = 0,
      frame_width = 78,
      frame_height = 71;
	image.onload = function() {
		let canvas = document.getElementById('myCanvas');
		let context = canvas.getContext("2d");
		window.requestAnimationFrame(animate);
		
		function animate() {
			let frame = Math.floor(counter % 6);
			context.drawImage(image, frame * frame_width, 0, frame_width, frame_height, 0, 0, frame_width, frame_height);
			counter = counter + .25;
			
			window.requestAnimationFrame(animate);
		}
	}
	// let newxpos = -77;
	// sprite.style.backgroundPosition = newxpos+"px 0px";
	// return;
	// let currentx = sprite.style.background-position-x;
	// console.log(currentx);
	// let spriteWidth = 77; 
	// let newx = (currentx + spriteWidth) % spriteWidth; 
	// console.log(newx);
	// sprite.style.backgroundPosition = newx+"px 0px";
	// END USER CODE
}
