// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prettyenumerations.proxies;

/**
 * Just to demo the enumerations in a datagrid
 */
public class Demo
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject demoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PrettyEnumerations.Demo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Color("Color"),
		Coordinate("Coordinate"),
		Direction("Direction"),
		EncryptionKey("EncryptionKey"),
		EnvironmentType("EnvironmentType"),
		OnOff("OnOff"),
		Trafficlight("Trafficlight"),
		TrueFalse("TrueFalse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Demo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PrettyEnumerations.Demo"));
	}

	protected Demo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject demoMendixObject)
	{
		if (demoMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PrettyEnumerations.Demo", demoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PrettyEnumerations.Demo");

		this.demoMendixObject = demoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Demo.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static prettyenumerations.proxies.Demo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return prettyenumerations.proxies.Demo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static prettyenumerations.proxies.Demo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new prettyenumerations.proxies.Demo(context, mendixObject);
	}

	public static prettyenumerations.proxies.Demo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return prettyenumerations.proxies.Demo.initialize(context, mendixObject);
	}

	public static java.util.List<prettyenumerations.proxies.Demo> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<prettyenumerations.proxies.Demo> result = new java.util.ArrayList<prettyenumerations.proxies.Demo>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PrettyEnumerations.Demo" + xpathConstraint))
			result.add(prettyenumerations.proxies.Demo.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Color
	 * @param color
	 */
	public final prettyenumerations.proxies.Enum_Color getColor()
	{
		return getColor(getContext());
	}

	/**
	 * @param context
	 * @return value of Color
	 */
	public final prettyenumerations.proxies.Enum_Color getColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Color.toString());
		if (obj == null)
			return null;

		return prettyenumerations.proxies.Enum_Color.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Color
	 * @param color
	 */
	public final void setColor(prettyenumerations.proxies.Enum_Color color)
	{
		setColor(getContext(), color);
	}

	/**
	 * Set value of Color
	 * @param context
	 * @param color
	 */
	public final void setColor(com.mendix.systemwideinterfaces.core.IContext context, prettyenumerations.proxies.Enum_Color color)
	{
		if (color != null)
			getMendixObject().setValue(context, MemberNames.Color.toString(), color.toString());
		else
			getMendixObject().setValue(context, MemberNames.Color.toString(), null);
	}

	/**
	 * Set value of Coordinate
	 * @param coordinate
	 */
	public final prettyenumerations.proxies.Enum_CoordinateType getCoordinate()
	{
		return getCoordinate(getContext());
	}

	/**
	 * @param context
	 * @return value of Coordinate
	 */
	public final prettyenumerations.proxies.Enum_CoordinateType getCoordinate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Coordinate.toString());
		if (obj == null)
			return null;

		return prettyenumerations.proxies.Enum_CoordinateType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Coordinate
	 * @param coordinate
	 */
	public final void setCoordinate(prettyenumerations.proxies.Enum_CoordinateType coordinate)
	{
		setCoordinate(getContext(), coordinate);
	}

	/**
	 * Set value of Coordinate
	 * @param context
	 * @param coordinate
	 */
	public final void setCoordinate(com.mendix.systemwideinterfaces.core.IContext context, prettyenumerations.proxies.Enum_CoordinateType coordinate)
	{
		if (coordinate != null)
			getMendixObject().setValue(context, MemberNames.Coordinate.toString(), coordinate.toString());
		else
			getMendixObject().setValue(context, MemberNames.Coordinate.toString(), null);
	}

	/**
	 * Set value of Direction
	 * @param direction
	 */
	public final prettyenumerations.proxies.Enum_Direction getDirection()
	{
		return getDirection(getContext());
	}

	/**
	 * @param context
	 * @return value of Direction
	 */
	public final prettyenumerations.proxies.Enum_Direction getDirection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Direction.toString());
		if (obj == null)
			return null;

		return prettyenumerations.proxies.Enum_Direction.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Direction
	 * @param direction
	 */
	public final void setDirection(prettyenumerations.proxies.Enum_Direction direction)
	{
		setDirection(getContext(), direction);
	}

	/**
	 * Set value of Direction
	 * @param context
	 * @param direction
	 */
	public final void setDirection(com.mendix.systemwideinterfaces.core.IContext context, prettyenumerations.proxies.Enum_Direction direction)
	{
		if (direction != null)
			getMendixObject().setValue(context, MemberNames.Direction.toString(), direction.toString());
		else
			getMendixObject().setValue(context, MemberNames.Direction.toString(), null);
	}

	/**
	 * Set value of EncryptionKey
	 * @param encryptionkey
	 */
	public final prettyenumerations.proxies.Enum_EncryptionKey getEncryptionKey()
	{
		return getEncryptionKey(getContext());
	}

	/**
	 * @param context
	 * @return value of EncryptionKey
	 */
	public final prettyenumerations.proxies.Enum_EncryptionKey getEncryptionKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EncryptionKey.toString());
		if (obj == null)
			return null;

		return prettyenumerations.proxies.Enum_EncryptionKey.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EncryptionKey
	 * @param encryptionkey
	 */
	public final void setEncryptionKey(prettyenumerations.proxies.Enum_EncryptionKey encryptionkey)
	{
		setEncryptionKey(getContext(), encryptionkey);
	}

	/**
	 * Set value of EncryptionKey
	 * @param context
	 * @param encryptionkey
	 */
	public final void setEncryptionKey(com.mendix.systemwideinterfaces.core.IContext context, prettyenumerations.proxies.Enum_EncryptionKey encryptionkey)
	{
		if (encryptionkey != null)
			getMendixObject().setValue(context, MemberNames.EncryptionKey.toString(), encryptionkey.toString());
		else
			getMendixObject().setValue(context, MemberNames.EncryptionKey.toString(), null);
	}

	/**
	 * Set value of EnvironmentType
	 * @param environmenttype
	 */
	public final prettyenumerations.proxies.Enum_EnvironmentType getEnvironmentType()
	{
		return getEnvironmentType(getContext());
	}

	/**
	 * @param context
	 * @return value of EnvironmentType
	 */
	public final prettyenumerations.proxies.Enum_EnvironmentType getEnvironmentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EnvironmentType.toString());
		if (obj == null)
			return null;

		return prettyenumerations.proxies.Enum_EnvironmentType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EnvironmentType
	 * @param environmenttype
	 */
	public final void setEnvironmentType(prettyenumerations.proxies.Enum_EnvironmentType environmenttype)
	{
		setEnvironmentType(getContext(), environmenttype);
	}

	/**
	 * Set value of EnvironmentType
	 * @param context
	 * @param environmenttype
	 */
	public final void setEnvironmentType(com.mendix.systemwideinterfaces.core.IContext context, prettyenumerations.proxies.Enum_EnvironmentType environmenttype)
	{
		if (environmenttype != null)
			getMendixObject().setValue(context, MemberNames.EnvironmentType.toString(), environmenttype.toString());
		else
			getMendixObject().setValue(context, MemberNames.EnvironmentType.toString(), null);
	}

	/**
	 * Set value of OnOff
	 * @param onoff
	 */
	public final prettyenumerations.proxies.Enum_OnOff getOnOff()
	{
		return getOnOff(getContext());
	}

	/**
	 * @param context
	 * @return value of OnOff
	 */
	public final prettyenumerations.proxies.Enum_OnOff getOnOff(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.OnOff.toString());
		if (obj == null)
			return null;

		return prettyenumerations.proxies.Enum_OnOff.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of OnOff
	 * @param onoff
	 */
	public final void setOnOff(prettyenumerations.proxies.Enum_OnOff onoff)
	{
		setOnOff(getContext(), onoff);
	}

	/**
	 * Set value of OnOff
	 * @param context
	 * @param onoff
	 */
	public final void setOnOff(com.mendix.systemwideinterfaces.core.IContext context, prettyenumerations.proxies.Enum_OnOff onoff)
	{
		if (onoff != null)
			getMendixObject().setValue(context, MemberNames.OnOff.toString(), onoff.toString());
		else
			getMendixObject().setValue(context, MemberNames.OnOff.toString(), null);
	}

	/**
	 * Set value of Trafficlight
	 * @param trafficlight
	 */
	public final prettyenumerations.proxies.Enum_Trafficlight getTrafficlight()
	{
		return getTrafficlight(getContext());
	}

	/**
	 * @param context
	 * @return value of Trafficlight
	 */
	public final prettyenumerations.proxies.Enum_Trafficlight getTrafficlight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Trafficlight.toString());
		if (obj == null)
			return null;

		return prettyenumerations.proxies.Enum_Trafficlight.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Trafficlight
	 * @param trafficlight
	 */
	public final void setTrafficlight(prettyenumerations.proxies.Enum_Trafficlight trafficlight)
	{
		setTrafficlight(getContext(), trafficlight);
	}

	/**
	 * Set value of Trafficlight
	 * @param context
	 * @param trafficlight
	 */
	public final void setTrafficlight(com.mendix.systemwideinterfaces.core.IContext context, prettyenumerations.proxies.Enum_Trafficlight trafficlight)
	{
		if (trafficlight != null)
			getMendixObject().setValue(context, MemberNames.Trafficlight.toString(), trafficlight.toString());
		else
			getMendixObject().setValue(context, MemberNames.Trafficlight.toString(), null);
	}

	/**
	 * Set value of TrueFalse
	 * @param truefalse
	 */
	public final prettyenumerations.proxies.Enum_TrueFalse getTrueFalse()
	{
		return getTrueFalse(getContext());
	}

	/**
	 * @param context
	 * @return value of TrueFalse
	 */
	public final prettyenumerations.proxies.Enum_TrueFalse getTrueFalse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TrueFalse.toString());
		if (obj == null)
			return null;

		return prettyenumerations.proxies.Enum_TrueFalse.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TrueFalse
	 * @param truefalse
	 */
	public final void setTrueFalse(prettyenumerations.proxies.Enum_TrueFalse truefalse)
	{
		setTrueFalse(getContext(), truefalse);
	}

	/**
	 * Set value of TrueFalse
	 * @param context
	 * @param truefalse
	 */
	public final void setTrueFalse(com.mendix.systemwideinterfaces.core.IContext context, prettyenumerations.proxies.Enum_TrueFalse truefalse)
	{
		if (truefalse != null)
			getMendixObject().setValue(context, MemberNames.TrueFalse.toString(), truefalse.toString());
		else
			getMendixObject().setValue(context, MemberNames.TrueFalse.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return demoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final prettyenumerations.proxies.Demo that = (prettyenumerations.proxies.Demo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PrettyEnumerations.Demo";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
