// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prettyenumerations.proxies;

public enum Enum_Trafficlight
{
	red(new java.lang.String[][] { new java.lang.String[] { "en_US", "" }, new java.lang.String[] { "nl_NL", "red" } }),
	yellow(new java.lang.String[][] { new java.lang.String[] { "en_US", "" }, new java.lang.String[] { "nl_NL", "yellow" } }),
	green(new java.lang.String[][] { new java.lang.String[] { "en_US", "" }, new java.lang.String[] { "nl_NL", "green" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_Trafficlight(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
