// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prettyenumerations.proxies;

public enum Enum_EnvironmentType
{
	D(new java.lang.String[][] { new java.lang.String[] { "en_US", "Development" }, new java.lang.String[] { "nl_NL", "<Development>" } }),
	T(new java.lang.String[][] { new java.lang.String[] { "en_US", "Test" }, new java.lang.String[] { "nl_NL", "<Test>" } }),
	A(new java.lang.String[][] { new java.lang.String[] { "en_US", "Acceptation" }, new java.lang.String[] { "nl_NL", "<Acceptation>" } }),
	P(new java.lang.String[][] { new java.lang.String[] { "en_US", "Production" }, new java.lang.String[] { "nl_NL", "<Production>" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_EnvironmentType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
