// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package goodies.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Goodies module
	public static void act_Experiment1_CreateABandAsso_CommitA(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Goodies.Act_Experiment1_CreateABandAsso_CommitA").withParams(params).execute(context);
	}
	public static void act_Experiment2_CreateABandAsso_CommitAandB(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Goodies.Act_Experiment2_CreateABandAsso_CommitAandB").withParams(params).execute(context);
	}
	public static void act_Experiment3_CreateABandAsso_CommitB(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Goodies.Act_Experiment3_CreateABandAsso_CommitB").withParams(params).execute(context);
	}
	public static void act_Experiment4_CreateABandAsso_CommitRefreshA(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Goodies.Act_Experiment4_CreateABandAsso_CommitRefreshA").withParams(params).execute(context);
	}
	public static void act_Experiment5_CreateABandAsso_CommitRefreshAandB(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Goodies.Act_Experiment5_CreateABandAsso_CommitRefreshAandB").withParams(params).execute(context);
	}
	public static void act_Experiment6_CreateABandAsso_CommitRefreshB(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Goodies.Act_Experiment6_CreateABandAsso_CommitRefreshB").withParams(params).execute(context);
	}
	public static void act_Experiment7_CreateA2CandAsso_CommitAandC1(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Goodies.Act_Experiment7_CreateA2CandAsso_CommitAandC1").withParams(params).execute(context);
	}
	public static void act_Experiment7_CreateA2CandAsso_CommitC1(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Goodies.Act_Experiment7_CreateA2CandAsso_CommitC1").withParams(params).execute(context);
	}
	public static void aCT_HMAC_GenerateUsingSHA1(IContext context, goodies.proxies.HMACbySHA1 _hMACbySHA1)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HMACbySHA1", _hMACbySHA1 == null ? null : _hMACbySHA1.getMendixObject());
		Core.microflowCall("Goodies.ACT_HMAC_GenerateUsingSHA1").withParams(params).execute(context);
	}
	public static goodies.proxies.HMACbySHA1 dS_HMACbySHA1(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Goodies.DS_HMACbySHA1").withParams(params).execute(context);
		return result == null ? null : goodies.proxies.HMACbySHA1.initialize(context, result);
	}
	public static void entityAandB_DeleteAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Goodies.EntityAandB_DeleteAll").withParams(params).execute(context);
	}
}