// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testjson.proxies;

public class Column
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject columnMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "testjson.Column";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Checkbox("Checkbox"),
		Column_Row("testjson.Column_Row");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Column(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "testjson.Column"));
	}

	protected Column(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject columnMendixObject)
	{
		if (columnMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("testjson.Column", columnMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a testjson.Column");

		this.columnMendixObject = columnMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Column.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testjson.proxies.Column initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testjson.proxies.Column.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testjson.proxies.Column initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testjson.proxies.Column(context, mendixObject);
	}

	public static testjson.proxies.Column load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testjson.proxies.Column.initialize(context, mendixObject);
	}

	public static java.util.List<testjson.proxies.Column> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testjson.proxies.Column> result = new java.util.ArrayList<testjson.proxies.Column>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//testjson.Column" + xpathConstraint))
			result.add(testjson.proxies.Column.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Checkbox
	 */
	public final java.lang.Boolean getCheckbox()
	{
		return getCheckbox(getContext());
	}

	/**
	 * @param context
	 * @return value of Checkbox
	 */
	public final java.lang.Boolean getCheckbox(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Checkbox.toString());
	}

	/**
	 * Set value of Checkbox
	 * @param checkbox
	 */
	public final void setCheckbox(java.lang.Boolean checkbox)
	{
		setCheckbox(getContext(), checkbox);
	}

	/**
	 * Set value of Checkbox
	 * @param context
	 * @param checkbox
	 */
	public final void setCheckbox(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean checkbox)
	{
		getMendixObject().setValue(context, MemberNames.Checkbox.toString(), checkbox);
	}

	/**
	 * @return value of Column_Row
	 */
	public final testjson.proxies.Row getColumn_Row() throws com.mendix.core.CoreException
	{
		return getColumn_Row(getContext());
	}

	/**
	 * @param context
	 * @return value of Column_Row
	 */
	public final testjson.proxies.Row getColumn_Row(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testjson.proxies.Row result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Column_Row.toString());
		if (identifier != null)
			result = testjson.proxies.Row.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Column_Row
	 * @param column_row
	 */
	public final void setColumn_Row(testjson.proxies.Row column_row)
	{
		setColumn_Row(getContext(), column_row);
	}

	/**
	 * Set value of Column_Row
	 * @param context
	 * @param column_row
	 */
	public final void setColumn_Row(com.mendix.systemwideinterfaces.core.IContext context, testjson.proxies.Row column_row)
	{
		if (column_row == null)
			getMendixObject().setValue(context, MemberNames.Column_Row.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Column_Row.toString(), column_row.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return columnMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testjson.proxies.Column that = (testjson.proxies.Column) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "testjson.Column";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
