// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testjson.proxies;

public class MyJSONObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject myJSONObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "testjson.MyJSONObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MyJSONObject_Root("testjson.MyJSONObject_Root");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MyJSONObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "testjson.MyJSONObject"));
	}

	protected MyJSONObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject myJSONObjectMendixObject)
	{
		if (myJSONObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("testjson.MyJSONObject", myJSONObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a testjson.MyJSONObject");

		this.myJSONObjectMendixObject = myJSONObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MyJSONObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testjson.proxies.MyJSONObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testjson.proxies.MyJSONObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testjson.proxies.MyJSONObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testjson.proxies.MyJSONObject(context, mendixObject);
	}

	public static testjson.proxies.MyJSONObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testjson.proxies.MyJSONObject.initialize(context, mendixObject);
	}

	public static java.util.List<testjson.proxies.MyJSONObject> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testjson.proxies.MyJSONObject> result = new java.util.ArrayList<testjson.proxies.MyJSONObject>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//testjson.MyJSONObject" + xpathConstraint))
			result.add(testjson.proxies.MyJSONObject.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MyJSONObject_Root
	 */
	public final testjson.proxies.Root getMyJSONObject_Root() throws com.mendix.core.CoreException
	{
		return getMyJSONObject_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of MyJSONObject_Root
	 */
	public final testjson.proxies.Root getMyJSONObject_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testjson.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MyJSONObject_Root.toString());
		if (identifier != null)
			result = testjson.proxies.Root.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MyJSONObject_Root
	 * @param myjsonobject_root
	 */
	public final void setMyJSONObject_Root(testjson.proxies.Root myjsonobject_root)
	{
		setMyJSONObject_Root(getContext(), myjsonobject_root);
	}

	/**
	 * Set value of MyJSONObject_Root
	 * @param context
	 * @param myjsonobject_root
	 */
	public final void setMyJSONObject_Root(com.mendix.systemwideinterfaces.core.IContext context, testjson.proxies.Root myjsonobject_root)
	{
		if (myjsonobject_root == null)
			getMendixObject().setValue(context, MemberNames.MyJSONObject_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MyJSONObject_Root.toString(), myjsonobject_root.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return myJSONObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testjson.proxies.MyJSONObject that = (testjson.proxies.MyJSONObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "testjson.MyJSONObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
