// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testjson.proxies;

public class Wrapper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject wrapperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "testjson.Wrapper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MyString("MyString"),
		Wrapper_MyJSONObject("testjson.Wrapper_MyJSONObject");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Wrapper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "testjson.Wrapper"));
	}

	protected Wrapper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject wrapperMendixObject)
	{
		if (wrapperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("testjson.Wrapper", wrapperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a testjson.Wrapper");

		this.wrapperMendixObject = wrapperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Wrapper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testjson.proxies.Wrapper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testjson.proxies.Wrapper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testjson.proxies.Wrapper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testjson.proxies.Wrapper(context, mendixObject);
	}

	public static testjson.proxies.Wrapper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testjson.proxies.Wrapper.initialize(context, mendixObject);
	}

	public static java.util.List<testjson.proxies.Wrapper> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testjson.proxies.Wrapper> result = new java.util.ArrayList<testjson.proxies.Wrapper>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//testjson.Wrapper" + xpathConstraint))
			result.add(testjson.proxies.Wrapper.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MyString
	 */
	public final java.lang.String getMyString()
	{
		return getMyString(getContext());
	}

	/**
	 * @param context
	 * @return value of MyString
	 */
	public final java.lang.String getMyString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MyString.toString());
	}

	/**
	 * Set value of MyString
	 * @param mystring
	 */
	public final void setMyString(java.lang.String mystring)
	{
		setMyString(getContext(), mystring);
	}

	/**
	 * Set value of MyString
	 * @param context
	 * @param mystring
	 */
	public final void setMyString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mystring)
	{
		getMendixObject().setValue(context, MemberNames.MyString.toString(), mystring);
	}

	/**
	 * @return value of Wrapper_MyJSONObject
	 */
	public final testjson.proxies.MyJSONObject getWrapper_MyJSONObject() throws com.mendix.core.CoreException
	{
		return getWrapper_MyJSONObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Wrapper_MyJSONObject
	 */
	public final testjson.proxies.MyJSONObject getWrapper_MyJSONObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testjson.proxies.MyJSONObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Wrapper_MyJSONObject.toString());
		if (identifier != null)
			result = testjson.proxies.MyJSONObject.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Wrapper_MyJSONObject
	 * @param wrapper_myjsonobject
	 */
	public final void setWrapper_MyJSONObject(testjson.proxies.MyJSONObject wrapper_myjsonobject)
	{
		setWrapper_MyJSONObject(getContext(), wrapper_myjsonobject);
	}

	/**
	 * Set value of Wrapper_MyJSONObject
	 * @param context
	 * @param wrapper_myjsonobject
	 */
	public final void setWrapper_MyJSONObject(com.mendix.systemwideinterfaces.core.IContext context, testjson.proxies.MyJSONObject wrapper_myjsonobject)
	{
		if (wrapper_myjsonobject == null)
			getMendixObject().setValue(context, MemberNames.Wrapper_MyJSONObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Wrapper_MyJSONObject.toString(), wrapper_myjsonobject.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return wrapperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testjson.proxies.Wrapper that = (testjson.proxies.Wrapper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "testjson.Wrapper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
