// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package charts.proxies;

/**
 * For ChartJs
 */
public class CJsDataset
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cJsDatasetMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Charts.CJsDataset";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Color("Color"),
		Label("Label"),
		Sorting("Sorting"),
		CJsDataset_SingleCJsDataPoint("Charts.CJsDataset_SingleCJsDataPoint"),
		CJsDataset_MultiCJsDataPoint("Charts.CJsDataset_MultiCJsDataPoint");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CJsDataset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Charts.CJsDataset"));
	}

	protected CJsDataset(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cJsDatasetMendixObject)
	{
		if (cJsDatasetMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Charts.CJsDataset", cJsDatasetMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Charts.CJsDataset");

		this.cJsDatasetMendixObject = cJsDatasetMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CJsDataset.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static charts.proxies.CJsDataset initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return charts.proxies.CJsDataset.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static charts.proxies.CJsDataset initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new charts.proxies.CJsDataset(context, mendixObject);
	}

	public static charts.proxies.CJsDataset load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return charts.proxies.CJsDataset.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Color
	 */
	public final java.lang.String getColor()
	{
		return getColor(getContext());
	}

	/**
	 * @param context
	 * @return value of Color
	 */
	public final java.lang.String getColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Color.toString());
	}

	/**
	 * Set value of Color
	 * @param color
	 */
	public final void setColor(java.lang.String color)
	{
		setColor(getContext(), color);
	}

	/**
	 * Set value of Color
	 * @param context
	 * @param color
	 */
	public final void setColor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String color)
	{
		getMendixObject().setValue(context, MemberNames.Color.toString(), color);
	}

	/**
	 * @return value of Label
	 */
	public final java.lang.String getLabel()
	{
		return getLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of Label
	 */
	public final java.lang.String getLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Label.toString());
	}

	/**
	 * Set value of Label
	 * @param label
	 */
	public final void setLabel(java.lang.String label)
	{
		setLabel(getContext(), label);
	}

	/**
	 * Set value of Label
	 * @param context
	 * @param label
	 */
	public final void setLabel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String label)
	{
		getMendixObject().setValue(context, MemberNames.Label.toString(), label);
	}

	/**
	 * @return value of Sorting
	 */
	public final java.lang.Integer getSorting()
	{
		return getSorting(getContext());
	}

	/**
	 * @param context
	 * @return value of Sorting
	 */
	public final java.lang.Integer getSorting(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Sorting.toString());
	}

	/**
	 * Set value of Sorting
	 * @param sorting
	 */
	public final void setSorting(java.lang.Integer sorting)
	{
		setSorting(getContext(), sorting);
	}

	/**
	 * Set value of Sorting
	 * @param context
	 * @param sorting
	 */
	public final void setSorting(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sorting)
	{
		getMendixObject().setValue(context, MemberNames.Sorting.toString(), sorting);
	}

	/**
	 * @return value of CJsDataset_SingleCJsDataPoint
	 */
	public final charts.proxies.CJsDataPoint getCJsDataset_SingleCJsDataPoint() throws com.mendix.core.CoreException
	{
		return getCJsDataset_SingleCJsDataPoint(getContext());
	}

	/**
	 * @param context
	 * @return value of CJsDataset_SingleCJsDataPoint
	 */
	public final charts.proxies.CJsDataPoint getCJsDataset_SingleCJsDataPoint(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		charts.proxies.CJsDataPoint result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CJsDataset_SingleCJsDataPoint.toString());
		if (identifier != null)
			result = charts.proxies.CJsDataPoint.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CJsDataset_SingleCJsDataPoint
	 * @param cjsdataset_singlecjsdatapoint
	 */
	public final void setCJsDataset_SingleCJsDataPoint(charts.proxies.CJsDataPoint cjsdataset_singlecjsdatapoint)
	{
		setCJsDataset_SingleCJsDataPoint(getContext(), cjsdataset_singlecjsdatapoint);
	}

	/**
	 * Set value of CJsDataset_SingleCJsDataPoint
	 * @param context
	 * @param cjsdataset_singlecjsdatapoint
	 */
	public final void setCJsDataset_SingleCJsDataPoint(com.mendix.systemwideinterfaces.core.IContext context, charts.proxies.CJsDataPoint cjsdataset_singlecjsdatapoint)
	{
		if (cjsdataset_singlecjsdatapoint == null)
			getMendixObject().setValue(context, MemberNames.CJsDataset_SingleCJsDataPoint.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CJsDataset_SingleCJsDataPoint.toString(), cjsdataset_singlecjsdatapoint.getMendixObject().getId());
	}

	/**
	 * @return value of CJsDataset_MultiCJsDataPoint
	 */
	public final java.util.List<charts.proxies.CJsDataPoint> getCJsDataset_MultiCJsDataPoint() throws com.mendix.core.CoreException
	{
		return getCJsDataset_MultiCJsDataPoint(getContext());
	}

	/**
	 * @param context
	 * @return value of CJsDataset_MultiCJsDataPoint
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<charts.proxies.CJsDataPoint> getCJsDataset_MultiCJsDataPoint(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<charts.proxies.CJsDataPoint> result = new java.util.ArrayList<charts.proxies.CJsDataPoint>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.CJsDataset_MultiCJsDataPoint.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(charts.proxies.CJsDataPoint.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of CJsDataset_MultiCJsDataPoint
	 * @param cjsdataset_multicjsdatapoint
	 */
	public final void setCJsDataset_MultiCJsDataPoint(java.util.List<charts.proxies.CJsDataPoint> cjsdataset_multicjsdatapoint)
	{
		setCJsDataset_MultiCJsDataPoint(getContext(), cjsdataset_multicjsdatapoint);
	}

	/**
	 * Set value of CJsDataset_MultiCJsDataPoint
	 * @param context
	 * @param cjsdataset_multicjsdatapoint
	 */
	public final void setCJsDataset_MultiCJsDataPoint(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<charts.proxies.CJsDataPoint> cjsdataset_multicjsdatapoint)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (charts.proxies.CJsDataPoint proxyObject : cjsdataset_multicjsdatapoint)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.CJsDataset_MultiCJsDataPoint.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cJsDatasetMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final charts.proxies.CJsDataset that = (charts.proxies.CJsDataset) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Charts.CJsDataset";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
