// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package charts.proxies;

public class CJsDataPoint
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cJsDataPointMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Charts.CJsDataPoint";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		xValue("xValue"),
		xsortingvalue("xsortingvalue"),
		yValue("yValue");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CJsDataPoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Charts.CJsDataPoint"));
	}

	protected CJsDataPoint(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cJsDataPointMendixObject)
	{
		if (cJsDataPointMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Charts.CJsDataPoint", cJsDataPointMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Charts.CJsDataPoint");

		this.cJsDataPointMendixObject = cJsDataPointMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CJsDataPoint.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static charts.proxies.CJsDataPoint initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return charts.proxies.CJsDataPoint.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static charts.proxies.CJsDataPoint initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new charts.proxies.CJsDataPoint(context, mendixObject);
	}

	public static charts.proxies.CJsDataPoint load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return charts.proxies.CJsDataPoint.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of xValue
	 */
	public final java.lang.String getxValue()
	{
		return getxValue(getContext());
	}

	/**
	 * @param context
	 * @return value of xValue
	 */
	public final java.lang.String getxValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.xValue.toString());
	}

	/**
	 * Set value of xValue
	 * @param xvalue
	 */
	public final void setxValue(java.lang.String xvalue)
	{
		setxValue(getContext(), xvalue);
	}

	/**
	 * Set value of xValue
	 * @param context
	 * @param xvalue
	 */
	public final void setxValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xvalue)
	{
		getMendixObject().setValue(context, MemberNames.xValue.toString(), xvalue);
	}

	/**
	 * @return value of xsortingvalue
	 */
	public final java.lang.Integer getxsortingvalue()
	{
		return getxsortingvalue(getContext());
	}

	/**
	 * @param context
	 * @return value of xsortingvalue
	 */
	public final java.lang.Integer getxsortingvalue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.xsortingvalue.toString());
	}

	/**
	 * Set value of xsortingvalue
	 * @param xsortingvalue
	 */
	public final void setxsortingvalue(java.lang.Integer xsortingvalue)
	{
		setxsortingvalue(getContext(), xsortingvalue);
	}

	/**
	 * Set value of xsortingvalue
	 * @param context
	 * @param xsortingvalue
	 */
	public final void setxsortingvalue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer xsortingvalue)
	{
		getMendixObject().setValue(context, MemberNames.xsortingvalue.toString(), xsortingvalue);
	}

	/**
	 * @return value of yValue
	 */
	public final java.lang.Integer getyValue()
	{
		return getyValue(getContext());
	}

	/**
	 * @param context
	 * @return value of yValue
	 */
	public final java.lang.Integer getyValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.yValue.toString());
	}

	/**
	 * Set value of yValue
	 * @param yvalue
	 */
	public final void setyValue(java.lang.Integer yvalue)
	{
		setyValue(getContext(), yvalue);
	}

	/**
	 * Set value of yValue
	 * @param context
	 * @param yvalue
	 */
	public final void setyValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer yvalue)
	{
		getMendixObject().setValue(context, MemberNames.yValue.toString(), yvalue);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cJsDataPointMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final charts.proxies.CJsDataPoint that = (charts.proxies.CJsDataPoint) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Charts.CJsDataPoint";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
