// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package charts.proxies;

public enum Enum_BasicChartType
{
	Barchart(new java.lang.String[][] { new java.lang.String[] { "en_US", "Barchart" }, new java.lang.String[] { "nl_NL", "barchart" } }),
	Linechart(new java.lang.String[][] { new java.lang.String[] { "en_US", "Linechart" }, new java.lang.String[] { "nl_NL", "Lijngrafiek" } }),
	AreaChart(new java.lang.String[][] { new java.lang.String[] { "en_US", "AreaChart" }, new java.lang.String[] { "nl_NL", "Vlakdiagram" } }),
	PieChart(new java.lang.String[][] { new java.lang.String[] { "en_US", "PieChart" }, new java.lang.String[] { "nl_NL", "PieChart" } }),
	Heatmap(new java.lang.String[][] { new java.lang.String[] { "en_US", "Heatmap" }, new java.lang.String[] { "nl_NL", "Temperatuurkaart" } }),
	BubbleChart(new java.lang.String[][] { new java.lang.String[] { "en_US", "BubbleChart" }, new java.lang.String[] { "nl_NL", "BubbleChart" } }),
	ScatterChart(new java.lang.String[][] { new java.lang.String[] { "en_US", "ScatterChart" }, new java.lang.String[] { "nl_NL", "scatterchart" } }),
	DougnutChart(new java.lang.String[][] { new java.lang.String[] { "en_US", "DougnutChart" }, new java.lang.String[] { "nl_NL", "DougnutChart" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_BasicChartType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
