// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package charts.proxies;

public class SerieNP
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject serieNPMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Charts.SerieNP";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Charttype("Charttype"),
		Data("Data"),
		SerieNP_ChartNP("Charts.SerieNP_ChartNP");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SerieNP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Charts.SerieNP"));
	}

	protected SerieNP(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject serieNPMendixObject)
	{
		if (serieNPMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Charts.SerieNP", serieNPMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Charts.SerieNP");

		this.serieNPMendixObject = serieNPMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SerieNP.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static charts.proxies.SerieNP initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return charts.proxies.SerieNP.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static charts.proxies.SerieNP initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new charts.proxies.SerieNP(context, mendixObject);
	}

	public static charts.proxies.SerieNP load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return charts.proxies.SerieNP.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * Set value of Charttype
	 * @param charttype
	 */
	public final charts.proxies.Enum_BasicChartType getCharttype()
	{
		return getCharttype(getContext());
	}

	/**
	 * @param context
	 * @return value of Charttype
	 */
	public final charts.proxies.Enum_BasicChartType getCharttype(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Charttype.toString());
		if (obj == null)
			return null;

		return charts.proxies.Enum_BasicChartType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Charttype
	 * @param charttype
	 */
	public final void setCharttype(charts.proxies.Enum_BasicChartType charttype)
	{
		setCharttype(getContext(), charttype);
	}

	/**
	 * Set value of Charttype
	 * @param context
	 * @param charttype
	 */
	public final void setCharttype(com.mendix.systemwideinterfaces.core.IContext context, charts.proxies.Enum_BasicChartType charttype)
	{
		if (charttype != null)
			getMendixObject().setValue(context, MemberNames.Charttype.toString(), charttype.toString());
		else
			getMendixObject().setValue(context, MemberNames.Charttype.toString(), null);
	}

	/**
	 * @return value of Data
	 */
	public final java.lang.String getData()
	{
		return getData(getContext());
	}

	/**
	 * @param context
	 * @return value of Data
	 */
	public final java.lang.String getData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Data.toString());
	}

	/**
	 * Set value of Data
	 * @param data
	 */
	public final void setData(java.lang.String data)
	{
		setData(getContext(), data);
	}

	/**
	 * Set value of Data
	 * @param context
	 * @param data
	 */
	public final void setData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String data)
	{
		getMendixObject().setValue(context, MemberNames.Data.toString(), data);
	}

	/**
	 * @return value of SerieNP_ChartNP
	 */
	public final java.util.List<charts.proxies.ChartNP> getSerieNP_ChartNP() throws com.mendix.core.CoreException
	{
		return getSerieNP_ChartNP(getContext());
	}

	/**
	 * @param context
	 * @return value of SerieNP_ChartNP
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<charts.proxies.ChartNP> getSerieNP_ChartNP(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<charts.proxies.ChartNP> result = new java.util.ArrayList<charts.proxies.ChartNP>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.SerieNP_ChartNP.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(charts.proxies.ChartNP.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of SerieNP_ChartNP
	 * @param serienp_chartnp
	 */
	public final void setSerieNP_ChartNP(java.util.List<charts.proxies.ChartNP> serienp_chartnp)
	{
		setSerieNP_ChartNP(getContext(), serienp_chartnp);
	}

	/**
	 * Set value of SerieNP_ChartNP
	 * @param context
	 * @param serienp_chartnp
	 */
	public final void setSerieNP_ChartNP(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<charts.proxies.ChartNP> serienp_chartnp)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (charts.proxies.ChartNP proxyObject : serienp_chartnp)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.SerieNP_ChartNP.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return serieNPMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final charts.proxies.SerieNP that = (charts.proxies.SerieNP) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Charts.SerieNP";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
