// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package parallelexecute.proxies;

public class ParallelExecuteOptions
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject parallelExecuteOptionsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ParallelExecute.ParallelExecuteOptions";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Timeout("Timeout"),
		NrParallelThreads("NrParallelThreads"),
		ExceptionHandling("ExceptionHandling");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ParallelExecuteOptions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ParallelExecute.ParallelExecuteOptions"));
	}

	protected ParallelExecuteOptions(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject parallelExecuteOptionsMendixObject)
	{
		if (parallelExecuteOptionsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ParallelExecute.ParallelExecuteOptions", parallelExecuteOptionsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ParallelExecute.ParallelExecuteOptions");

		this.parallelExecuteOptionsMendixObject = parallelExecuteOptionsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ParallelExecuteOptions.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static parallelexecute.proxies.ParallelExecuteOptions initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return parallelexecute.proxies.ParallelExecuteOptions.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static parallelexecute.proxies.ParallelExecuteOptions initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new parallelexecute.proxies.ParallelExecuteOptions(context, mendixObject);
	}

	public static parallelexecute.proxies.ParallelExecuteOptions load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return parallelexecute.proxies.ParallelExecuteOptions.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Timeout
	 */
	public final java.lang.Integer getTimeout()
	{
		return getTimeout(getContext());
	}

	/**
	 * @param context
	 * @return value of Timeout
	 */
	public final java.lang.Integer getTimeout(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Timeout.toString());
	}

	/**
	 * Set value of Timeout
	 * @param timeout
	 */
	public final void setTimeout(java.lang.Integer timeout)
	{
		setTimeout(getContext(), timeout);
	}

	/**
	 * Set value of Timeout
	 * @param context
	 * @param timeout
	 */
	public final void setTimeout(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer timeout)
	{
		getMendixObject().setValue(context, MemberNames.Timeout.toString(), timeout);
	}

	/**
	 * @return value of NrParallelThreads
	 */
	public final java.lang.Integer getNrParallelThreads()
	{
		return getNrParallelThreads(getContext());
	}

	/**
	 * @param context
	 * @return value of NrParallelThreads
	 */
	public final java.lang.Integer getNrParallelThreads(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NrParallelThreads.toString());
	}

	/**
	 * Set value of NrParallelThreads
	 * @param nrparallelthreads
	 */
	public final void setNrParallelThreads(java.lang.Integer nrparallelthreads)
	{
		setNrParallelThreads(getContext(), nrparallelthreads);
	}

	/**
	 * Set value of NrParallelThreads
	 * @param context
	 * @param nrparallelthreads
	 */
	public final void setNrParallelThreads(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nrparallelthreads)
	{
		getMendixObject().setValue(context, MemberNames.NrParallelThreads.toString(), nrparallelthreads);
	}

	/**
	 * Set value of ExceptionHandling
	 * @param exceptionhandling
	 */
	public final parallelexecute.proxies.ENUM_ParallelActionsExceptionHandling getExceptionHandling()
	{
		return getExceptionHandling(getContext());
	}

	/**
	 * @param context
	 * @return value of ExceptionHandling
	 */
	public final parallelexecute.proxies.ENUM_ParallelActionsExceptionHandling getExceptionHandling(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ExceptionHandling.toString());
		if (obj == null)
			return null;

		return parallelexecute.proxies.ENUM_ParallelActionsExceptionHandling.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ExceptionHandling
	 * @param exceptionhandling
	 */
	public final void setExceptionHandling(parallelexecute.proxies.ENUM_ParallelActionsExceptionHandling exceptionhandling)
	{
		setExceptionHandling(getContext(), exceptionhandling);
	}

	/**
	 * Set value of ExceptionHandling
	 * @param context
	 * @param exceptionhandling
	 */
	public final void setExceptionHandling(com.mendix.systemwideinterfaces.core.IContext context, parallelexecute.proxies.ENUM_ParallelActionsExceptionHandling exceptionhandling)
	{
		if (exceptionhandling != null)
			getMendixObject().setValue(context, MemberNames.ExceptionHandling.toString(), exceptionhandling.toString());
		else
			getMendixObject().setValue(context, MemberNames.ExceptionHandling.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return parallelExecuteOptionsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final parallelexecute.proxies.ParallelExecuteOptions that = (parallelexecute.proxies.ParallelExecuteOptions) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ParallelExecute.ParallelExecuteOptions";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
