// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package domdal.proxies;

/**
 * Address of a real estate object, for instance a house, a building, a flat, a stable.
 */
public class Address
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject addressMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DomDAL.Address";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Street("Street"),
		Postalcode("Postalcode"),
		Housenumber("Housenumber"),
		HasShore("HasShore"),
		Person_HomeAddress("DomDAL.Person_HomeAddress"),
		Address_Country("DomDAL.Address_Country");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Address(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DomDAL.Address"));
	}

	protected Address(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject addressMendixObject)
	{
		if (addressMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DomDAL.Address", addressMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DomDAL.Address");

		this.addressMendixObject = addressMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Address.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static domdal.proxies.Address initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return domdal.proxies.Address.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static domdal.proxies.Address initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new domdal.proxies.Address(context, mendixObject);
	}

	public static domdal.proxies.Address load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return domdal.proxies.Address.initialize(context, mendixObject);
	}

	public static java.util.List<domdal.proxies.Address> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<domdal.proxies.Address> result = new java.util.ArrayList<domdal.proxies.Address>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DomDAL.Address" + xpathConstraint))
			result.add(domdal.proxies.Address.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Street
	 */
	public final java.lang.String getStreet()
	{
		return getStreet(getContext());
	}

	/**
	 * @param context
	 * @return value of Street
	 */
	public final java.lang.String getStreet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Street.toString());
	}

	/**
	 * Set value of Street
	 * @param street
	 */
	public final void setStreet(java.lang.String street)
	{
		setStreet(getContext(), street);
	}

	/**
	 * Set value of Street
	 * @param context
	 * @param street
	 */
	public final void setStreet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String street)
	{
		getMendixObject().setValue(context, MemberNames.Street.toString(), street);
	}

	/**
	 * @return value of Postalcode
	 */
	public final java.lang.String getPostalcode()
	{
		return getPostalcode(getContext());
	}

	/**
	 * @param context
	 * @return value of Postalcode
	 */
	public final java.lang.String getPostalcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Postalcode.toString());
	}

	/**
	 * Set value of Postalcode
	 * @param postalcode
	 */
	public final void setPostalcode(java.lang.String postalcode)
	{
		setPostalcode(getContext(), postalcode);
	}

	/**
	 * Set value of Postalcode
	 * @param context
	 * @param postalcode
	 */
	public final void setPostalcode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String postalcode)
	{
		getMendixObject().setValue(context, MemberNames.Postalcode.toString(), postalcode);
	}

	/**
	 * @return value of Housenumber
	 */
	public final java.lang.String getHousenumber()
	{
		return getHousenumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Housenumber
	 */
	public final java.lang.String getHousenumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Housenumber.toString());
	}

	/**
	 * Set value of Housenumber
	 * @param housenumber
	 */
	public final void setHousenumber(java.lang.String housenumber)
	{
		setHousenumber(getContext(), housenumber);
	}

	/**
	 * Set value of Housenumber
	 * @param context
	 * @param housenumber
	 */
	public final void setHousenumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String housenumber)
	{
		getMendixObject().setValue(context, MemberNames.Housenumber.toString(), housenumber);
	}

	/**
	 * @return value of HasShore
	 */
	public final java.lang.Boolean getHasShore()
	{
		return getHasShore(getContext());
	}

	/**
	 * @param context
	 * @return value of HasShore
	 */
	public final java.lang.Boolean getHasShore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasShore.toString());
	}

	/**
	 * Set value of HasShore
	 * @param hasshore
	 */
	public final void setHasShore(java.lang.Boolean hasshore)
	{
		setHasShore(getContext(), hasshore);
	}

	/**
	 * Set value of HasShore
	 * @param context
	 * @param hasshore
	 */
	public final void setHasShore(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasshore)
	{
		getMendixObject().setValue(context, MemberNames.HasShore.toString(), hasshore);
	}

	/**
	 * @return value of Person_HomeAddress
	 */
	public final domdal.proxies.Person getPerson_HomeAddress() throws com.mendix.core.CoreException
	{
		return getPerson_HomeAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_HomeAddress
	 */
	public final domdal.proxies.Person getPerson_HomeAddress(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		domdal.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_HomeAddress.toString());
		if (identifier != null)
			result = domdal.proxies.Person.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Person_HomeAddress
	 * @param person_homeaddress
	 */
	public final void setPerson_HomeAddress(domdal.proxies.Person person_homeaddress)
	{
		setPerson_HomeAddress(getContext(), person_homeaddress);
	}

	/**
	 * Set value of Person_HomeAddress
	 * @param context
	 * @param person_homeaddress
	 */
	public final void setPerson_HomeAddress(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.Person person_homeaddress)
	{
		if (person_homeaddress == null)
			getMendixObject().setValue(context, MemberNames.Person_HomeAddress.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Person_HomeAddress.toString(), person_homeaddress.getMendixObject().getId());
	}

	/**
	 * @return value of Address_Country
	 */
	public final domdal.proxies.Country getAddress_Country() throws com.mendix.core.CoreException
	{
		return getAddress_Country(getContext());
	}

	/**
	 * @param context
	 * @return value of Address_Country
	 */
	public final domdal.proxies.Country getAddress_Country(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		domdal.proxies.Country result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Address_Country.toString());
		if (identifier != null)
			result = domdal.proxies.Country.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Address_Country
	 * @param address_country
	 */
	public final void setAddress_Country(domdal.proxies.Country address_country)
	{
		setAddress_Country(getContext(), address_country);
	}

	/**
	 * Set value of Address_Country
	 * @param context
	 * @param address_country
	 */
	public final void setAddress_Country(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.Country address_country)
	{
		if (address_country == null)
			getMendixObject().setValue(context, MemberNames.Address_Country.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Address_Country.toString(), address_country.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return addressMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final domdal.proxies.Address that = (domdal.proxies.Address) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DomDAL.Address";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
