// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package domdal.proxies;

public class Country
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject countryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DomDAL.Country";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Code("Code"),
		Name("Name"),
		number("number"),
		Country_Flag("DomDAL.Country_Flag");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Country(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DomDAL.Country"));
	}

	protected Country(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject countryMendixObject)
	{
		if (countryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DomDAL.Country", countryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DomDAL.Country");

		this.countryMendixObject = countryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Country.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static domdal.proxies.Country initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return domdal.proxies.Country.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static domdal.proxies.Country initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new domdal.proxies.Country(context, mendixObject);
	}

	public static domdal.proxies.Country load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return domdal.proxies.Country.initialize(context, mendixObject);
	}

	public static java.util.List<domdal.proxies.Country> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<domdal.proxies.Country> result = new java.util.ArrayList<domdal.proxies.Country>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DomDAL.Country" + xpathConstraint))
			result.add(domdal.proxies.Country.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Code
	 */
	public final java.lang.String getCode()
	{
		return getCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Code
	 */
	public final java.lang.String getCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Code.toString());
	}

	/**
	 * Set value of Code
	 * @param code
	 */
	public final void setCode(java.lang.String code)
	{
		setCode(getContext(), code);
	}

	/**
	 * Set value of Code
	 * @param context
	 * @param code
	 */
	public final void setCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String code)
	{
		getMendixObject().setValue(context, MemberNames.Code.toString(), code);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of number
	 */
	public final java.math.BigDecimal getnumber()
	{
		return getnumber(getContext());
	}

	/**
	 * @param context
	 * @return value of number
	 */
	public final java.math.BigDecimal getnumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.number.toString());
	}

	/**
	 * Set value of number
	 * @param number
	 */
	public final void setnumber(java.math.BigDecimal number)
	{
		setnumber(getContext(), number);
	}

	/**
	 * Set value of number
	 * @param context
	 * @param number
	 */
	public final void setnumber(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal number)
	{
		getMendixObject().setValue(context, MemberNames.number.toString(), number);
	}

	/**
	 * @return value of Country_Flag
	 */
	public final domdal.proxies.Flag getCountry_Flag() throws com.mendix.core.CoreException
	{
		return getCountry_Flag(getContext());
	}

	/**
	 * @param context
	 * @return value of Country_Flag
	 */
	public final domdal.proxies.Flag getCountry_Flag(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		domdal.proxies.Flag result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Country_Flag.toString());
		if (identifier != null)
			result = domdal.proxies.Flag.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Country_Flag
	 * @param country_flag
	 */
	public final void setCountry_Flag(domdal.proxies.Flag country_flag)
	{
		setCountry_Flag(getContext(), country_flag);
	}

	/**
	 * Set value of Country_Flag
	 * @param context
	 * @param country_flag
	 */
	public final void setCountry_Flag(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.Flag country_flag)
	{
		if (country_flag == null)
			getMendixObject().setValue(context, MemberNames.Country_Flag.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Country_Flag.toString(), country_flag.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return countryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final domdal.proxies.Country that = (domdal.proxies.Country) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DomDAL.Country";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
