// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package domdal.proxies;

/**
 * One day, one project
 */
public class DailyTimeRealized
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dailyTimeRealizedMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DomDAL.DailyTimeRealized";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Date("Date"),
		Starttime("Starttime"),
		Endtime("Endtime"),
		TimeRealized("TimeRealized"),
		SignedOffTimeRealized("SignedOffTimeRealized"),
		SignedOffAt("SignedOffAt"),
		SignedOffRemark("SignedOffRemark"),
		DailyTimeRealized_Project("DomDAL.DailyTimeRealized_Project"),
		DailyTimeRealized_Person("DomDAL.DailyTimeRealized_Person"),
		DailyTimeRealized_SignedOffByPerson("DomDAL.DailyTimeRealized_SignedOffByPerson");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DailyTimeRealized(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DomDAL.DailyTimeRealized"));
	}

	protected DailyTimeRealized(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dailyTimeRealizedMendixObject)
	{
		if (dailyTimeRealizedMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DomDAL.DailyTimeRealized", dailyTimeRealizedMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DomDAL.DailyTimeRealized");

		this.dailyTimeRealizedMendixObject = dailyTimeRealizedMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DailyTimeRealized.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static domdal.proxies.DailyTimeRealized initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return domdal.proxies.DailyTimeRealized.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static domdal.proxies.DailyTimeRealized initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new domdal.proxies.DailyTimeRealized(context, mendixObject);
	}

	public static domdal.proxies.DailyTimeRealized load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return domdal.proxies.DailyTimeRealized.initialize(context, mendixObject);
	}

	public static java.util.List<domdal.proxies.DailyTimeRealized> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<domdal.proxies.DailyTimeRealized> result = new java.util.ArrayList<domdal.proxies.DailyTimeRealized>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DomDAL.DailyTimeRealized" + xpathConstraint))
			result.add(domdal.proxies.DailyTimeRealized.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of Starttime
	 */
	public final java.util.Date getStarttime()
	{
		return getStarttime(getContext());
	}

	/**
	 * @param context
	 * @return value of Starttime
	 */
	public final java.util.Date getStarttime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Starttime.toString());
	}

	/**
	 * Set value of Starttime
	 * @param starttime
	 */
	public final void setStarttime(java.util.Date starttime)
	{
		setStarttime(getContext(), starttime);
	}

	/**
	 * Set value of Starttime
	 * @param context
	 * @param starttime
	 */
	public final void setStarttime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date starttime)
	{
		getMendixObject().setValue(context, MemberNames.Starttime.toString(), starttime);
	}

	/**
	 * @return value of Endtime
	 */
	public final java.util.Date getEndtime()
	{
		return getEndtime(getContext());
	}

	/**
	 * @param context
	 * @return value of Endtime
	 */
	public final java.util.Date getEndtime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Endtime.toString());
	}

	/**
	 * Set value of Endtime
	 * @param endtime
	 */
	public final void setEndtime(java.util.Date endtime)
	{
		setEndtime(getContext(), endtime);
	}

	/**
	 * Set value of Endtime
	 * @param context
	 * @param endtime
	 */
	public final void setEndtime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endtime)
	{
		getMendixObject().setValue(context, MemberNames.Endtime.toString(), endtime);
	}

	/**
	 * @return value of TimeRealized
	 */
	public final java.math.BigDecimal getTimeRealized()
	{
		return getTimeRealized(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeRealized
	 */
	public final java.math.BigDecimal getTimeRealized(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TimeRealized.toString());
	}

	/**
	 * Set value of TimeRealized
	 * @param timerealized
	 */
	public final void setTimeRealized(java.math.BigDecimal timerealized)
	{
		setTimeRealized(getContext(), timerealized);
	}

	/**
	 * Set value of TimeRealized
	 * @param context
	 * @param timerealized
	 */
	public final void setTimeRealized(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal timerealized)
	{
		getMendixObject().setValue(context, MemberNames.TimeRealized.toString(), timerealized);
	}

	/**
	 * @return value of SignedOffTimeRealized
	 */
	public final java.math.BigDecimal getSignedOffTimeRealized()
	{
		return getSignedOffTimeRealized(getContext());
	}

	/**
	 * @param context
	 * @return value of SignedOffTimeRealized
	 */
	public final java.math.BigDecimal getSignedOffTimeRealized(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.SignedOffTimeRealized.toString());
	}

	/**
	 * Set value of SignedOffTimeRealized
	 * @param signedofftimerealized
	 */
	public final void setSignedOffTimeRealized(java.math.BigDecimal signedofftimerealized)
	{
		setSignedOffTimeRealized(getContext(), signedofftimerealized);
	}

	/**
	 * Set value of SignedOffTimeRealized
	 * @param context
	 * @param signedofftimerealized
	 */
	public final void setSignedOffTimeRealized(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal signedofftimerealized)
	{
		getMendixObject().setValue(context, MemberNames.SignedOffTimeRealized.toString(), signedofftimerealized);
	}

	/**
	 * @return value of SignedOffAt
	 */
	public final java.util.Date getSignedOffAt()
	{
		return getSignedOffAt(getContext());
	}

	/**
	 * @param context
	 * @return value of SignedOffAt
	 */
	public final java.util.Date getSignedOffAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SignedOffAt.toString());
	}

	/**
	 * Set value of SignedOffAt
	 * @param signedoffat
	 */
	public final void setSignedOffAt(java.util.Date signedoffat)
	{
		setSignedOffAt(getContext(), signedoffat);
	}

	/**
	 * Set value of SignedOffAt
	 * @param context
	 * @param signedoffat
	 */
	public final void setSignedOffAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date signedoffat)
	{
		getMendixObject().setValue(context, MemberNames.SignedOffAt.toString(), signedoffat);
	}

	/**
	 * @return value of SignedOffRemark
	 */
	public final java.lang.String getSignedOffRemark()
	{
		return getSignedOffRemark(getContext());
	}

	/**
	 * @param context
	 * @return value of SignedOffRemark
	 */
	public final java.lang.String getSignedOffRemark(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SignedOffRemark.toString());
	}

	/**
	 * Set value of SignedOffRemark
	 * @param signedoffremark
	 */
	public final void setSignedOffRemark(java.lang.String signedoffremark)
	{
		setSignedOffRemark(getContext(), signedoffremark);
	}

	/**
	 * Set value of SignedOffRemark
	 * @param context
	 * @param signedoffremark
	 */
	public final void setSignedOffRemark(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String signedoffremark)
	{
		getMendixObject().setValue(context, MemberNames.SignedOffRemark.toString(), signedoffremark);
	}

	/**
	 * @return value of DailyTimeRealized_Project
	 */
	public final domdal.proxies.Project getDailyTimeRealized_Project() throws com.mendix.core.CoreException
	{
		return getDailyTimeRealized_Project(getContext());
	}

	/**
	 * @param context
	 * @return value of DailyTimeRealized_Project
	 */
	public final domdal.proxies.Project getDailyTimeRealized_Project(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		domdal.proxies.Project result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DailyTimeRealized_Project.toString());
		if (identifier != null)
			result = domdal.proxies.Project.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DailyTimeRealized_Project
	 * @param dailytimerealized_project
	 */
	public final void setDailyTimeRealized_Project(domdal.proxies.Project dailytimerealized_project)
	{
		setDailyTimeRealized_Project(getContext(), dailytimerealized_project);
	}

	/**
	 * Set value of DailyTimeRealized_Project
	 * @param context
	 * @param dailytimerealized_project
	 */
	public final void setDailyTimeRealized_Project(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.Project dailytimerealized_project)
	{
		if (dailytimerealized_project == null)
			getMendixObject().setValue(context, MemberNames.DailyTimeRealized_Project.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DailyTimeRealized_Project.toString(), dailytimerealized_project.getMendixObject().getId());
	}

	/**
	 * @return value of DailyTimeRealized_Person
	 */
	public final domdal.proxies.Person getDailyTimeRealized_Person() throws com.mendix.core.CoreException
	{
		return getDailyTimeRealized_Person(getContext());
	}

	/**
	 * @param context
	 * @return value of DailyTimeRealized_Person
	 */
	public final domdal.proxies.Person getDailyTimeRealized_Person(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		domdal.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DailyTimeRealized_Person.toString());
		if (identifier != null)
			result = domdal.proxies.Person.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DailyTimeRealized_Person
	 * @param dailytimerealized_person
	 */
	public final void setDailyTimeRealized_Person(domdal.proxies.Person dailytimerealized_person)
	{
		setDailyTimeRealized_Person(getContext(), dailytimerealized_person);
	}

	/**
	 * Set value of DailyTimeRealized_Person
	 * @param context
	 * @param dailytimerealized_person
	 */
	public final void setDailyTimeRealized_Person(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.Person dailytimerealized_person)
	{
		if (dailytimerealized_person == null)
			getMendixObject().setValue(context, MemberNames.DailyTimeRealized_Person.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DailyTimeRealized_Person.toString(), dailytimerealized_person.getMendixObject().getId());
	}

	/**
	 * @return value of DailyTimeRealized_SignedOffByPerson
	 */
	public final domdal.proxies.Person getDailyTimeRealized_SignedOffByPerson() throws com.mendix.core.CoreException
	{
		return getDailyTimeRealized_SignedOffByPerson(getContext());
	}

	/**
	 * @param context
	 * @return value of DailyTimeRealized_SignedOffByPerson
	 */
	public final domdal.proxies.Person getDailyTimeRealized_SignedOffByPerson(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		domdal.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DailyTimeRealized_SignedOffByPerson.toString());
		if (identifier != null)
			result = domdal.proxies.Person.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DailyTimeRealized_SignedOffByPerson
	 * @param dailytimerealized_signedoffbyperson
	 */
	public final void setDailyTimeRealized_SignedOffByPerson(domdal.proxies.Person dailytimerealized_signedoffbyperson)
	{
		setDailyTimeRealized_SignedOffByPerson(getContext(), dailytimerealized_signedoffbyperson);
	}

	/**
	 * Set value of DailyTimeRealized_SignedOffByPerson
	 * @param context
	 * @param dailytimerealized_signedoffbyperson
	 */
	public final void setDailyTimeRealized_SignedOffByPerson(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.Person dailytimerealized_signedoffbyperson)
	{
		if (dailytimerealized_signedoffbyperson == null)
			getMendixObject().setValue(context, MemberNames.DailyTimeRealized_SignedOffByPerson.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DailyTimeRealized_SignedOffByPerson.toString(), dailytimerealized_signedoffbyperson.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dailyTimeRealizedMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final domdal.proxies.DailyTimeRealized that = (domdal.proxies.DailyTimeRealized) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DomDAL.DailyTimeRealized";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
