// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package domdal.proxies;

/**
 * One day, one project
 */
public class DailyTimePlanned
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dailyTimePlannedMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DomDAL.DailyTimePlanned";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Date("Date"),
		Startime("Startime"),
		Endtime("Endtime"),
		TimePlanned("TimePlanned"),
		DailyTimePlanned_Project("DomDAL.DailyTimePlanned_Project"),
		DailyTimePlanned_Person("DomDAL.DailyTimePlanned_Person");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DailyTimePlanned(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DomDAL.DailyTimePlanned"));
	}

	protected DailyTimePlanned(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dailyTimePlannedMendixObject)
	{
		if (dailyTimePlannedMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DomDAL.DailyTimePlanned", dailyTimePlannedMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DomDAL.DailyTimePlanned");

		this.dailyTimePlannedMendixObject = dailyTimePlannedMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DailyTimePlanned.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static domdal.proxies.DailyTimePlanned initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return domdal.proxies.DailyTimePlanned.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static domdal.proxies.DailyTimePlanned initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new domdal.proxies.DailyTimePlanned(context, mendixObject);
	}

	public static domdal.proxies.DailyTimePlanned load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return domdal.proxies.DailyTimePlanned.initialize(context, mendixObject);
	}

	public static java.util.List<domdal.proxies.DailyTimePlanned> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<domdal.proxies.DailyTimePlanned> result = new java.util.ArrayList<domdal.proxies.DailyTimePlanned>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DomDAL.DailyTimePlanned" + xpathConstraint))
			result.add(domdal.proxies.DailyTimePlanned.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of Startime
	 */
	public final java.util.Date getStartime()
	{
		return getStartime(getContext());
	}

	/**
	 * @param context
	 * @return value of Startime
	 */
	public final java.util.Date getStartime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Startime.toString());
	}

	/**
	 * Set value of Startime
	 * @param startime
	 */
	public final void setStartime(java.util.Date startime)
	{
		setStartime(getContext(), startime);
	}

	/**
	 * Set value of Startime
	 * @param context
	 * @param startime
	 */
	public final void setStartime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startime)
	{
		getMendixObject().setValue(context, MemberNames.Startime.toString(), startime);
	}

	/**
	 * @return value of Endtime
	 */
	public final java.util.Date getEndtime()
	{
		return getEndtime(getContext());
	}

	/**
	 * @param context
	 * @return value of Endtime
	 */
	public final java.util.Date getEndtime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Endtime.toString());
	}

	/**
	 * Set value of Endtime
	 * @param endtime
	 */
	public final void setEndtime(java.util.Date endtime)
	{
		setEndtime(getContext(), endtime);
	}

	/**
	 * Set value of Endtime
	 * @param context
	 * @param endtime
	 */
	public final void setEndtime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endtime)
	{
		getMendixObject().setValue(context, MemberNames.Endtime.toString(), endtime);
	}

	/**
	 * @return value of TimePlanned
	 */
	public final java.math.BigDecimal getTimePlanned()
	{
		return getTimePlanned(getContext());
	}

	/**
	 * @param context
	 * @return value of TimePlanned
	 */
	public final java.math.BigDecimal getTimePlanned(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TimePlanned.toString());
	}

	/**
	 * Set value of TimePlanned
	 * @param timeplanned
	 */
	public final void setTimePlanned(java.math.BigDecimal timeplanned)
	{
		setTimePlanned(getContext(), timeplanned);
	}

	/**
	 * Set value of TimePlanned
	 * @param context
	 * @param timeplanned
	 */
	public final void setTimePlanned(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal timeplanned)
	{
		getMendixObject().setValue(context, MemberNames.TimePlanned.toString(), timeplanned);
	}

	/**
	 * @return value of DailyTimePlanned_Project
	 */
	public final domdal.proxies.Project getDailyTimePlanned_Project() throws com.mendix.core.CoreException
	{
		return getDailyTimePlanned_Project(getContext());
	}

	/**
	 * @param context
	 * @return value of DailyTimePlanned_Project
	 */
	public final domdal.proxies.Project getDailyTimePlanned_Project(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		domdal.proxies.Project result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DailyTimePlanned_Project.toString());
		if (identifier != null)
			result = domdal.proxies.Project.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DailyTimePlanned_Project
	 * @param dailytimeplanned_project
	 */
	public final void setDailyTimePlanned_Project(domdal.proxies.Project dailytimeplanned_project)
	{
		setDailyTimePlanned_Project(getContext(), dailytimeplanned_project);
	}

	/**
	 * Set value of DailyTimePlanned_Project
	 * @param context
	 * @param dailytimeplanned_project
	 */
	public final void setDailyTimePlanned_Project(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.Project dailytimeplanned_project)
	{
		if (dailytimeplanned_project == null)
			getMendixObject().setValue(context, MemberNames.DailyTimePlanned_Project.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DailyTimePlanned_Project.toString(), dailytimeplanned_project.getMendixObject().getId());
	}

	/**
	 * @return value of DailyTimePlanned_Person
	 */
	public final domdal.proxies.Person getDailyTimePlanned_Person() throws com.mendix.core.CoreException
	{
		return getDailyTimePlanned_Person(getContext());
	}

	/**
	 * @param context
	 * @return value of DailyTimePlanned_Person
	 */
	public final domdal.proxies.Person getDailyTimePlanned_Person(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		domdal.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DailyTimePlanned_Person.toString());
		if (identifier != null)
			result = domdal.proxies.Person.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DailyTimePlanned_Person
	 * @param dailytimeplanned_person
	 */
	public final void setDailyTimePlanned_Person(domdal.proxies.Person dailytimeplanned_person)
	{
		setDailyTimePlanned_Person(getContext(), dailytimeplanned_person);
	}

	/**
	 * Set value of DailyTimePlanned_Person
	 * @param context
	 * @param dailytimeplanned_person
	 */
	public final void setDailyTimePlanned_Person(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.Person dailytimeplanned_person)
	{
		if (dailytimeplanned_person == null)
			getMendixObject().setValue(context, MemberNames.DailyTimePlanned_Person.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DailyTimePlanned_Person.toString(), dailytimeplanned_person.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dailyTimePlannedMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final domdal.proxies.DailyTimePlanned that = (domdal.proxies.DailyTimePlanned) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DomDAL.DailyTimePlanned";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
