// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package domdal.proxies;

public enum Enum_Gender
{
	Male(new java.lang.String[][] { new java.lang.String[] { "en_US", "Male" }, new java.lang.String[] { "nl_NL", "Mannetje" } }),
	Female(new java.lang.String[][] { new java.lang.String[] { "en_US", "Female" }, new java.lang.String[] { "nl_NL", "Vrouw" } }),
	LGBTQ(new java.lang.String[][] { new java.lang.String[] { "en_US", "LGBTQ" }, new java.lang.String[] { "nl_NL", "LGBTQ" } }),
	NotGonnaTellYou(new java.lang.String[][] { new java.lang.String[] { "en_US", "NotGonnaTellYou" }, new java.lang.String[] { "nl_NL", "NotGonnaTellYou" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_Gender(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
