// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package domdal.proxies;

public class Flag extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DomDAL.Flag";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Country_Flag("DomDAL.Country_Flag");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Flag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DomDAL.Flag"));
	}

	protected Flag(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject flagMendixObject)
	{
		super(context, flagMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DomDAL.Flag", flagMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DomDAL.Flag");
	}

	/**
	 * @deprecated Use 'Flag.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static domdal.proxies.Flag initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return domdal.proxies.Flag.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static domdal.proxies.Flag initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new domdal.proxies.Flag(context, mendixObject);
	}

	public static domdal.proxies.Flag load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return domdal.proxies.Flag.initialize(context, mendixObject);
	}

	public static java.util.List<domdal.proxies.Flag> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<domdal.proxies.Flag> result = new java.util.ArrayList<domdal.proxies.Flag>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DomDAL.Flag" + xpathConstraint))
			result.add(domdal.proxies.Flag.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Country_Flag
	 */
	public final domdal.proxies.Country getCountry_Flag() throws com.mendix.core.CoreException
	{
		return getCountry_Flag(getContext());
	}

	/**
	 * @param context
	 * @return value of Country_Flag
	 */
	public final domdal.proxies.Country getCountry_Flag(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		domdal.proxies.Country result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Country_Flag.toString());
		if (identifier != null)
			result = domdal.proxies.Country.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Country_Flag
	 * @param country_flag
	 */
	public final void setCountry_Flag(domdal.proxies.Country country_flag)
	{
		setCountry_Flag(getContext(), country_flag);
	}

	/**
	 * Set value of Country_Flag
	 * @param context
	 * @param country_flag
	 */
	public final void setCountry_Flag(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.Country country_flag)
	{
		if (country_flag == null)
			getMendixObject().setValue(context, MemberNames.Country_Flag.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Country_Flag.toString(), country_flag.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final domdal.proxies.Flag that = (domdal.proxies.Flag) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DomDAL.Flag";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
