// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package domdal.proxies;

/**
 * A living being, roaming the earth upright on two feet, thinking, playing with fire, loving, cheering, helping.
 */
public class Person
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject personMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DomDAL.Person";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Age("Age"),
		DateOfBirth("DateOfBirth"),
		NetWorth("NetWorth"),
		Alive("Alive"),
		Gender("Gender"),
		Pincode("Pincode"),
		CharacterDescription("CharacterDescription"),
		DailyTimeRealized_SignedOffByPerson("DomDAL.DailyTimeRealized_SignedOffByPerson"),
		Person_Party("DomDAL.Person_Party"),
		Person_HomeAddress("DomDAL.Person_HomeAddress");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Person(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DomDAL.Person"));
	}

	protected Person(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject personMendixObject)
	{
		if (personMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DomDAL.Person", personMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DomDAL.Person");

		this.personMendixObject = personMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Person.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static domdal.proxies.Person initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return domdal.proxies.Person.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static domdal.proxies.Person initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new domdal.proxies.Person(context, mendixObject);
	}

	public static domdal.proxies.Person load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return domdal.proxies.Person.initialize(context, mendixObject);
	}

	public static java.util.List<domdal.proxies.Person> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<domdal.proxies.Person> result = new java.util.ArrayList<domdal.proxies.Person>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DomDAL.Person" + xpathConstraint))
			result.add(domdal.proxies.Person.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Age
	 */
	public final java.lang.Integer getAge()
	{
		return getAge(getContext());
	}

	/**
	 * @param context
	 * @return value of Age
	 */
	public final java.lang.Integer getAge(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Age.toString());
	}

	/**
	 * Set value of Age
	 * @param age
	 */
	public final void setAge(java.lang.Integer age)
	{
		setAge(getContext(), age);
	}

	/**
	 * Set value of Age
	 * @param context
	 * @param age
	 */
	public final void setAge(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer age)
	{
		getMendixObject().setValue(context, MemberNames.Age.toString(), age);
	}

	/**
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth()
	{
		return getDateOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfBirth.toString());
	}

	/**
	 * Set value of DateOfBirth
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(java.util.Date dateofbirth)
	{
		setDateOfBirth(getContext(), dateofbirth);
	}

	/**
	 * Set value of DateOfBirth
	 * @param context
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofbirth)
	{
		getMendixObject().setValue(context, MemberNames.DateOfBirth.toString(), dateofbirth);
	}

	/**
	 * @return value of NetWorth
	 */
	public final java.math.BigDecimal getNetWorth()
	{
		return getNetWorth(getContext());
	}

	/**
	 * @param context
	 * @return value of NetWorth
	 */
	public final java.math.BigDecimal getNetWorth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.NetWorth.toString());
	}

	/**
	 * Set value of NetWorth
	 * @param networth
	 */
	public final void setNetWorth(java.math.BigDecimal networth)
	{
		setNetWorth(getContext(), networth);
	}

	/**
	 * Set value of NetWorth
	 * @param context
	 * @param networth
	 */
	public final void setNetWorth(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal networth)
	{
		getMendixObject().setValue(context, MemberNames.NetWorth.toString(), networth);
	}

	/**
	 * @return value of Alive
	 */
	public final java.lang.Boolean getAlive()
	{
		return getAlive(getContext());
	}

	/**
	 * @param context
	 * @return value of Alive
	 */
	public final java.lang.Boolean getAlive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Alive.toString());
	}

	/**
	 * Set value of Alive
	 * @param alive
	 */
	public final void setAlive(java.lang.Boolean alive)
	{
		setAlive(getContext(), alive);
	}

	/**
	 * Set value of Alive
	 * @param context
	 * @param alive
	 */
	public final void setAlive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean alive)
	{
		getMendixObject().setValue(context, MemberNames.Alive.toString(), alive);
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final domdal.proxies.Enum_Gender getGender()
	{
		return getGender(getContext());
	}

	/**
	 * @param context
	 * @return value of Gender
	 */
	public final domdal.proxies.Enum_Gender getGender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Gender.toString());
		if (obj == null)
			return null;

		return domdal.proxies.Enum_Gender.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final void setGender(domdal.proxies.Enum_Gender gender)
	{
		setGender(getContext(), gender);
	}

	/**
	 * Set value of Gender
	 * @param context
	 * @param gender
	 */
	public final void setGender(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.Enum_Gender gender)
	{
		if (gender != null)
			getMendixObject().setValue(context, MemberNames.Gender.toString(), gender.toString());
		else
			getMendixObject().setValue(context, MemberNames.Gender.toString(), null);
	}

	/**
	 * Set value of Pincode
	 * @param pincode
	 */
	public final void setPincode(java.lang.String pincode)
	{
		setPincode(getContext(), pincode);
	}

	/**
	 * Set value of Pincode
	 * @param context
	 * @param pincode
	 */
	public final void setPincode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pincode)
	{
		getMendixObject().setValue(context, MemberNames.Pincode.toString(), pincode);
	}

	/**
	 * @return value of CharacterDescription
	 */
	public final java.lang.String getCharacterDescription()
	{
		return getCharacterDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of CharacterDescription
	 */
	public final java.lang.String getCharacterDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CharacterDescription.toString());
	}

	/**
	 * Set value of CharacterDescription
	 * @param characterdescription
	 */
	public final void setCharacterDescription(java.lang.String characterdescription)
	{
		setCharacterDescription(getContext(), characterdescription);
	}

	/**
	 * Set value of CharacterDescription
	 * @param context
	 * @param characterdescription
	 */
	public final void setCharacterDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String characterdescription)
	{
		getMendixObject().setValue(context, MemberNames.CharacterDescription.toString(), characterdescription);
	}

	/**
	 * @return value of DailyTimeRealized_SignedOffByPerson
	 */
	public final domdal.proxies.DailyTimeRealized getDailyTimeRealized_SignedOffByPerson() throws com.mendix.core.CoreException
	{
		return getDailyTimeRealized_SignedOffByPerson(getContext());
	}

	/**
	 * @param context
	 * @return value of DailyTimeRealized_SignedOffByPerson
	 */
	public final domdal.proxies.DailyTimeRealized getDailyTimeRealized_SignedOffByPerson(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		domdal.proxies.DailyTimeRealized result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DailyTimeRealized_SignedOffByPerson.toString());
		if (identifier != null)
			result = domdal.proxies.DailyTimeRealized.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DailyTimeRealized_SignedOffByPerson
	 * @param dailytimerealized_signedoffbyperson
	 */
	public final void setDailyTimeRealized_SignedOffByPerson(domdal.proxies.DailyTimeRealized dailytimerealized_signedoffbyperson)
	{
		setDailyTimeRealized_SignedOffByPerson(getContext(), dailytimerealized_signedoffbyperson);
	}

	/**
	 * Set value of DailyTimeRealized_SignedOffByPerson
	 * @param context
	 * @param dailytimerealized_signedoffbyperson
	 */
	public final void setDailyTimeRealized_SignedOffByPerson(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.DailyTimeRealized dailytimerealized_signedoffbyperson)
	{
		if (dailytimerealized_signedoffbyperson == null)
			getMendixObject().setValue(context, MemberNames.DailyTimeRealized_SignedOffByPerson.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DailyTimeRealized_SignedOffByPerson.toString(), dailytimerealized_signedoffbyperson.getMendixObject().getId());
	}

	/**
	 * @return value of Person_Party
	 */
	public final domdal.proxies.Party getPerson_Party() throws com.mendix.core.CoreException
	{
		return getPerson_Party(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_Party
	 */
	public final domdal.proxies.Party getPerson_Party(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		domdal.proxies.Party result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_Party.toString());
		if (identifier != null)
			result = domdal.proxies.Party.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Person_Party
	 * @param person_party
	 */
	public final void setPerson_Party(domdal.proxies.Party person_party)
	{
		setPerson_Party(getContext(), person_party);
	}

	/**
	 * Set value of Person_Party
	 * @param context
	 * @param person_party
	 */
	public final void setPerson_Party(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.Party person_party)
	{
		if (person_party == null)
			getMendixObject().setValue(context, MemberNames.Person_Party.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Person_Party.toString(), person_party.getMendixObject().getId());
	}

	/**
	 * @return value of Person_HomeAddress
	 */
	public final domdal.proxies.Address getPerson_HomeAddress() throws com.mendix.core.CoreException
	{
		return getPerson_HomeAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_HomeAddress
	 */
	public final domdal.proxies.Address getPerson_HomeAddress(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		domdal.proxies.Address result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_HomeAddress.toString());
		if (identifier != null)
			result = domdal.proxies.Address.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Person_HomeAddress
	 * @param person_homeaddress
	 */
	public final void setPerson_HomeAddress(domdal.proxies.Address person_homeaddress)
	{
		setPerson_HomeAddress(getContext(), person_homeaddress);
	}

	/**
	 * Set value of Person_HomeAddress
	 * @param context
	 * @param person_homeaddress
	 */
	public final void setPerson_HomeAddress(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.Address person_homeaddress)
	{
		if (person_homeaddress == null)
			getMendixObject().setValue(context, MemberNames.Person_HomeAddress.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Person_HomeAddress.toString(), person_homeaddress.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return personMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final domdal.proxies.Person that = (domdal.proxies.Person) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DomDAL.Person";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
