// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package domdal.proxies;

public class Sprints
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sprintsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DomDAL.Sprints";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SprintID("SprintID"),
		Name("Name"),
		HasStories("HasStories"),
		Completed("Completed"),
		IsActiveSprint("IsActiveSprint"),
		Deleted("Deleted"),
		CreationDate("CreationDate"),
		StartDate("StartDate"),
		EndDate("EndDate"),
		IsBacklog("IsBacklog"),
		Sprints_GetSprintsResponse("DomDAL.Sprints_GetSprintsResponse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Sprints(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DomDAL.Sprints"));
	}

	protected Sprints(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sprintsMendixObject)
	{
		if (sprintsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DomDAL.Sprints", sprintsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DomDAL.Sprints");

		this.sprintsMendixObject = sprintsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Sprints.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static domdal.proxies.Sprints initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return domdal.proxies.Sprints.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static domdal.proxies.Sprints initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new domdal.proxies.Sprints(context, mendixObject);
	}

	public static domdal.proxies.Sprints load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return domdal.proxies.Sprints.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SprintID
	 */
	public final java.lang.Long getSprintID()
	{
		return getSprintID(getContext());
	}

	/**
	 * @param context
	 * @return value of SprintID
	 */
	public final java.lang.Long getSprintID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.SprintID.toString());
	}

	/**
	 * Set value of SprintID
	 * @param sprintid
	 */
	public final void setSprintID(java.lang.Long sprintid)
	{
		setSprintID(getContext(), sprintid);
	}

	/**
	 * Set value of SprintID
	 * @param context
	 * @param sprintid
	 */
	public final void setSprintID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long sprintid)
	{
		getMendixObject().setValue(context, MemberNames.SprintID.toString(), sprintid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of HasStories
	 */
	public final java.lang.Boolean getHasStories()
	{
		return getHasStories(getContext());
	}

	/**
	 * @param context
	 * @return value of HasStories
	 */
	public final java.lang.Boolean getHasStories(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasStories.toString());
	}

	/**
	 * Set value of HasStories
	 * @param hasstories
	 */
	public final void setHasStories(java.lang.Boolean hasstories)
	{
		setHasStories(getContext(), hasstories);
	}

	/**
	 * Set value of HasStories
	 * @param context
	 * @param hasstories
	 */
	public final void setHasStories(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasstories)
	{
		getMendixObject().setValue(context, MemberNames.HasStories.toString(), hasstories);
	}

	/**
	 * @return value of Completed
	 */
	public final java.lang.Boolean getCompleted()
	{
		return getCompleted(getContext());
	}

	/**
	 * @param context
	 * @return value of Completed
	 */
	public final java.lang.Boolean getCompleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Completed.toString());
	}

	/**
	 * Set value of Completed
	 * @param completed
	 */
	public final void setCompleted(java.lang.Boolean completed)
	{
		setCompleted(getContext(), completed);
	}

	/**
	 * Set value of Completed
	 * @param context
	 * @param completed
	 */
	public final void setCompleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean completed)
	{
		getMendixObject().setValue(context, MemberNames.Completed.toString(), completed);
	}

	/**
	 * @return value of IsActiveSprint
	 */
	public final java.lang.Boolean getIsActiveSprint()
	{
		return getIsActiveSprint(getContext());
	}

	/**
	 * @param context
	 * @return value of IsActiveSprint
	 */
	public final java.lang.Boolean getIsActiveSprint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsActiveSprint.toString());
	}

	/**
	 * Set value of IsActiveSprint
	 * @param isactivesprint
	 */
	public final void setIsActiveSprint(java.lang.Boolean isactivesprint)
	{
		setIsActiveSprint(getContext(), isactivesprint);
	}

	/**
	 * Set value of IsActiveSprint
	 * @param context
	 * @param isactivesprint
	 */
	public final void setIsActiveSprint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isactivesprint)
	{
		getMendixObject().setValue(context, MemberNames.IsActiveSprint.toString(), isactivesprint);
	}

	/**
	 * @return value of Deleted
	 */
	public final java.lang.Boolean getDeleted()
	{
		return getDeleted(getContext());
	}

	/**
	 * @param context
	 * @return value of Deleted
	 */
	public final java.lang.Boolean getDeleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Deleted.toString());
	}

	/**
	 * Set value of Deleted
	 * @param deleted
	 */
	public final void setDeleted(java.lang.Boolean deleted)
	{
		setDeleted(getContext(), deleted);
	}

	/**
	 * Set value of Deleted
	 * @param context
	 * @param deleted
	 */
	public final void setDeleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean deleted)
	{
		getMendixObject().setValue(context, MemberNames.Deleted.toString(), deleted);
	}

	/**
	 * @return value of CreationDate
	 */
	public final java.util.Date getCreationDate()
	{
		return getCreationDate(getContext());
	}

	/**
	 * @param context
	 * @return value of CreationDate
	 */
	public final java.util.Date getCreationDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreationDate.toString());
	}

	/**
	 * Set value of CreationDate
	 * @param creationdate
	 */
	public final void setCreationDate(java.util.Date creationdate)
	{
		setCreationDate(getContext(), creationdate);
	}

	/**
	 * Set value of CreationDate
	 * @param context
	 * @param creationdate
	 */
	public final void setCreationDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date creationdate)
	{
		getMendixObject().setValue(context, MemberNames.CreationDate.toString(), creationdate);
	}

	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * @return value of IsBacklog
	 */
	public final java.lang.Boolean getIsBacklog()
	{
		return getIsBacklog(getContext());
	}

	/**
	 * @param context
	 * @return value of IsBacklog
	 */
	public final java.lang.Boolean getIsBacklog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsBacklog.toString());
	}

	/**
	 * Set value of IsBacklog
	 * @param isbacklog
	 */
	public final void setIsBacklog(java.lang.Boolean isbacklog)
	{
		setIsBacklog(getContext(), isbacklog);
	}

	/**
	 * Set value of IsBacklog
	 * @param context
	 * @param isbacklog
	 */
	public final void setIsBacklog(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isbacklog)
	{
		getMendixObject().setValue(context, MemberNames.IsBacklog.toString(), isbacklog);
	}

	/**
	 * @return value of Sprints_GetSprintsResponse
	 */
	public final domdal.proxies.GetSprintsResponse getSprints_GetSprintsResponse() throws com.mendix.core.CoreException
	{
		return getSprints_GetSprintsResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of Sprints_GetSprintsResponse
	 */
	public final domdal.proxies.GetSprintsResponse getSprints_GetSprintsResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		domdal.proxies.GetSprintsResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sprints_GetSprintsResponse.toString());
		if (identifier != null)
			result = domdal.proxies.GetSprintsResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Sprints_GetSprintsResponse
	 * @param sprints_getsprintsresponse
	 */
	public final void setSprints_GetSprintsResponse(domdal.proxies.GetSprintsResponse sprints_getsprintsresponse)
	{
		setSprints_GetSprintsResponse(getContext(), sprints_getsprintsresponse);
	}

	/**
	 * Set value of Sprints_GetSprintsResponse
	 * @param context
	 * @param sprints_getsprintsresponse
	 */
	public final void setSprints_GetSprintsResponse(com.mendix.systemwideinterfaces.core.IContext context, domdal.proxies.GetSprintsResponse sprints_getsprintsresponse)
	{
		if (sprints_getsprintsresponse == null)
			getMendixObject().setValue(context, MemberNames.Sprints_GetSprintsResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Sprints_GetSprintsResponse.toString(), sprints_getsprintsresponse.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sprintsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final domdal.proxies.Sprints that = (domdal.proxies.Sprints) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DomDAL.Sprints";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
