// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package test.proxies;

public class FibonacciPageHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject fibonacciPageHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "test.FibonacciPageHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InputInteger("InputInteger"),
		OutputString("OutputString");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FibonacciPageHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "test.FibonacciPageHelper"));
	}

	protected FibonacciPageHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fibonacciPageHelperMendixObject)
	{
		if (fibonacciPageHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("test.FibonacciPageHelper", fibonacciPageHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a test.FibonacciPageHelper");

		this.fibonacciPageHelperMendixObject = fibonacciPageHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'FibonacciPageHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static test.proxies.FibonacciPageHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return test.proxies.FibonacciPageHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static test.proxies.FibonacciPageHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new test.proxies.FibonacciPageHelper(context, mendixObject);
	}

	public static test.proxies.FibonacciPageHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return test.proxies.FibonacciPageHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of InputInteger
	 */
	public final java.lang.Integer getInputInteger()
	{
		return getInputInteger(getContext());
	}

	/**
	 * @param context
	 * @return value of InputInteger
	 */
	public final java.lang.Integer getInputInteger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.InputInteger.toString());
	}

	/**
	 * Set value of InputInteger
	 * @param inputinteger
	 */
	public final void setInputInteger(java.lang.Integer inputinteger)
	{
		setInputInteger(getContext(), inputinteger);
	}

	/**
	 * Set value of InputInteger
	 * @param context
	 * @param inputinteger
	 */
	public final void setInputInteger(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer inputinteger)
	{
		getMendixObject().setValue(context, MemberNames.InputInteger.toString(), inputinteger);
	}

	/**
	 * @return value of OutputString
	 */
	public final java.lang.String getOutputString()
	{
		return getOutputString(getContext());
	}

	/**
	 * @param context
	 * @return value of OutputString
	 */
	public final java.lang.String getOutputString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OutputString.toString());
	}

	/**
	 * Set value of OutputString
	 * @param outputstring
	 */
	public final void setOutputString(java.lang.String outputstring)
	{
		setOutputString(getContext(), outputstring);
	}

	/**
	 * Set value of OutputString
	 * @param context
	 * @param outputstring
	 */
	public final void setOutputString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String outputstring)
	{
		getMendixObject().setValue(context, MemberNames.OutputString.toString(), outputstring);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return fibonacciPageHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final test.proxies.FibonacciPageHelper that = (test.proxies.FibonacciPageHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "test.FibonacciPageHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
