// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package test.proxies;

public class Fibonacci
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject fibonacciMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "test.Fibonacci";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Serie("Serie"),
		_1Ago("_1Ago"),
		_2Ago("_2Ago"),
		Counter("Counter");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Fibonacci(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "test.Fibonacci"));
	}

	protected Fibonacci(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fibonacciMendixObject)
	{
		if (fibonacciMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("test.Fibonacci", fibonacciMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a test.Fibonacci");

		this.fibonacciMendixObject = fibonacciMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Fibonacci.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static test.proxies.Fibonacci initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return test.proxies.Fibonacci.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static test.proxies.Fibonacci initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new test.proxies.Fibonacci(context, mendixObject);
	}

	public static test.proxies.Fibonacci load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return test.proxies.Fibonacci.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Serie
	 */
	public final java.lang.String getSerie()
	{
		return getSerie(getContext());
	}

	/**
	 * @param context
	 * @return value of Serie
	 */
	public final java.lang.String getSerie(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Serie.toString());
	}

	/**
	 * Set value of Serie
	 * @param serie
	 */
	public final void setSerie(java.lang.String serie)
	{
		setSerie(getContext(), serie);
	}

	/**
	 * Set value of Serie
	 * @param context
	 * @param serie
	 */
	public final void setSerie(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serie)
	{
		getMendixObject().setValue(context, MemberNames.Serie.toString(), serie);
	}

	/**
	 * @return value of _1Ago
	 */
	public final java.lang.Long get_1Ago()
	{
		return get_1Ago(getContext());
	}

	/**
	 * @param context
	 * @return value of _1Ago
	 */
	public final java.lang.Long get_1Ago(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames._1Ago.toString());
	}

	/**
	 * Set value of _1Ago
	 * @param _1ago
	 */
	public final void set_1Ago(java.lang.Long _1ago)
	{
		set_1Ago(getContext(), _1ago);
	}

	/**
	 * Set value of _1Ago
	 * @param context
	 * @param _1ago
	 */
	public final void set_1Ago(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long _1ago)
	{
		getMendixObject().setValue(context, MemberNames._1Ago.toString(), _1ago);
	}

	/**
	 * @return value of _2Ago
	 */
	public final java.lang.Long get_2Ago()
	{
		return get_2Ago(getContext());
	}

	/**
	 * @param context
	 * @return value of _2Ago
	 */
	public final java.lang.Long get_2Ago(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames._2Ago.toString());
	}

	/**
	 * Set value of _2Ago
	 * @param _2ago
	 */
	public final void set_2Ago(java.lang.Long _2ago)
	{
		set_2Ago(getContext(), _2ago);
	}

	/**
	 * Set value of _2Ago
	 * @param context
	 * @param _2ago
	 */
	public final void set_2Ago(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long _2ago)
	{
		getMendixObject().setValue(context, MemberNames._2Ago.toString(), _2ago);
	}

	/**
	 * @return value of Counter
	 */
	public final java.lang.Long getCounter()
	{
		return getCounter(getContext());
	}

	/**
	 * @param context
	 * @return value of Counter
	 */
	public final java.lang.Long getCounter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Counter.toString());
	}

	/**
	 * Set value of Counter
	 * @param counter
	 */
	public final void setCounter(java.lang.Long counter)
	{
		setCounter(getContext(), counter);
	}

	/**
	 * Set value of Counter
	 * @param context
	 * @param counter
	 */
	public final void setCounter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long counter)
	{
		getMendixObject().setValue(context, MemberNames.Counter.toString(), counter);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return fibonacciMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final test.proxies.Fibonacci that = (test.proxies.Fibonacci) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "test.Fibonacci";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
