// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package environmentvariables.proxies;

public enum Enum_EnvironmentType
{
	D(new java.lang.String[][] { new java.lang.String[] { "en_US", "Development" } }),
	T(new java.lang.String[][] { new java.lang.String[] { "en_US", "Test" } }),
	A(new java.lang.String[][] { new java.lang.String[] { "en_US", "Acceptation" } }),
	P(new java.lang.String[][] { new java.lang.String[] { "en_US", "Production" } }),
	S(new java.lang.String[][] { new java.lang.String[] { "en_US", "Soak" } }),
	Z(new java.lang.String[][] { new java.lang.String[] { "en_US", "Performance" } }),
	R(new java.lang.String[][] { new java.lang.String[] { "en_US", "Reporting" } }),
	L(new java.lang.String[][] { new java.lang.String[] { "en_US", "Local" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_EnvironmentType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
