// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sales.proxies;

public class Address
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject addressMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Sales.Address";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Street("Street"),
		City("City"),
		Order_Address("Sales.Order_Address"),
		Customer_Address("Sales.Customer_Address");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Address(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Sales.Address"));
	}

	protected Address(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject addressMendixObject)
	{
		if (addressMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Sales.Address", addressMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Sales.Address");

		this.addressMendixObject = addressMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Address.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sales.proxies.Address initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sales.proxies.Address.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sales.proxies.Address initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sales.proxies.Address(context, mendixObject);
	}

	public static sales.proxies.Address load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sales.proxies.Address.initialize(context, mendixObject);
	}

	public static java.util.List<sales.proxies.Address> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<sales.proxies.Address> result = new java.util.ArrayList<sales.proxies.Address>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Sales.Address" + xpathConstraint))
			result.add(sales.proxies.Address.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Street
	 */
	public final java.lang.String getStreet()
	{
		return getStreet(getContext());
	}

	/**
	 * @param context
	 * @return value of Street
	 */
	public final java.lang.String getStreet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Street.toString());
	}

	/**
	 * Set value of Street
	 * @param street
	 */
	public final void setStreet(java.lang.String street)
	{
		setStreet(getContext(), street);
	}

	/**
	 * Set value of Street
	 * @param context
	 * @param street
	 */
	public final void setStreet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String street)
	{
		getMendixObject().setValue(context, MemberNames.Street.toString(), street);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of Order_Address
	 */
	public final sales.proxies.Order getOrder_Address() throws com.mendix.core.CoreException
	{
		return getOrder_Address(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_Address
	 */
	public final sales.proxies.Order getOrder_Address(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sales.proxies.Order result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_Address.toString());
		if (identifier != null)
			result = sales.proxies.Order.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Order_Address
	 * @param order_address
	 */
	public final void setOrder_Address(sales.proxies.Order order_address)
	{
		setOrder_Address(getContext(), order_address);
	}

	/**
	 * Set value of Order_Address
	 * @param context
	 * @param order_address
	 */
	public final void setOrder_Address(com.mendix.systemwideinterfaces.core.IContext context, sales.proxies.Order order_address)
	{
		if (order_address == null)
			getMendixObject().setValue(context, MemberNames.Order_Address.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Order_Address.toString(), order_address.getMendixObject().getId());
	}

	/**
	 * @return value of Customer_Address
	 */
	public final sales.proxies.Customer getCustomer_Address() throws com.mendix.core.CoreException
	{
		return getCustomer_Address(getContext());
	}

	/**
	 * @param context
	 * @return value of Customer_Address
	 */
	public final sales.proxies.Customer getCustomer_Address(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sales.proxies.Customer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Customer_Address.toString());
		if (identifier != null)
			result = sales.proxies.Customer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Customer_Address
	 * @param customer_address
	 */
	public final void setCustomer_Address(sales.proxies.Customer customer_address)
	{
		setCustomer_Address(getContext(), customer_address);
	}

	/**
	 * Set value of Customer_Address
	 * @param context
	 * @param customer_address
	 */
	public final void setCustomer_Address(com.mendix.systemwideinterfaces.core.IContext context, sales.proxies.Customer customer_address)
	{
		if (customer_address == null)
			getMendixObject().setValue(context, MemberNames.Customer_Address.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Customer_Address.toString(), customer_address.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return addressMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sales.proxies.Address that = (sales.proxies.Address) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Sales.Address";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
