// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * This action will make the cursor scroll to the selected page element: 
 * - Top
 * - Botom
 * - Any anchor. 
 * 
 * If scrolling is set to got to an anchor, the name of the anchor needs to be provided in the second parameter 'TargetAnchor'.
 * @param {"MyDemoVersion8.Enum_ScrollTo.Top"|"MyDemoVersion8.Enum_ScrollTo.Bottom"|"MyDemoVersion8.Enum_ScrollTo.Anchor"} location - Where does the cursor need to go?
 * @param {string} targetAnchor - The anchor that the cursor needs to scroll to. If not found, it will scroll to the top of the page.
 * @returns {Promise.<boolean>}
 */
export async function JS_ScrollToPageElement(location, targetAnchor) {
	// BEGIN USER CODE
	alert (location.valueOf)
	if(location.valueOf == 'Top'){
		 $(document).ready(function(){
			$(window).scrollTop(0);
		});
	} else if(location.valueOf == 'Bottom'){
		 $(document).ready(function(){
			$(window).scrollTop(0);
		});
	}
	// END USER CODE
}
