// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oql.proxies;

public class Query
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject queryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OQL.Query";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OQL("OQL"),
		CSV("CSV"),
		ShowAs("ShowAs");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Query(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "OQL.Query"));
	}

	protected Query(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject queryMendixObject)
	{
		if (queryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("OQL.Query", queryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a OQL.Query");

		this.queryMendixObject = queryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Query.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static oql.proxies.Query initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return oql.proxies.Query.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static oql.proxies.Query initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new oql.proxies.Query(context, mendixObject);
	}

	public static oql.proxies.Query load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return oql.proxies.Query.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OQL
	 */
	public final java.lang.String getOQL()
	{
		return getOQL(getContext());
	}

	/**
	 * @param context
	 * @return value of OQL
	 */
	public final java.lang.String getOQL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OQL.toString());
	}

	/**
	 * Set value of OQL
	 * @param oql
	 */
	public final void setOQL(java.lang.String oql)
	{
		setOQL(getContext(), oql);
	}

	/**
	 * Set value of OQL
	 * @param context
	 * @param oql
	 */
	public final void setOQL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oql)
	{
		getMendixObject().setValue(context, MemberNames.OQL.toString(), oql);
	}

	/**
	 * @return value of CSV
	 */
	public final java.lang.String getCSV()
	{
		return getCSV(getContext());
	}

	/**
	 * @param context
	 * @return value of CSV
	 */
	public final java.lang.String getCSV(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CSV.toString());
	}

	/**
	 * Set value of CSV
	 * @param csv
	 */
	public final void setCSV(java.lang.String csv)
	{
		setCSV(getContext(), csv);
	}

	/**
	 * Set value of CSV
	 * @param context
	 * @param csv
	 */
	public final void setCSV(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String csv)
	{
		getMendixObject().setValue(context, MemberNames.CSV.toString(), csv);
	}

	/**
	 * Set value of ShowAs
	 * @param showas
	 */
	public final oql.proxies.ShowAs getShowAs()
	{
		return getShowAs(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAs
	 */
	public final oql.proxies.ShowAs getShowAs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ShowAs.toString());
		if (obj == null)
			return null;

		return oql.proxies.ShowAs.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ShowAs
	 * @param showas
	 */
	public final void setShowAs(oql.proxies.ShowAs showas)
	{
		setShowAs(getContext(), showas);
	}

	/**
	 * Set value of ShowAs
	 * @param context
	 * @param showas
	 */
	public final void setShowAs(com.mendix.systemwideinterfaces.core.IContext context, oql.proxies.ShowAs showas)
	{
		if (showas != null)
			getMendixObject().setValue(context, MemberNames.ShowAs.toString(), showas.toString());
		else
			getMendixObject().setValue(context, MemberNames.ShowAs.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return queryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final oql.proxies.Query that = (oql.proxies.Query) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "OQL.Query";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
