// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<boolean>}
 */
export async function JS_GetObjectListFromArray() {
	// BEGIN USER CODE
	//Inspired by https://forum.mendixcloud.com/link/questions/96386
	function getList() 	{
		var phrases = ["Phrase", "Phrase2", "Phrase3", "Phrase4"];
		return Promise.all(phrases.map((phrase) => createObject(phrase)));
	}

	function createObject(text) {
		return new Promise((resolve, reject) => {
			mx.data.create({
				entity: "MyFirstModule.Phrase",
				callback: function(mxObject) {
					mxObject.set("Text", text);
					resolve(mxObject);
				},
				error: function(e) {
					reject("Could not create object:" + error.message);
				}
			});
		});
	}
	throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
