// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mflistviewsort.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MFListViewSort module
	public static void dS_Animal_Create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MFListViewSort.DS_Animal_Create").withParams(params).execute(context);
	}
	public static mflistviewsort.proxies.SortHelper dS_SortHelper(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MFListViewSort.DS_SortHelper").withParams(params).execute(context);
		return result == null ? null : mflistviewsort.proxies.SortHelper.initialize(context, result);
	}
	public static java.util.List<mflistviewsort.proxies.Animal> dSL_Animals(IContext context, mflistviewsort.proxies.SortHelper _sortHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SortHelper", _sortHelper == null ? null : _sortHelper.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MFListViewSort.DSL_Animals").withParams(params).execute(context);
		java.util.List<mflistviewsort.proxies.Animal> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(mflistviewsort.proxies.Animal.initialize(context, obj));
		}
		return result;
	}
}