// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package appstoreappdemos.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the AppstoreAppDemos module
	public static void aCT_MyThing_GeneratePDF(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AppstoreAppDemos.ACT_MyThing_GeneratePDF").withParams(params).execute(context);
	}
	public static boolean bCo_DateTimeRange_CopyFromDateToUntilDate(IContext context, appstoreappdemos.proxies.DateTimeRange _dateTimeRange)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DateTimeRange", _dateTimeRange == null ? null : _dateTimeRange.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("AppstoreAppDemos.BCo_DateTimeRange_CopyFromDateToUntilDate").withParams(params).execute(context);
	}
	public static appstoreappdemos.proxies.MyBarcode dS_BarcodeTypeCode39(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AppstoreAppDemos.DS_BarcodeTypeCode39").withParams(params).execute(context);
		return result == null ? null : appstoreappdemos.proxies.MyBarcode.initialize(context, result);
	}
	public static appstoreappdemos.proxies.CompletenessPercentage dS_CompletenessPercentage_GetFromAddress(IContext context, domdal.proxies.Address _address)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Address", _address == null ? null : _address.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("AppstoreAppDemos.DS_CompletenessPercentage_GetFromAddress").withParams(params).execute(context);
		return result == null ? null : appstoreappdemos.proxies.CompletenessPercentage.initialize(context, result);
	}
	public static appstoreappdemos.proxies.DateRange dS_DateRange(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AppstoreAppDemos.DS_DateRange").withParams(params).execute(context);
		return result == null ? null : appstoreappdemos.proxies.DateRange.initialize(context, result);
	}
	public static appstoreappdemos.proxies.DateTimeRange dS_DateTimerange_GetOrCreate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AppstoreAppDemos.DS_DateTimerange_GetOrCreate").withParams(params).execute(context);
		return result == null ? null : appstoreappdemos.proxies.DateTimeRange.initialize(context, result);
	}
	public static appstoreappdemos.proxies.MyThing dS_MyThing_Create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AppstoreAppDemos.DS_MyThing_Create").withParams(params).execute(context);
		return result == null ? null : appstoreappdemos.proxies.MyThing.initialize(context, result);
	}
	public static appstoreappdemos.proxies.Webcam dS_Video_GetAYoutube(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AppstoreAppDemos.DS_Video_GetAYoutube").withParams(params).execute(context);
		return result == null ? null : appstoreappdemos.proxies.Webcam.initialize(context, result);
	}
	public static void label_AfterCreateByLabelSelectorWidget(IContext context, appstoreappdemos.proxies.Webcam _webcam)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Webcam", _webcam == null ? null : _webcam.getMendixObject());
		Core.microflowCall("AppstoreAppDemos.Label_AfterCreateByLabelSelectorWidget").withParams(params).execute(context);
	}
	public static void label_OnChangeByLabelSelectorWidget(IContext context, appstoreappdemos.proxies.Webcam _webcam)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Webcam", _webcam == null ? null : _webcam.getMendixObject());
		Core.microflowCall("AppstoreAppDemos.Label_OnChangeByLabelSelectorWidget").withParams(params).execute(context);
	}
	public static void lineChart_GetData(IContext context, appstoreappdemos.proxies.DateRange _dateRange)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DateRange", _dateRange == null ? null : _dateRange.getMendixObject());
		Core.microflowCall("AppstoreAppDemos.LineChart_GetData").withParams(params).execute(context);
	}
	public static charts.proxies.ChartNP lineChart_GetData_2(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AppstoreAppDemos.LineChart_GetData_2").withParams(params).execute(context);
		return result == null ? null : charts.proxies.ChartNP.initialize(context, result);
	}
	public static void oCh_DateTimeRange_Save(IContext context, appstoreappdemos.proxies.DateTimeRange _dateTimeRange)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DateTimeRange", _dateTimeRange == null ? null : _dateTimeRange.getMendixObject());
		Core.microflowCall("AppstoreAppDemos.OCh_DateTimeRange_Save").withParams(params).execute(context);
	}
	public static void person_DoALotInParallel(IContext context, java.util.List<domdal.proxies.Person> _personList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_personList = null;
		if (_personList != null)
		{
			listparam_personList = new java.util.ArrayList<>();
			for (domdal.proxies.Person obj : _personList)
				listparam_personList.add(obj.getMendixObject());
		}
		params.put("PersonList", listparam_personList);

		Core.microflowCall("AppstoreAppDemos.Person_DoALotInParallel").withParams(params).execute(context);
	}
	public static void person_DoALotSerially(IContext context, java.util.List<domdal.proxies.Person> _personList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_personList = null;
		if (_personList != null)
		{
			listparam_personList = new java.util.ArrayList<>();
			for (domdal.proxies.Person obj : _personList)
				listparam_personList.add(obj.getMendixObject());
		}
		params.put("PersonList", listparam_personList);

		Core.microflowCall("AppstoreAppDemos.Person_DoALotSerially").withParams(params).execute(context);
	}
	public static void person_KeepsMeBusy(IContext context, domdal.proxies.Person _person)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Person", _person == null ? null : _person.getMendixObject());
		Core.microflowCall("AppstoreAppDemos.Person_KeepsMeBusy").withParams(params).execute(context);
	}
	public static void person_NetWorth_Show(IContext context, domdal.proxies.Person _person)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Person", _person == null ? null : _person.getMendixObject());
		Core.microflowCall("AppstoreAppDemos.Person_NetWorth_Show").withParams(params).execute(context);
	}
	public static appstoreappdemos.proxies.MyBarcode sUB_Barcode_GetOrCreate(IContext context, appstoreappdemos.proxies.MyThing _myThing)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MyThing", _myThing == null ? null : _myThing.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("AppstoreAppDemos.SUB_Barcode_GetOrCreate").withParams(params).execute(context);
		return result == null ? null : appstoreappdemos.proxies.MyBarcode.initialize(context, result);
	}
	public static void sUB_Barcode_RegenerateBarcode(IContext context, appstoreappdemos.proxies.MyThing _myThing)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MyThing", _myThing == null ? null : _myThing.getMendixObject());
		Core.microflowCall("AppstoreAppDemos.SUB_Barcode_RegenerateBarcode").withParams(params).execute(context);
	}
	public static java.util.Date sUB_DateTimeRange_GetTodaysDate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.util.Date) Core.microflowCall("AppstoreAppDemos.SUB_DateTimeRange_GetTodaysDate").withParams(params).execute(context);
	}
	public static void sUB_Deeplink_App(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AppstoreAppDemos.SUB_Deeplink_App").withParams(params).execute(context);
	}
	public static void sUB_Temperature_CalcFKRaRe(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AppstoreAppDemos.SUB_Temperature_CalcFKRaRe").withParams(params).execute(context);
	}
	public static boolean sUB_Webcam_AddBase64DecodeToFile(IContext context, appstoreappdemos.proxies.Webcam _webcam)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Webcam", _webcam == null ? null : _webcam.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("AppstoreAppDemos.SUB_Webcam_AddBase64DecodeToFile").withParams(params).execute(context);
	}
	public static java.util.List<appstoreappdemos.proxies.MyThing> tempDS_GetSome(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("AppstoreAppDemos.tempDS_GetSome").withParams(params).execute(context);
		java.util.List<appstoreappdemos.proxies.MyThing> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(appstoreappdemos.proxies.MyThing.initialize(context, obj));
		}
		return result;
	}
	public static void test_BCo_DateTimeRange_CopyFromDateToUntilDate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AppstoreAppDemos.test_BCo_DateTimeRange_CopyFromDateToUntilDate").withParams(params).execute(context);
	}
}