// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package domdal.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DomDAL module
	public static domdal.proxies.Party dS_Party_GetOne(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DomDAL.DS_Party_GetOne").withParams(params).execute(context);
		return result == null ? null : domdal.proxies.Party.initialize(context, result);
	}
	public static java.util.List<domdal.proxies.Person> dS_Person_GetAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("DomDAL.DS_Person_GetAll").withParams(params).execute(context);
		java.util.List<domdal.proxies.Person> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(domdal.proxies.Person.initialize(context, obj));
		}
		return result;
	}
	public static void sUB_DateTimePlanned_CopyFromRealized(IContext context, java.util.List<domdal.proxies.DailyTimePlanned> _dailyTimePlanned)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_dailyTimePlanned = null;
		if (_dailyTimePlanned != null)
		{
			listparam_dailyTimePlanned = new java.util.ArrayList<>();
			for (domdal.proxies.DailyTimePlanned obj : _dailyTimePlanned)
				listparam_dailyTimePlanned.add(obj.getMendixObject());
		}
		params.put("DailyTimePlanned", listparam_dailyTimePlanned);

		Core.microflowCall("DomDAL.SUB_DateTimePlanned_CopyFromRealized").withParams(params).execute(context);
	}
	public static java.util.List<domdal.proxies.DailyTimeRealized> sUB_TimeSheet_GetHoursToSignOff(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("DomDAL.SUB_TimeSheet_GetHoursToSignOff").withParams(params).execute(context);
		java.util.List<domdal.proxies.DailyTimeRealized> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(domdal.proxies.DailyTimeRealized.initialize(context, obj));
		}
		return result;
	}
}