// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mydemoversion8.proxies;

public enum Enum_ScrollTo
{
	Top(new java.lang.String[][] { new java.lang.String[] { "en_US", "Top" } }),
	Bottom(new java.lang.String[][] { new java.lang.String[] { "en_US", "Bottom" } }),
	Anchor(new java.lang.String[][] { new java.lang.String[] { "en_US", "Anchor" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_ScrollTo(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
