// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oql.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the OQL module
	public static void aCT_ExecuteOQL(IContext context, oql.proxies.Query _query)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Query", _query == null ? null : _query.getMendixObject());
		Core.microflowCall("OQL.ACT_ExecuteOQL").withParams(params).execute(context);
	}
	public static java.util.List<oql.proxies.ExamplePersonResult> dS_ExampleOQL(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("OQL.DS_ExampleOQL").withParams(params).execute(context);
		java.util.List<oql.proxies.ExamplePersonResult> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(oql.proxies.ExamplePersonResult.initialize(context, obj));
		}
		return result;
	}
	public static oql.proxies.Query dS_GetQuery(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("OQL.DS_GetQuery").withParams(params).execute(context);
		return result == null ? null : oql.proxies.Query.initialize(context, result);
	}
	public static void iVK_CreateContent(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("OQL.IVK_CreateContent").withParams(params).execute(context);
	}
	public static void iVK_PerformTests(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("OQL.IVK_PerformTests").withParams(params).execute(context);
	}
	public static void iVK_TestCount(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("OQL.IVK_TestCount").withParams(params).execute(context);
	}
}