// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package functionfiddler.proxies;

public class FormatDateTimeResult
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject formatDateTimeResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FunctionFiddler.FormatDateTimeResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DateTime("DateTime"),
		FormatString("FormatString"),
		ResultString("ResultString"),
		Error("Error"),
		ErrorMessage("ErrorMessage");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FormatDateTimeResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "FunctionFiddler.FormatDateTimeResult"));
	}

	protected FormatDateTimeResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject formatDateTimeResultMendixObject)
	{
		if (formatDateTimeResultMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("FunctionFiddler.FormatDateTimeResult", formatDateTimeResultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a FunctionFiddler.FormatDateTimeResult");

		this.formatDateTimeResultMendixObject = formatDateTimeResultMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'FormatDateTimeResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static functionfiddler.proxies.FormatDateTimeResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return functionfiddler.proxies.FormatDateTimeResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static functionfiddler.proxies.FormatDateTimeResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new functionfiddler.proxies.FormatDateTimeResult(context, mendixObject);
	}

	public static functionfiddler.proxies.FormatDateTimeResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return functionfiddler.proxies.FormatDateTimeResult.initialize(context, mendixObject);
	}

	public static java.util.List<functionfiddler.proxies.FormatDateTimeResult> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<functionfiddler.proxies.FormatDateTimeResult> result = new java.util.ArrayList<functionfiddler.proxies.FormatDateTimeResult>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//FunctionFiddler.FormatDateTimeResult" + xpathConstraint))
			result.add(functionfiddler.proxies.FormatDateTimeResult.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DateTime
	 */
	public final java.util.Date getDateTime()
	{
		return getDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTime
	 */
	public final java.util.Date getDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTime.toString());
	}

	/**
	 * Set value of DateTime
	 * @param datetime
	 */
	public final void setDateTime(java.util.Date datetime)
	{
		setDateTime(getContext(), datetime);
	}

	/**
	 * Set value of DateTime
	 * @param context
	 * @param datetime
	 */
	public final void setDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetime)
	{
		getMendixObject().setValue(context, MemberNames.DateTime.toString(), datetime);
	}

	/**
	 * @return value of FormatString
	 */
	public final java.lang.String getFormatString()
	{
		return getFormatString(getContext());
	}

	/**
	 * @param context
	 * @return value of FormatString
	 */
	public final java.lang.String getFormatString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FormatString.toString());
	}

	/**
	 * Set value of FormatString
	 * @param formatstring
	 */
	public final void setFormatString(java.lang.String formatstring)
	{
		setFormatString(getContext(), formatstring);
	}

	/**
	 * Set value of FormatString
	 * @param context
	 * @param formatstring
	 */
	public final void setFormatString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String formatstring)
	{
		getMendixObject().setValue(context, MemberNames.FormatString.toString(), formatstring);
	}

	/**
	 * @return value of ResultString
	 */
	public final java.lang.String getResultString()
	{
		return getResultString(getContext());
	}

	/**
	 * @param context
	 * @return value of ResultString
	 */
	public final java.lang.String getResultString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResultString.toString());
	}

	/**
	 * Set value of ResultString
	 * @param resultstring
	 */
	public final void setResultString(java.lang.String resultstring)
	{
		setResultString(getContext(), resultstring);
	}

	/**
	 * Set value of ResultString
	 * @param context
	 * @param resultstring
	 */
	public final void setResultString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resultstring)
	{
		getMendixObject().setValue(context, MemberNames.ResultString.toString(), resultstring);
	}

	/**
	 * @return value of Error
	 */
	public final java.lang.Boolean getError()
	{
		return getError(getContext());
	}

	/**
	 * @param context
	 * @return value of Error
	 */
	public final java.lang.Boolean getError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Error.toString());
	}

	/**
	 * Set value of Error
	 * @param error
	 */
	public final void setError(java.lang.Boolean error)
	{
		setError(getContext(), error);
	}

	/**
	 * Set value of Error
	 * @param context
	 * @param error
	 */
	public final void setError(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean error)
	{
		getMendixObject().setValue(context, MemberNames.Error.toString(), error);
	}

	/**
	 * @return value of ErrorMessage
	 */
	public final java.lang.String getErrorMessage()
	{
		return getErrorMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorMessage
	 */
	public final java.lang.String getErrorMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ErrorMessage.toString());
	}

	/**
	 * Set value of ErrorMessage
	 * @param errormessage
	 */
	public final void setErrorMessage(java.lang.String errormessage)
	{
		setErrorMessage(getContext(), errormessage);
	}

	/**
	 * Set value of ErrorMessage
	 * @param context
	 * @param errormessage
	 */
	public final void setErrorMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String errormessage)
	{
		getMendixObject().setValue(context, MemberNames.ErrorMessage.toString(), errormessage);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return formatDateTimeResultMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final functionfiddler.proxies.FormatDateTimeResult that = (functionfiddler.proxies.FormatDateTimeResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "FunctionFiddler.FormatDateTimeResult";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
