// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package functionfiddler.proxies;

/**
 * A string to pass to the parsedatetime-function as second parameter
 */
public class ParseDateTimeParam2
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject parseDateTimeParam2MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FunctionFiddler.ParseDateTimeParam2";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MatchesThisString("MatchesThisString");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ParseDateTimeParam2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "FunctionFiddler.ParseDateTimeParam2"));
	}

	protected ParseDateTimeParam2(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject parseDateTimeParam2MendixObject)
	{
		if (parseDateTimeParam2MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("FunctionFiddler.ParseDateTimeParam2", parseDateTimeParam2MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a FunctionFiddler.ParseDateTimeParam2");

		this.parseDateTimeParam2MendixObject = parseDateTimeParam2MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ParseDateTimeParam2.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static functionfiddler.proxies.ParseDateTimeParam2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return functionfiddler.proxies.ParseDateTimeParam2.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static functionfiddler.proxies.ParseDateTimeParam2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new functionfiddler.proxies.ParseDateTimeParam2(context, mendixObject);
	}

	public static functionfiddler.proxies.ParseDateTimeParam2 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return functionfiddler.proxies.ParseDateTimeParam2.initialize(context, mendixObject);
	}

	public static java.util.List<functionfiddler.proxies.ParseDateTimeParam2> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<functionfiddler.proxies.ParseDateTimeParam2> result = new java.util.ArrayList<functionfiddler.proxies.ParseDateTimeParam2>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//FunctionFiddler.ParseDateTimeParam2" + xpathConstraint))
			result.add(functionfiddler.proxies.ParseDateTimeParam2.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MatchesThisString
	 */
	public final java.lang.String getMatchesThisString()
	{
		return getMatchesThisString(getContext());
	}

	/**
	 * @param context
	 * @return value of MatchesThisString
	 */
	public final java.lang.String getMatchesThisString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MatchesThisString.toString());
	}

	/**
	 * Set value of MatchesThisString
	 * @param matchesthisstring
	 */
	public final void setMatchesThisString(java.lang.String matchesthisstring)
	{
		setMatchesThisString(getContext(), matchesthisstring);
	}

	/**
	 * Set value of MatchesThisString
	 * @param context
	 * @param matchesthisstring
	 */
	public final void setMatchesThisString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String matchesthisstring)
	{
		getMendixObject().setValue(context, MemberNames.MatchesThisString.toString(), matchesthisstring);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return parseDateTimeParam2MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final functionfiddler.proxies.ParseDateTimeParam2 that = (functionfiddler.proxies.ParseDateTimeParam2) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "FunctionFiddler.ParseDateTimeParam2";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
