// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mflistviewsort.proxies;

public class SortHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sortHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MFListViewSort.SortHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sort("Sort"),
		Ascending("Ascending");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SortHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MFListViewSort.SortHelper"));
	}

	protected SortHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sortHelperMendixObject)
	{
		if (sortHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MFListViewSort.SortHelper", sortHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MFListViewSort.SortHelper");

		this.sortHelperMendixObject = sortHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SortHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mflistviewsort.proxies.SortHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mflistviewsort.proxies.SortHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mflistviewsort.proxies.SortHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mflistviewsort.proxies.SortHelper(context, mendixObject);
	}

	public static mflistviewsort.proxies.SortHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mflistviewsort.proxies.SortHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Sort
	 * @param sort
	 */
	public final mflistviewsort.proxies.ENU_SortColumn getSort()
	{
		return getSort(getContext());
	}

	/**
	 * @param context
	 * @return value of Sort
	 */
	public final mflistviewsort.proxies.ENU_SortColumn getSort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Sort.toString());
		if (obj == null)
			return null;

		return mflistviewsort.proxies.ENU_SortColumn.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Sort
	 * @param sort
	 */
	public final void setSort(mflistviewsort.proxies.ENU_SortColumn sort)
	{
		setSort(getContext(), sort);
	}

	/**
	 * Set value of Sort
	 * @param context
	 * @param sort
	 */
	public final void setSort(com.mendix.systemwideinterfaces.core.IContext context, mflistviewsort.proxies.ENU_SortColumn sort)
	{
		if (sort != null)
			getMendixObject().setValue(context, MemberNames.Sort.toString(), sort.toString());
		else
			getMendixObject().setValue(context, MemberNames.Sort.toString(), null);
	}

	/**
	 * @return value of Ascending
	 */
	public final java.lang.Boolean getAscending()
	{
		return getAscending(getContext());
	}

	/**
	 * @param context
	 * @return value of Ascending
	 */
	public final java.lang.Boolean getAscending(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Ascending.toString());
	}

	/**
	 * Set value of Ascending
	 * @param ascending
	 */
	public final void setAscending(java.lang.Boolean ascending)
	{
		setAscending(getContext(), ascending);
	}

	/**
	 * Set value of Ascending
	 * @param context
	 * @param ascending
	 */
	public final void setAscending(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ascending)
	{
		getMendixObject().setValue(context, MemberNames.Ascending.toString(), ascending);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sortHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mflistviewsort.proxies.SortHelper that = (mflistviewsort.proxies.SortHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MFListViewSort.SortHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
