// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package countriesv5.proxies;

public class CountryModuleSettings
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject countryModuleSettingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CountriesV5.CountryModuleSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CreateDutchNENTable("CreateDutchNENTable");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CountryModuleSettings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CountriesV5.CountryModuleSettings"));
	}

	protected CountryModuleSettings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject countryModuleSettingsMendixObject)
	{
		if (countryModuleSettingsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CountriesV5.CountryModuleSettings", countryModuleSettingsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CountriesV5.CountryModuleSettings");

		this.countryModuleSettingsMendixObject = countryModuleSettingsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CountryModuleSettings.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static countriesv5.proxies.CountryModuleSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return countriesv5.proxies.CountryModuleSettings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static countriesv5.proxies.CountryModuleSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new countriesv5.proxies.CountryModuleSettings(context, mendixObject);
	}

	public static countriesv5.proxies.CountryModuleSettings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return countriesv5.proxies.CountryModuleSettings.initialize(context, mendixObject);
	}

	public static java.util.List<countriesv5.proxies.CountryModuleSettings> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<countriesv5.proxies.CountryModuleSettings> result = new java.util.ArrayList<countriesv5.proxies.CountryModuleSettings>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CountriesV5.CountryModuleSettings" + xpathConstraint))
			result.add(countriesv5.proxies.CountryModuleSettings.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CreateDutchNENTable
	 */
	public final java.lang.Boolean getCreateDutchNENTable()
	{
		return getCreateDutchNENTable(getContext());
	}

	/**
	 * @param context
	 * @return value of CreateDutchNENTable
	 */
	public final java.lang.Boolean getCreateDutchNENTable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CreateDutchNENTable.toString());
	}

	/**
	 * Set value of CreateDutchNENTable
	 * @param createdutchnentable
	 */
	public final void setCreateDutchNENTable(java.lang.Boolean createdutchnentable)
	{
		setCreateDutchNENTable(getContext(), createdutchnentable);
	}

	/**
	 * Set value of CreateDutchNENTable
	 * @param context
	 * @param createdutchnentable
	 */
	public final void setCreateDutchNENTable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean createdutchnentable)
	{
		getMendixObject().setValue(context, MemberNames.CreateDutchNENTable.toString(), createdutchnentable);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return countryModuleSettingsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final countriesv5.proxies.CountryModuleSettings that = (countriesv5.proxies.CountryModuleSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CountriesV5.CountryModuleSettings";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
