// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package countriesv5.proxies;

public class Demonym
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject demonymMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CountriesV5.Demonym";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CountryKey("CountryKey"),
		Description("Description"),
		TranslationDemonym("TranslationDemonym"),
		Demonym_Country_ISO3166_1("CountriesV5.Demonym_Country_ISO3166_1");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Demonym(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CountriesV5.Demonym"));
	}

	protected Demonym(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject demonymMendixObject)
	{
		if (demonymMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CountriesV5.Demonym", demonymMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CountriesV5.Demonym");

		this.demonymMendixObject = demonymMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Demonym.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static countriesv5.proxies.Demonym initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return countriesv5.proxies.Demonym.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static countriesv5.proxies.Demonym initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new countriesv5.proxies.Demonym(context, mendixObject);
	}

	public static countriesv5.proxies.Demonym load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return countriesv5.proxies.Demonym.initialize(context, mendixObject);
	}

	public static java.util.List<countriesv5.proxies.Demonym> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<countriesv5.proxies.Demonym> result = new java.util.ArrayList<countriesv5.proxies.Demonym>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CountriesV5.Demonym" + xpathConstraint))
			result.add(countriesv5.proxies.Demonym.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of CountryKey
	 * @param countrykey
	 */
	public final countriesv5.proxies.Countries getCountryKey()
	{
		return getCountryKey(getContext());
	}

	/**
	 * @param context
	 * @return value of CountryKey
	 */
	public final countriesv5.proxies.Countries getCountryKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CountryKey.toString());
		if (obj == null)
			return null;

		return countriesv5.proxies.Countries.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CountryKey
	 * @param countrykey
	 */
	public final void setCountryKey(countriesv5.proxies.Countries countrykey)
	{
		setCountryKey(getContext(), countrykey);
	}

	/**
	 * Set value of CountryKey
	 * @param context
	 * @param countrykey
	 */
	public final void setCountryKey(com.mendix.systemwideinterfaces.core.IContext context, countriesv5.proxies.Countries countrykey)
	{
		if (countrykey != null)
			getMendixObject().setValue(context, MemberNames.CountryKey.toString(), countrykey.toString());
		else
			getMendixObject().setValue(context, MemberNames.CountryKey.toString(), null);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of TranslationDemonym
	 */
	public final java.lang.String getTranslationDemonym()
	{
		return getTranslationDemonym(getContext());
	}

	/**
	 * @param context
	 * @return value of TranslationDemonym
	 */
	public final java.lang.String getTranslationDemonym(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TranslationDemonym.toString());
	}

	/**
	 * Set value of TranslationDemonym
	 * @param translationdemonym
	 */
	public final void setTranslationDemonym(java.lang.String translationdemonym)
	{
		setTranslationDemonym(getContext(), translationdemonym);
	}

	/**
	 * Set value of TranslationDemonym
	 * @param context
	 * @param translationdemonym
	 */
	public final void setTranslationDemonym(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String translationdemonym)
	{
		getMendixObject().setValue(context, MemberNames.TranslationDemonym.toString(), translationdemonym);
	}

	/**
	 * @return value of Demonym_Country_ISO3166_1
	 */
	public final countriesv5.proxies.Country_ISO3166_1 getDemonym_Country_ISO3166_1() throws com.mendix.core.CoreException
	{
		return getDemonym_Country_ISO3166_1(getContext());
	}

	/**
	 * @param context
	 * @return value of Demonym_Country_ISO3166_1
	 */
	public final countriesv5.proxies.Country_ISO3166_1 getDemonym_Country_ISO3166_1(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		countriesv5.proxies.Country_ISO3166_1 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Demonym_Country_ISO3166_1.toString());
		if (identifier != null)
			result = countriesv5.proxies.Country_ISO3166_1.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Demonym_Country_ISO3166_1
	 * @param demonym_country_iso3166_1
	 */
	public final void setDemonym_Country_ISO3166_1(countriesv5.proxies.Country_ISO3166_1 demonym_country_iso3166_1)
	{
		setDemonym_Country_ISO3166_1(getContext(), demonym_country_iso3166_1);
	}

	/**
	 * Set value of Demonym_Country_ISO3166_1
	 * @param context
	 * @param demonym_country_iso3166_1
	 */
	public final void setDemonym_Country_ISO3166_1(com.mendix.systemwideinterfaces.core.IContext context, countriesv5.proxies.Country_ISO3166_1 demonym_country_iso3166_1)
	{
		if (demonym_country_iso3166_1 == null)
			getMendixObject().setValue(context, MemberNames.Demonym_Country_ISO3166_1.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Demonym_Country_ISO3166_1.toString(), demonym_country_iso3166_1.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return demonymMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final countriesv5.proxies.Demonym that = (countriesv5.proxies.Demonym) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CountriesV5.Demonym";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
