// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package countriesv5.proxies;

public class Nationality_Dutch_NEN1888
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nationality_Dutch_NEN1888MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CountriesV5.Nationality_Dutch_NEN1888";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NationaltyCodeString("NationaltyCodeString"),
		NationalityCodeInteger("NationalityCodeInteger"),
		Omschrijving("Omschrijving"),
		DatumIngang("DatumIngang"),
		DatumEinde("DatumEinde"),
		Country_ISO3166_1_Nationality_Dutch_NEN1888("CountriesV5.Country_ISO3166_1_Nationality_Dutch_NEN1888");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Nationality_Dutch_NEN1888(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CountriesV5.Nationality_Dutch_NEN1888"));
	}

	protected Nationality_Dutch_NEN1888(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nationality_Dutch_NEN1888MendixObject)
	{
		if (nationality_Dutch_NEN1888MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CountriesV5.Nationality_Dutch_NEN1888", nationality_Dutch_NEN1888MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CountriesV5.Nationality_Dutch_NEN1888");

		this.nationality_Dutch_NEN1888MendixObject = nationality_Dutch_NEN1888MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Nationality_Dutch_NEN1888.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static countriesv5.proxies.Nationality_Dutch_NEN1888 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return countriesv5.proxies.Nationality_Dutch_NEN1888.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static countriesv5.proxies.Nationality_Dutch_NEN1888 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new countriesv5.proxies.Nationality_Dutch_NEN1888(context, mendixObject);
	}

	public static countriesv5.proxies.Nationality_Dutch_NEN1888 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return countriesv5.proxies.Nationality_Dutch_NEN1888.initialize(context, mendixObject);
	}

	public static java.util.List<countriesv5.proxies.Nationality_Dutch_NEN1888> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<countriesv5.proxies.Nationality_Dutch_NEN1888> result = new java.util.ArrayList<countriesv5.proxies.Nationality_Dutch_NEN1888>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CountriesV5.Nationality_Dutch_NEN1888" + xpathConstraint))
			result.add(countriesv5.proxies.Nationality_Dutch_NEN1888.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NationaltyCodeString
	 */
	public final java.lang.String getNationaltyCodeString()
	{
		return getNationaltyCodeString(getContext());
	}

	/**
	 * @param context
	 * @return value of NationaltyCodeString
	 */
	public final java.lang.String getNationaltyCodeString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NationaltyCodeString.toString());
	}

	/**
	 * Set value of NationaltyCodeString
	 * @param nationaltycodestring
	 */
	public final void setNationaltyCodeString(java.lang.String nationaltycodestring)
	{
		setNationaltyCodeString(getContext(), nationaltycodestring);
	}

	/**
	 * Set value of NationaltyCodeString
	 * @param context
	 * @param nationaltycodestring
	 */
	public final void setNationaltyCodeString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nationaltycodestring)
	{
		getMendixObject().setValue(context, MemberNames.NationaltyCodeString.toString(), nationaltycodestring);
	}

	/**
	 * @return value of NationalityCodeInteger
	 */
	public final java.lang.Integer getNationalityCodeInteger()
	{
		return getNationalityCodeInteger(getContext());
	}

	/**
	 * @param context
	 * @return value of NationalityCodeInteger
	 */
	public final java.lang.Integer getNationalityCodeInteger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NationalityCodeInteger.toString());
	}

	/**
	 * Set value of NationalityCodeInteger
	 * @param nationalitycodeinteger
	 */
	public final void setNationalityCodeInteger(java.lang.Integer nationalitycodeinteger)
	{
		setNationalityCodeInteger(getContext(), nationalitycodeinteger);
	}

	/**
	 * Set value of NationalityCodeInteger
	 * @param context
	 * @param nationalitycodeinteger
	 */
	public final void setNationalityCodeInteger(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nationalitycodeinteger)
	{
		getMendixObject().setValue(context, MemberNames.NationalityCodeInteger.toString(), nationalitycodeinteger);
	}

	/**
	 * @return value of Omschrijving
	 */
	public final java.lang.String getOmschrijving()
	{
		return getOmschrijving(getContext());
	}

	/**
	 * @param context
	 * @return value of Omschrijving
	 */
	public final java.lang.String getOmschrijving(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Omschrijving.toString());
	}

	/**
	 * Set value of Omschrijving
	 * @param omschrijving
	 */
	public final void setOmschrijving(java.lang.String omschrijving)
	{
		setOmschrijving(getContext(), omschrijving);
	}

	/**
	 * Set value of Omschrijving
	 * @param context
	 * @param omschrijving
	 */
	public final void setOmschrijving(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String omschrijving)
	{
		getMendixObject().setValue(context, MemberNames.Omschrijving.toString(), omschrijving);
	}

	/**
	 * @return value of DatumIngang
	 */
	public final java.util.Date getDatumIngang()
	{
		return getDatumIngang(getContext());
	}

	/**
	 * @param context
	 * @return value of DatumIngang
	 */
	public final java.util.Date getDatumIngang(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DatumIngang.toString());
	}

	/**
	 * Set value of DatumIngang
	 * @param datumingang
	 */
	public final void setDatumIngang(java.util.Date datumingang)
	{
		setDatumIngang(getContext(), datumingang);
	}

	/**
	 * Set value of DatumIngang
	 * @param context
	 * @param datumingang
	 */
	public final void setDatumIngang(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datumingang)
	{
		getMendixObject().setValue(context, MemberNames.DatumIngang.toString(), datumingang);
	}

	/**
	 * @return value of DatumEinde
	 */
	public final java.util.Date getDatumEinde()
	{
		return getDatumEinde(getContext());
	}

	/**
	 * @param context
	 * @return value of DatumEinde
	 */
	public final java.util.Date getDatumEinde(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DatumEinde.toString());
	}

	/**
	 * Set value of DatumEinde
	 * @param datumeinde
	 */
	public final void setDatumEinde(java.util.Date datumeinde)
	{
		setDatumEinde(getContext(), datumeinde);
	}

	/**
	 * Set value of DatumEinde
	 * @param context
	 * @param datumeinde
	 */
	public final void setDatumEinde(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datumeinde)
	{
		getMendixObject().setValue(context, MemberNames.DatumEinde.toString(), datumeinde);
	}

	/**
	 * @return value of Country_ISO3166_1_Nationality_Dutch_NEN1888
	 */
	public final java.util.List<countriesv5.proxies.Country_ISO3166_1> getCountry_ISO3166_1_Nationality_Dutch_NEN1888() throws com.mendix.core.CoreException
	{
		return getCountry_ISO3166_1_Nationality_Dutch_NEN1888(getContext());
	}

	/**
	 * @param context
	 * @return value of Country_ISO3166_1_Nationality_Dutch_NEN1888
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<countriesv5.proxies.Country_ISO3166_1> getCountry_ISO3166_1_Nationality_Dutch_NEN1888(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<countriesv5.proxies.Country_ISO3166_1> result = new java.util.ArrayList<countriesv5.proxies.Country_ISO3166_1>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Country_ISO3166_1_Nationality_Dutch_NEN1888.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(countriesv5.proxies.Country_ISO3166_1.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Country_ISO3166_1_Nationality_Dutch_NEN1888
	 * @param country_iso3166_1_nationality_dutch_nen1888
	 */
	public final void setCountry_ISO3166_1_Nationality_Dutch_NEN1888(java.util.List<countriesv5.proxies.Country_ISO3166_1> country_iso3166_1_nationality_dutch_nen1888)
	{
		setCountry_ISO3166_1_Nationality_Dutch_NEN1888(getContext(), country_iso3166_1_nationality_dutch_nen1888);
	}

	/**
	 * Set value of Country_ISO3166_1_Nationality_Dutch_NEN1888
	 * @param context
	 * @param country_iso3166_1_nationality_dutch_nen1888
	 */
	public final void setCountry_ISO3166_1_Nationality_Dutch_NEN1888(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<countriesv5.proxies.Country_ISO3166_1> country_iso3166_1_nationality_dutch_nen1888)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (countriesv5.proxies.Country_ISO3166_1 proxyObject : country_iso3166_1_nationality_dutch_nen1888)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Country_ISO3166_1_Nationality_Dutch_NEN1888.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nationality_Dutch_NEN1888MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final countriesv5.proxies.Nationality_Dutch_NEN1888 that = (countriesv5.proxies.Nationality_Dutch_NEN1888) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CountriesV5.Nationality_Dutch_NEN1888";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
