// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package draganddroptrial.proxies;

public class CardDnD
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cardDnDMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DragAndDropTrial.CardDnD";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CardId("CardId"),
		Title("Title"),
		Description("Description"),
		CardDnD_CardDroptarget("DragAndDropTrial.CardDnD_CardDroptarget"),
		CardDnD_CardDragged("DragAndDropTrial.CardDnD_CardDragged");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CardDnD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DragAndDropTrial.CardDnD"));
	}

	protected CardDnD(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cardDnDMendixObject)
	{
		if (cardDnDMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DragAndDropTrial.CardDnD", cardDnDMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DragAndDropTrial.CardDnD");

		this.cardDnDMendixObject = cardDnDMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CardDnD.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static draganddroptrial.proxies.CardDnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return draganddroptrial.proxies.CardDnD.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static draganddroptrial.proxies.CardDnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new draganddroptrial.proxies.CardDnD(context, mendixObject);
	}

	public static draganddroptrial.proxies.CardDnD load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return draganddroptrial.proxies.CardDnD.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CardId
	 */
	public final java.lang.Integer getCardId()
	{
		return getCardId(getContext());
	}

	/**
	 * @param context
	 * @return value of CardId
	 */
	public final java.lang.Integer getCardId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CardId.toString());
	}

	/**
	 * Set value of CardId
	 * @param cardid
	 */
	public final void setCardId(java.lang.Integer cardid)
	{
		setCardId(getContext(), cardid);
	}

	/**
	 * Set value of CardId
	 * @param context
	 * @param cardid
	 */
	public final void setCardId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cardid)
	{
		getMendixObject().setValue(context, MemberNames.CardId.toString(), cardid);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of CardDnD_CardDroptarget
	 */
	public final draganddroptrial.proxies.Card getCardDnD_CardDroptarget() throws com.mendix.core.CoreException
	{
		return getCardDnD_CardDroptarget(getContext());
	}

	/**
	 * @param context
	 * @return value of CardDnD_CardDroptarget
	 */
	public final draganddroptrial.proxies.Card getCardDnD_CardDroptarget(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		draganddroptrial.proxies.Card result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CardDnD_CardDroptarget.toString());
		if (identifier != null)
			result = draganddroptrial.proxies.Card.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CardDnD_CardDroptarget
	 * @param carddnd_carddroptarget
	 */
	public final void setCardDnD_CardDroptarget(draganddroptrial.proxies.Card carddnd_carddroptarget)
	{
		setCardDnD_CardDroptarget(getContext(), carddnd_carddroptarget);
	}

	/**
	 * Set value of CardDnD_CardDroptarget
	 * @param context
	 * @param carddnd_carddroptarget
	 */
	public final void setCardDnD_CardDroptarget(com.mendix.systemwideinterfaces.core.IContext context, draganddroptrial.proxies.Card carddnd_carddroptarget)
	{
		if (carddnd_carddroptarget == null)
			getMendixObject().setValue(context, MemberNames.CardDnD_CardDroptarget.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CardDnD_CardDroptarget.toString(), carddnd_carddroptarget.getMendixObject().getId());
	}

	/**
	 * @return value of CardDnD_CardDragged
	 */
	public final draganddroptrial.proxies.Card getCardDnD_CardDragged() throws com.mendix.core.CoreException
	{
		return getCardDnD_CardDragged(getContext());
	}

	/**
	 * @param context
	 * @return value of CardDnD_CardDragged
	 */
	public final draganddroptrial.proxies.Card getCardDnD_CardDragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		draganddroptrial.proxies.Card result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CardDnD_CardDragged.toString());
		if (identifier != null)
			result = draganddroptrial.proxies.Card.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CardDnD_CardDragged
	 * @param carddnd_carddragged
	 */
	public final void setCardDnD_CardDragged(draganddroptrial.proxies.Card carddnd_carddragged)
	{
		setCardDnD_CardDragged(getContext(), carddnd_carddragged);
	}

	/**
	 * Set value of CardDnD_CardDragged
	 * @param context
	 * @param carddnd_carddragged
	 */
	public final void setCardDnD_CardDragged(com.mendix.systemwideinterfaces.core.IContext context, draganddroptrial.proxies.Card carddnd_carddragged)
	{
		if (carddnd_carddragged == null)
			getMendixObject().setValue(context, MemberNames.CardDnD_CardDragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CardDnD_CardDragged.toString(), carddnd_carddragged.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cardDnDMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final draganddroptrial.proxies.CardDnD that = (draganddroptrial.proxies.CardDnD) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DragAndDropTrial.CardDnD";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
