// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package draganddroptrial.proxies;

public class FileDoc extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DragAndDropTrial.FileDoc";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		FileDoc_Thing("DragAndDropTrial.FileDoc_Thing");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FileDoc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DragAndDropTrial.FileDoc"));
	}

	protected FileDoc(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fileDocMendixObject)
	{
		super(context, fileDocMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DragAndDropTrial.FileDoc", fileDocMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DragAndDropTrial.FileDoc");
	}

	/**
	 * @deprecated Use 'FileDoc.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static draganddroptrial.proxies.FileDoc initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return draganddroptrial.proxies.FileDoc.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static draganddroptrial.proxies.FileDoc initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new draganddroptrial.proxies.FileDoc(context, mendixObject);
	}

	public static draganddroptrial.proxies.FileDoc load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return draganddroptrial.proxies.FileDoc.initialize(context, mendixObject);
	}

	public static java.util.List<draganddroptrial.proxies.FileDoc> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<draganddroptrial.proxies.FileDoc> result = new java.util.ArrayList<draganddroptrial.proxies.FileDoc>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DragAndDropTrial.FileDoc" + xpathConstraint))
			result.add(draganddroptrial.proxies.FileDoc.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of FileDoc_Thing
	 */
	public final draganddroptrial.proxies.Thing getFileDoc_Thing() throws com.mendix.core.CoreException
	{
		return getFileDoc_Thing(getContext());
	}

	/**
	 * @param context
	 * @return value of FileDoc_Thing
	 */
	public final draganddroptrial.proxies.Thing getFileDoc_Thing(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		draganddroptrial.proxies.Thing result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FileDoc_Thing.toString());
		if (identifier != null)
			result = draganddroptrial.proxies.Thing.load(context, identifier);
		return result;
	}

	/**
	 * Set value of FileDoc_Thing
	 * @param filedoc_thing
	 */
	public final void setFileDoc_Thing(draganddroptrial.proxies.Thing filedoc_thing)
	{
		setFileDoc_Thing(getContext(), filedoc_thing);
	}

	/**
	 * Set value of FileDoc_Thing
	 * @param context
	 * @param filedoc_thing
	 */
	public final void setFileDoc_Thing(com.mendix.systemwideinterfaces.core.IContext context, draganddroptrial.proxies.Thing filedoc_thing)
	{
		if (filedoc_thing == null)
			getMendixObject().setValue(context, MemberNames.FileDoc_Thing.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.FileDoc_Thing.toString(), filedoc_thing.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final draganddroptrial.proxies.FileDoc that = (draganddroptrial.proxies.FileDoc) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DragAndDropTrial.FileDoc";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
