// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package draganddroptrial.proxies;

public class Thing
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject thingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DragAndDropTrial.Thing";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ThingsName("ThingsName");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Thing(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DragAndDropTrial.Thing"));
	}

	protected Thing(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject thingMendixObject)
	{
		if (thingMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DragAndDropTrial.Thing", thingMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DragAndDropTrial.Thing");

		this.thingMendixObject = thingMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Thing.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static draganddroptrial.proxies.Thing initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return draganddroptrial.proxies.Thing.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static draganddroptrial.proxies.Thing initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new draganddroptrial.proxies.Thing(context, mendixObject);
	}

	public static draganddroptrial.proxies.Thing load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return draganddroptrial.proxies.Thing.initialize(context, mendixObject);
	}

	public static java.util.List<draganddroptrial.proxies.Thing> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<draganddroptrial.proxies.Thing> result = new java.util.ArrayList<draganddroptrial.proxies.Thing>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DragAndDropTrial.Thing" + xpathConstraint))
			result.add(draganddroptrial.proxies.Thing.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ThingsName
	 */
	public final java.lang.String getThingsName()
	{
		return getThingsName(getContext());
	}

	/**
	 * @param context
	 * @return value of ThingsName
	 */
	public final java.lang.String getThingsName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ThingsName.toString());
	}

	/**
	 * Set value of ThingsName
	 * @param thingsname
	 */
	public final void setThingsName(java.lang.String thingsname)
	{
		setThingsName(getContext(), thingsname);
	}

	/**
	 * Set value of ThingsName
	 * @param context
	 * @param thingsname
	 */
	public final void setThingsName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String thingsname)
	{
		getMendixObject().setValue(context, MemberNames.ThingsName.toString(), thingsname);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return thingMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final draganddroptrial.proxies.Thing that = (draganddroptrial.proxies.Thing) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DragAndDropTrial.Thing";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
