// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package widgets.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Widgets module
	public static widgets.proxies.Thing dS_Thing_Get(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Widgets.DS_Thing_Get").withParams(params).execute(context);
		return result == null ? null : widgets.proxies.Thing.initialize(context, result);
	}
	public static widgets.proxies.Thing dSS_CreateTestObject(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Widgets.DSS_CreateTestObject").withParams(params).execute(context);
		return result == null ? null : widgets.proxies.Thing.initialize(context, result);
	}
	public static void validation_Microflow(IContext context, widgets.proxies.Thing _thing)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Thing", _thing == null ? null : _thing.getMendixObject());
		Core.microflowCall("Widgets.Validation_Microflow").withParams(params).execute(context);
	}
}