// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package systemmanagement.proxies;

/**
 * Used for calculating totals in overviews that group on an attribute.
 */
public class CountHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject countHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SystemManagement.CountHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Count("Count"),
		CountHelper_Language("SystemManagement.CountHelper_Language"),
		CountHelper_UserRole("SystemManagement.CountHelper_UserRole");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CountHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SystemManagement.CountHelper"));
	}

	protected CountHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject countHelperMendixObject)
	{
		if (countHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SystemManagement.CountHelper", countHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SystemManagement.CountHelper");

		this.countHelperMendixObject = countHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CountHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static systemmanagement.proxies.CountHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return systemmanagement.proxies.CountHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static systemmanagement.proxies.CountHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new systemmanagement.proxies.CountHelper(context, mendixObject);
	}

	public static systemmanagement.proxies.CountHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return systemmanagement.proxies.CountHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Count
	 */
	public final java.lang.Integer getCount()
	{
		return getCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Count
	 */
	public final java.lang.Integer getCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Count.toString());
	}

	/**
	 * Set value of Count
	 * @param count
	 */
	public final void setCount(java.lang.Integer count)
	{
		setCount(getContext(), count);
	}

	/**
	 * Set value of Count
	 * @param context
	 * @param count
	 */
	public final void setCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer count)
	{
		getMendixObject().setValue(context, MemberNames.Count.toString(), count);
	}

	/**
	 * @return value of CountHelper_Language
	 */
	public final system.proxies.Language getCountHelper_Language() throws com.mendix.core.CoreException
	{
		return getCountHelper_Language(getContext());
	}

	/**
	 * @param context
	 * @return value of CountHelper_Language
	 */
	public final system.proxies.Language getCountHelper_Language(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Language result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CountHelper_Language.toString());
		if (identifier != null)
			result = system.proxies.Language.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CountHelper_Language
	 * @param counthelper_language
	 */
	public final void setCountHelper_Language(system.proxies.Language counthelper_language)
	{
		setCountHelper_Language(getContext(), counthelper_language);
	}

	/**
	 * Set value of CountHelper_Language
	 * @param context
	 * @param counthelper_language
	 */
	public final void setCountHelper_Language(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Language counthelper_language)
	{
		if (counthelper_language == null)
			getMendixObject().setValue(context, MemberNames.CountHelper_Language.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CountHelper_Language.toString(), counthelper_language.getMendixObject().getId());
	}

	/**
	 * @return value of CountHelper_UserRole
	 */
	public final system.proxies.UserRole getCountHelper_UserRole() throws com.mendix.core.CoreException
	{
		return getCountHelper_UserRole(getContext());
	}

	/**
	 * @param context
	 * @return value of CountHelper_UserRole
	 */
	public final system.proxies.UserRole getCountHelper_UserRole(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.UserRole result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CountHelper_UserRole.toString());
		if (identifier != null)
			result = system.proxies.UserRole.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CountHelper_UserRole
	 * @param counthelper_userrole
	 */
	public final void setCountHelper_UserRole(system.proxies.UserRole counthelper_userrole)
	{
		setCountHelper_UserRole(getContext(), counthelper_userrole);
	}

	/**
	 * Set value of CountHelper_UserRole
	 * @param context
	 * @param counthelper_userrole
	 */
	public final void setCountHelper_UserRole(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.UserRole counthelper_userrole)
	{
		if (counthelper_userrole == null)
			getMendixObject().setValue(context, MemberNames.CountHelper_UserRole.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CountHelper_UserRole.toString(), counthelper_userrole.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return countHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final systemmanagement.proxies.CountHelper that = (systemmanagement.proxies.CountHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SystemManagement.CountHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
