// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package parallelexecute.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the ParallelExecute module

	/**
	* we recommend to keep it below 500
	* 
	* to override this number for a particular call use the CustomOptions variants of the functions
	*/
	public static java.lang.Long getDEFAULT_NUMBER_PARALLEL_THREADS()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("ParallelExecute.DEFAULT_NUMBER_PARALLEL_THREADS");
	}

	/**
	* in milliseconds, this is the timeout for the entire list not a single element
	* 
	* to override this number for a particular call use the CustomOptions variants of the functions
	*/
	public static java.lang.Long getDEFAULT_TIMEOUT_MS()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("ParallelExecute.DEFAULT_TIMEOUT_MS");
	}
}