// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sprintrapis2.proxies;

/**
 * Copied from https://docs.mendix.com/apidocs-mxsdk/apidocs/deploy-api
 */
public class DeploymentPackage
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject deploymentPackageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SprintrApis2.DeploymentPackage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PackageID("PackageID"),
		Name("Name"),
		Description("Description"),
		Version("Version"),
		Creator("Creator"),
		CreationDate("CreationDate"),
		Status("Status"),
		Size("Size"),
		DeploymentPackage_App("SprintrApis2.DeploymentPackage_App");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DeploymentPackage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SprintrApis2.DeploymentPackage"));
	}

	protected DeploymentPackage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject deploymentPackageMendixObject)
	{
		if (deploymentPackageMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SprintrApis2.DeploymentPackage", deploymentPackageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SprintrApis2.DeploymentPackage");

		this.deploymentPackageMendixObject = deploymentPackageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DeploymentPackage.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sprintrapis2.proxies.DeploymentPackage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sprintrapis2.proxies.DeploymentPackage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sprintrapis2.proxies.DeploymentPackage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sprintrapis2.proxies.DeploymentPackage(context, mendixObject);
	}

	public static sprintrapis2.proxies.DeploymentPackage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sprintrapis2.proxies.DeploymentPackage.initialize(context, mendixObject);
	}

	public static java.util.List<sprintrapis2.proxies.DeploymentPackage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<sprintrapis2.proxies.DeploymentPackage> result = new java.util.ArrayList<sprintrapis2.proxies.DeploymentPackage>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SprintrApis2.DeploymentPackage" + xpathConstraint))
			result.add(sprintrapis2.proxies.DeploymentPackage.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of PackageID
	 */
	public final java.lang.String getPackageID()
	{
		return getPackageID(getContext());
	}

	/**
	 * @param context
	 * @return value of PackageID
	 */
	public final java.lang.String getPackageID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PackageID.toString());
	}

	/**
	 * Set value of PackageID
	 * @param packageid
	 */
	public final void setPackageID(java.lang.String packageid)
	{
		setPackageID(getContext(), packageid);
	}

	/**
	 * Set value of PackageID
	 * @param context
	 * @param packageid
	 */
	public final void setPackageID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String packageid)
	{
		getMendixObject().setValue(context, MemberNames.PackageID.toString(), packageid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Version
	 */
	public final java.lang.String getVersion()
	{
		return getVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of Version
	 */
	public final java.lang.String getVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Version.toString());
	}

	/**
	 * Set value of Version
	 * @param version
	 */
	public final void setVersion(java.lang.String version)
	{
		setVersion(getContext(), version);
	}

	/**
	 * Set value of Version
	 * @param context
	 * @param version
	 */
	public final void setVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String version)
	{
		getMendixObject().setValue(context, MemberNames.Version.toString(), version);
	}

	/**
	 * @return value of Creator
	 */
	public final java.lang.String getCreator()
	{
		return getCreator(getContext());
	}

	/**
	 * @param context
	 * @return value of Creator
	 */
	public final java.lang.String getCreator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Creator.toString());
	}

	/**
	 * Set value of Creator
	 * @param creator
	 */
	public final void setCreator(java.lang.String creator)
	{
		setCreator(getContext(), creator);
	}

	/**
	 * Set value of Creator
	 * @param context
	 * @param creator
	 */
	public final void setCreator(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String creator)
	{
		getMendixObject().setValue(context, MemberNames.Creator.toString(), creator);
	}

	/**
	 * @return value of CreationDate
	 */
	public final java.util.Date getCreationDate()
	{
		return getCreationDate(getContext());
	}

	/**
	 * @param context
	 * @return value of CreationDate
	 */
	public final java.util.Date getCreationDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreationDate.toString());
	}

	/**
	 * Set value of CreationDate
	 * @param creationdate
	 */
	public final void setCreationDate(java.util.Date creationdate)
	{
		setCreationDate(getContext(), creationdate);
	}

	/**
	 * Set value of CreationDate
	 * @param context
	 * @param creationdate
	 */
	public final void setCreationDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date creationdate)
	{
		getMendixObject().setValue(context, MemberNames.CreationDate.toString(), creationdate);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of Size
	 */
	public final java.lang.Long getSize()
	{
		return getSize(getContext());
	}

	/**
	 * @param context
	 * @return value of Size
	 */
	public final java.lang.Long getSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Size.toString());
	}

	/**
	 * Set value of Size
	 * @param size
	 */
	public final void setSize(java.lang.Long size)
	{
		setSize(getContext(), size);
	}

	/**
	 * Set value of Size
	 * @param context
	 * @param size
	 */
	public final void setSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long size)
	{
		getMendixObject().setValue(context, MemberNames.Size.toString(), size);
	}

	/**
	 * @return value of DeploymentPackage_App
	 */
	public final sprintrapis2.proxies.App getDeploymentPackage_App() throws com.mendix.core.CoreException
	{
		return getDeploymentPackage_App(getContext());
	}

	/**
	 * @param context
	 * @return value of DeploymentPackage_App
	 */
	public final sprintrapis2.proxies.App getDeploymentPackage_App(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sprintrapis2.proxies.App result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DeploymentPackage_App.toString());
		if (identifier != null)
			result = sprintrapis2.proxies.App.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DeploymentPackage_App
	 * @param deploymentpackage_app
	 */
	public final void setDeploymentPackage_App(sprintrapis2.proxies.App deploymentpackage_app)
	{
		setDeploymentPackage_App(getContext(), deploymentpackage_app);
	}

	/**
	 * Set value of DeploymentPackage_App
	 * @param context
	 * @param deploymentpackage_app
	 */
	public final void setDeploymentPackage_App(com.mendix.systemwideinterfaces.core.IContext context, sprintrapis2.proxies.App deploymentpackage_app)
	{
		if (deploymentpackage_app == null)
			getMendixObject().setValue(context, MemberNames.DeploymentPackage_App.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DeploymentPackage_App.toString(), deploymentpackage_app.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return deploymentPackageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sprintrapis2.proxies.DeploymentPackage that = (sprintrapis2.proxies.DeploymentPackage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SprintrApis2.DeploymentPackage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
