// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sprintrapis2.proxies;

public class Story
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject storyMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SprintrApis2.Story";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		StoryId("StoryId"),
		Story_App("SprintrApis2.Story_App");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Story(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SprintrApis2.Story"));
	}

	protected Story(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject storyMendixObject)
	{
		if (storyMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SprintrApis2.Story", storyMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SprintrApis2.Story");

		this.storyMendixObject = storyMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Story.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sprintrapis2.proxies.Story initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sprintrapis2.proxies.Story.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sprintrapis2.proxies.Story initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sprintrapis2.proxies.Story(context, mendixObject);
	}

	public static sprintrapis2.proxies.Story load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sprintrapis2.proxies.Story.initialize(context, mendixObject);
	}

	public static java.util.List<sprintrapis2.proxies.Story> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<sprintrapis2.proxies.Story> result = new java.util.ArrayList<sprintrapis2.proxies.Story>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SprintrApis2.Story" + xpathConstraint))
			result.add(sprintrapis2.proxies.Story.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of StoryId
	 */
	public final java.lang.String getStoryId()
	{
		return getStoryId(getContext());
	}

	/**
	 * @param context
	 * @return value of StoryId
	 */
	public final java.lang.String getStoryId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StoryId.toString());
	}

	/**
	 * Set value of StoryId
	 * @param storyid
	 */
	public final void setStoryId(java.lang.String storyid)
	{
		setStoryId(getContext(), storyid);
	}

	/**
	 * Set value of StoryId
	 * @param context
	 * @param storyid
	 */
	public final void setStoryId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String storyid)
	{
		getMendixObject().setValue(context, MemberNames.StoryId.toString(), storyid);
	}

	/**
	 * @return value of Story_App
	 */
	public final sprintrapis2.proxies.App getStory_App() throws com.mendix.core.CoreException
	{
		return getStory_App(getContext());
	}

	/**
	 * @param context
	 * @return value of Story_App
	 */
	public final sprintrapis2.proxies.App getStory_App(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sprintrapis2.proxies.App result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Story_App.toString());
		if (identifier != null)
			result = sprintrapis2.proxies.App.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Story_App
	 * @param story_app
	 */
	public final void setStory_App(sprintrapis2.proxies.App story_app)
	{
		setStory_App(getContext(), story_app);
	}

	/**
	 * Set value of Story_App
	 * @param context
	 * @param story_app
	 */
	public final void setStory_App(com.mendix.systemwideinterfaces.core.IContext context, sprintrapis2.proxies.App story_app)
	{
		if (story_app == null)
			getMendixObject().setValue(context, MemberNames.Story_App.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Story_App.toString(), story_app.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return storyMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sprintrapis2.proxies.Story that = (sprintrapis2.proxies.Story) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SprintrApis2.Story";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
